### ISSUE TITLE
歌词搜索默认显示网易云

### ISSUE THREAD

**Issue by Bacon257** [ESLyric/feedback#1]
一旦歌词成功匹配，歌词搜索默认显示网易云歌词，再次点击“搜索”按钮后，才显示其他平台的歌词。
希望能一次性显示已勾选平台的歌词列表
![image](https://user-images.githubusercontent.com/100892568/162699621-59174810-6b33-4b8c-b409-725907496acb.png)
![image](https://user-images.githubusercontent.com/100892568/162699683-bab802c1-8f6c-4c2e-aa01-f03250e01db5.png)
![image](https://user-images.githubusercontent.com/100892568/162700411-d672547c-aae7-4793-84e0-f4adcff2d984.png)

若匹配失败，点击“歌词搜索”正常显示
![image](https://user-images.githubusercontent.com/100892568/162700360-1b44348d-526f-4c37-b9f8-3c4c0d9255bb.png)

另外想问一下，歌词匹配度是如何计算的，搜索结果是否根据匹配度排序了？
非常感谢你开发的插件！

**Comment by ESLyric** [comment]
> 一旦歌词成功匹配，歌词搜索默认显示网易云歌词，再次点击“搜索”按钮后，才显示其他平台的歌词。
> 希望能一次性显示已勾选平台的歌词列表

正常情况下会显示所有来源的歌词，如果没有显示可能是这一次的自动搜索并没有搜到。
现在在线歌词源使用同样的关键词多次搜索有可能出现搜索结果不同的情况，印象中对应歌词源返回了空的结果，暂没有进一步确认是否是插件或歌词源脚本问题。

> 若匹配失败，点击“歌词搜索”正常显示

手动搜索的区别除开上述问题的差异外，手动搜索内部不会处理搜索的关键词，包含移除一些特殊字符，转换为简体等。如果排除多次搜索结果的差异外，可以提供下相关的关键词看看。

> 另外想问一下，歌词匹配度是如何计算的，搜索结果是否根据匹配度排序了？  

现在匹配度使用最常用的字符串相似度算法，综合关键词预处理等。搜索结果是根据匹配度排序的。

**Comment by Bacon257** [comment]
感谢回复，我还在使用ctrl+左键设置offset时碰到了一些问题，歌词面板不能实时显示效果。反馈在q群内了

**Comment by dghgw** [comment]
CTRL+鼠标调整歌词时，不象原版可以一个字一个字的调整，希望能改成原来那种可以一个字一个字的调整。保存歌词也应象旧版那样有得选择是覆盖还是别的，搜酷狗歌词时希望不用填写艺术家就能自动识别。

**Comment by a1waysbeta** [comment]
> CTRL+鼠标调整歌词时，不象原版可以一个字一个字的调整，希望能改成原来那种可以一个字一个字的调整。保存歌词也应象旧版那样有得选择是覆盖还是别的，搜酷狗歌词时希望不用填写艺术家就能自动识别。

开启卡拉OK效果，再调整，就方便识别调整到字。同样，歌词面板右键有保存菜单。

**Comment by dghgw** [comment]
我是开启了卡拉模式后，CLRL+鼠标是调歌词快慢一句歌词一句歌词的调，没显示一个字一个字的调，老版的是显示到一个字一个字的调的。另我说的是参数设置里，现在的保存歌词文件是覆盖原来的还是另存，老板本是可以选择性的

**Comment by ESLyric** [comment]
调整显示的暂时不考虑保持一致了，如果这个功能你很在意可以继续用老版本的。
另外，老版本作者很久没有用过了，一些表现也没什么印象，因此后几个问题需要详细提供详细说明。
麻烦另外开一个issue，这个先关闭了。
