### ISSUE TITLE
如何新增musixmatch歌詞來源

### ISSUE THREAD

**Issue by aunight** [ESLyric/feedback#10]
希望有腳本可以新增musixmatch的歌詞來源
或是任何日文歌曲的歌詞來源

**Comment by ESLyric** [comment]
请参考
https://github.com/ESLyric/release/wiki/%E6%AD%8C%E8%AF%8D%E6%BA%90%E5%8F%8A%E8%A7%A3%E6%9E%90%E5%99%A8%E8%84%9A%E6%9C%AC

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1117
