### ISSUE TITLE
桌面歌词垂直滚动功能请求

### ISSUE THREAD

**Issue by bao230503** [ESLyric/feedback#100]
**新功能或功能增强**
1.请问能否新增桌面歌词垂直滚动？
2.请问能否为桌面歌词增加背景透明度设置？

**功能简介**
效果差不多是歌词面板的垂直滚动效果。

**是否有参考软件实现**
![垂直滚动](https://github.com/ESLyric/feedback/assets/132416523/24a5f284-ac75-4931-aa81-bfac5e8ac7e9)

**Comment by ESLyric** [comment]
1. 没有计划
2. 没有计划
