### ISSUE TITLE
(regression, Wine) 歌词背景闪灭

### ISSUE THREAD

**Issue by szc126** [ESLyric/feedback#101]
**问题描述**
歌词背景（专辑封面）闪灭，仅Wine环境，因为属于 eslyric alpha 版的 regression bug 所以觉得值得报错，不过如果维护者觉得 wine 过于小众不值得费心，也是无所谓的。

 - Wine 8.12 + 0.5.3.1031 没问题
 - Windows 10 + 0.5.4.1001 Alpha 没问题

**重现步骤**
重现该问题的步骤:
1. 开启歌词背景（专辑封面），播放音乐

**期望表现**
简要清晰的表述你期望的表现

1. 歌词背景正常表示

**截图**
如可能，请添加截图帮助阐述问题

https://user-images.githubusercontent.com/29127915/254099009-10fad486-181f-4c33-9a78-afae8245c72c.webm

**软件环境:**
 - Wine 8.12
 - foobar2000 v2.0
 - eslyric 0.5.4.1001 Alpha

**其他信息**

**Comment by ESLyric** [comment]
具体原因没看，不过会针对wine简单特殊处理。

**Comment by ESLyric** [comment]
可以试下最新的alpha版

**Comment by szc126** [comment]
没问题了，谢谢！
