### ISSUE TITLE
已解决：正则表达式 Regex Match 设置过滤自定义原生配乐类

### ISSUE THREAD

**Issue by kazegh** [ESLyric/feedback#104]
**问题描述**
搜索过滤功能     正则必须写成这样才生效  ：  （用%album%或文件名） 
.\*配乐.\*|.\*纯音乐.\*|.\*伴奏.\*|.\*原声.\*|.\*O.S.T.\*|.\*OST.\*|.\*Original Soundtrack.\*
实际上应该简洁写成下面，效果一样的：（.代表任意字符，*重复0次及以上，就是.*可以忽略，意思是任意字符重复0次及以上）
配乐|纯音乐|伴奏

JAVASCRIPT正则匹配字符示例:
'125533'.match(/125/)[0] 得125
'125533'.match(/.\*125.\*/)[0] 得全字符125533

**期望表现**
小问题而已，改不改随你。不改的话上面的第二种示例从逻辑上应该是正确的但就是不行。

**Comment by kazegh** [comment]
发现之前打的字全部掉星号字符，现已改正，。

**Comment by ESLyric** [comment]
感谢反馈，下个版本会修正下~

**Comment by ESLyric** [comment]
可以试下最新版看看

**Comment by kazegh** [comment]
试过了，很好，非常感谢
