### ISSUE TITLE
Please restore the ability to toggle on/off all Field Processing

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#105]
Using version 0.5.4.1005, 64-bit.  I noticed that this version no longer has the ability to enable/disable all Field Processing with a check-box, which was present in all previous versions.  Please restore this helpful feature.  Thank you very much.

Windows 10x64, Foobar v2.1 preview 2023-08-11, 64-bit.

**Comment by ESLyric** [comment]
I will add entry switch instead.

**Comment by ESLyric** [comment]
toggle every single field instead the global switch. btw, it may be better to modify the search script
