### ISSUE TITLE
Lyric text synchronization for radio stream tracks

### ISSUE THREAD

**Issue by amigx** [ESLyric/feedback#106]
It looks like ESLyric doesn't synchronize text scrolling of lyrics when playing radio streams.
The time for timestamps is determined by the start time of the playback of the radio stream.
This time is not reset after changing the name of the radio stream track.
For this reason, after a while of playing the radio stream (after 7-10 minutes), only the end of the text of the lyrics is displayed.
Link to the radio stream for an example `http://mistralfmaubagne.ice.infomaniak.ch/mistralfmaubagne-128.mp3`

**Comment by ESLyric** [comment]
It seems there is no way to sync progress, it may be more reasonable to display unsync lyrics.

**Comment by amigx** [comment]
Resetting the offset when changing the name/artist of the radio stream track will allow scrolling of the text of the lyrics to start from the first line. Of course there is no way to sync, but scrolling lyrics will look good. This would be another advantage of the component.

**Comment by amigx** [comment]
ES Lyric v0.5.4.1006
There is a noticeable improvement in the quality of searching for the Internet radio lyrics.
As before, the text of the lyrics is displayed not from the beginning, but from the end of the text, starting from the second track from the beginning playback the radio stream.

My fb2k layout now has two different lyrics search panel. 
I think ESLyric will be better in time.

Thank you for your efforts!
