### ISSUE TITLE
Start unsynced lyrics at the top of the panel

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#107]
Am using .5.4.1006 in Foobar v2.1 64-bit and very impressed with the speed of radio stream lyrics retrieval and the ability to toggle on/off various search processing--thank you!

All versions however will start the display of the lyrics about half-way down from the top panel margin in Foobar (see attached image).  Is there any way to provide an option to begin the display at the TOP for unsynced lyrics?  I've tried adjusting the margin values, etc within the panel preferences and still can't get the start point any closer than about 30% from the top.

![hdjms08](https://github.com/ESLyric/feedback/assets/130251824/81b8424e-c08b-4e99-8756-23a340052c2c)

**Comment by ESLyric** [comment]
No such settings.

**Comment by ESLyric** [comment]
A very personalized settings?
