### ISSUE TITLE
问题反馈 “全屏歌词设置-面板参数选项”中，“高亮行歌词偏移”一旦调整参数，就无法调整为负值

### ISSUE THREAD

**Issue by charles7580** [ESLyric/feedback#108]
**问题描述**
“全屏歌词设置-面板参数选项”中，“高亮行歌词偏移”一旦调整参数，就无法调整为负值

**重现步骤**
重现该问题的步骤:
1. 进入全屏歌词
2. 右键选择全屏歌词设置
3. 调整“高亮行歌词偏移”

**期望表现**
希望能够自行调整负值

**软件环境:**
 - Windows 10 19045.3324
 - foobar2000 1.6.11

**Comment by charles7580** [comment]
歌词渐隐后面的参数调整貌似也是无效的，只能拥有默认的效果

**Comment by ESLyric** [comment]
什么情况下会使用到负值？

**Comment by charles7580** [comment]
默认就是-1吧好像😂不过实测也确实没有用到负值的地方；不过歌词渐隐的参数好像是没生效的

**Comment by ESLyric** [comment]
那是某几个版本的默认值，后面废弃了。0就是默认值。

**Comment by charles7580** [comment]
哦哦明白了感谢

**Comment by ESLyric** [comment]
歌词渐隐设置是正常的，如果没其他的问题可以把issue关掉。
