### ISSUE TITLE
Performance issue - invalid buffer in minilyrics.js source

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#109]
How to reproduce:
1. Install foobar as portable.
2. Download and install Georgia-ReBORN master from [here](https://github.com/TT-ReBORN/Georgia-ReBORN/archive/331ffb16800d23caded9195c93aa81f72fc1df7e.zip).
3. Copy profile folder from zip to root foobar and start foobar.
4. Download this song and drag and drop to playlist. [Test_song.zip](https://github.com/ESLyric/feedback/files/12445259/Test_song.zip)
5. Play the test song and close foobar, it will freeze.

---

Hi ohyeah,

multiple user have reported to me that they have big performance issues when trying to close foobar, it becomes unresponsive and freezes. 
I could reproduce this issue on my notebook. When trying to close foobar, my CPU usage is very high.
It took me a while to debug this but the issue is in eslyric-data/scripts/searcher/minilyrics.js

I have cleaned up the code, there was also an issue in `class CompressedXmlReader`

```
       position = 0;
       stringTable = [];
```

needs to be in the constructor:

```
class CompressedXmlReader {
    constructor(buffer) {
        this.position = 0;
        this.stringTable = [];
        this.buffer = new DataView(buffer);
    }
```

Here is the cleaned version: [minilyrics_cleaned.zip](https://github.com/ESLyric/feedback/files/12445292/minilyrics_cleaned.zip)

---

What I have found out is that it seems the calculation of the buffer size is causing the freeze or the conversion.
When removing `stSize` from `this.cxmlBody = new ArrayBuffer(2 + 4 + 4 + 9 + stSize + 2);` the freeze will stop
but of course the buffer does not work correctly anymore. I have tried to search for `stringToArrayBuffer` but I did not find it in the files.

I'm not familiar with this cryptographic and buffer stuff, can you take over and fix it please?
Thanks!

-TT

**Comment by ESLyric** [comment]
It seems this source has broken now. I cannot access http://search.crintsoft.com/searchlyrics.htm. And ESLyric request this site timeout, which seems freezed.
ESLyric uses thread to search lyrics and will join threads when exit. you could alter this behavior by changing the advanced property `pref.debug.thread.join`  to `0`.

**Comment by TT-ReBORN** [comment]
Yes http://search.crintsoft.com/searchlyrics.htm is down but the website not, I guess they changed their API or closed? 
But I did not thought it would break the buffer? Should be handled better to avoid such cases in the future.

I can confirm, pref.debug.thread.join = 0 seems to work great, immediate exit.
But what will you do for the general public who uses your ESLyrics, make this default behavior ( pref.debug.thread.join = 0 ) or will you remove ( or add error handling ) the minilyrics source for next ESLyrics version?

**Comment by ESLyric** [comment]
Not buffer related. Just blocked by internet request. Maybe changing default behavior if applicable.

**Comment by TT-ReBORN** [comment]
@ESLyric,

minilyrics works again, I have restored it in my theme but kept `pref.debug.thread.join = 0` setting.
Don't forgot to put the cleaned minilyrics.js version from the first post in your next release, thanks!

-Tom

**Comment by ESLyric** [comment]
> @ESLyric,
> 
> minilyrics works again, I have restored it in my theme but kept `pref.debug.thread.join = 0` setting. Don't forgot to put the cleaned minilyrics.js version from the [first post](https://github.com/ESLyric/feedback/issues/109#issue-1868072043) in your next release, thanks!
> 
> -Tom

Thanks. Updated. 
https://github.com/ESLyric/scripts/blob/main/searcher/minilyrics.js
