### ISSUE TITLE
ESLyric问题反馈

### ISSUE THREAD

**Issue by LORLEE** [ESLyric/feedback#11]
**问题描述**
foobar2000中，ESLyric选择中文字体时会变成竖向

**重现步骤**
重现该问题的步骤:
1. 在foobar2000在右边歌词选择面板参数时，选择字体
2. 在选择了中文的字体后，字体会变成竖向

**期望表现**
修复

**截图**
![image](https://user-images.githubusercontent.com/44886273/179405550-a147771b-7112-4134-9f39-1f8d5674f303.png)
![image](https://user-images.githubusercontent.com/44886273/179405584-9f9dba02-d51f-4a4c-90fb-4140d3b754cb.png)
![image](https://user-images.githubusercontent.com/44886273/179405601-3ce5bf4a-9ba6-43fe-8da4-9de55a475f36.png)

**软件环境:**
 - win11 25158.1000/25151.1000(更新系统后仍然出现)
 - foobar2000版本 (1.3.16)

**Comment by ESLyric** [comment]
不要选择前面有@ 前缀的字体
