### ISSUE TITLE
全屏歌词界面专辑图片偶尔不匹配

### ISSUE THREAD

**Issue by charles7580** [ESLyric/feedback#111]
**问题描述**
在全屏歌词界面下，背景专辑图片偶尔会出现不匹配的情况（貌似是之前随机播放过的歌曲封面）

**重现步骤**
1. 播放若干首歌曲
2. 切换多次全屏歌词界面

**截图**
![Snipaste_2023-08-30_10-56-49](https://github.com/ESLyric/feedback/assets/25521003/962e6c41-4136-4631-88b4-5b01dd821303)
![Snipaste_2023-08-30_10-57-01](https://github.com/ESLyric/feedback/assets/25521003/9667e48d-93c0-4997-84db-5ce269b5ef40)

**软件环境:**
 - Windows 10 19045.3324
 - foobar2000 2.0

**Comment by ESLyric** [comment]
好的，有时间我重现下。

**Comment by ESLyric** [comment]
没有重现出来，是否设置有其他歌词背景来源？

**Comment by charles7580** [comment]
> 没有重现出来，是否设置有其他歌词背景来源？

就如图所示的设置，切换全屏歌词后，不断切换下一首，一会儿就会出现不匹配的情况：
![Snipaste_2023-09-02_21-18-45](https://github.com/ESLyric/feedback/assets/25521003/ba59f841-f837-4bd3-b9fa-c66fc306bc0d)
如图，实际播放为暗杠的《童话镇》，专辑名《童话镇》；而背景显示的是4首歌之前的曹方的《风吹过下雨天》，专辑名《遇见我》

**Comment by ESLyric** [comment]
没有重现。麻烦截图一下这里的配置。以及当前播放歌曲路径以及封面路径/是否内嵌。
![image](https://github.com/ESLyric/feedback/assets/102273569/7797bf9f-2d96-4996-affe-5c61dbe32fbc)

**Comment by charles7580** [comment]
> 没有重现。麻烦截图一下这里的配置。以及当前播放歌曲路径以及封面路径/是否内嵌。 ![image](https://user-images.githubusercontent.com/102273569/265275420-7797bf9f-2d96-4996-affe-5c61dbe32fbc.png)

![Snipaste_2023-09-04_10-14-46](https://github.com/ESLyric/feedback/assets/25521003/1090a185-6881-4147-9df9-768ee3b95edf)
歌曲路径：D:\Audio\Music\Cool\暗杠 - 童话镇.flac  D:\Audio\Music\Cool\曹方 - 风吹过下雨天.flac
封面均已内嵌。
不过刚刚在查询路径的时候我貌似已经找到了问题源头，有些歌曲拥有“音轨号”或“碟片编号”，有些歌曲则没有。出现问题的好像均是前者，貌似是软件把它们识别成了同一张专辑……我批量删除了这两个属性，再试试

**Comment by charles7580** [comment]
貌似不是“音轨号”和“碟片编号”，都清零之后还是会出现，如图（Windows音量界面中是正确的封面）
![Snipaste_2023-09-04_11-04-12](https://github.com/ESLyric/feedback/assets/25521003/6498130e-0463-4dbb-aaff-52a43dcc5d7d)
![Snipaste_2023-09-04_11-04-23](https://github.com/ESLyric/feedback/assets/25521003/cd724469-5951-4e27-83ac-3ec1c46627fc)

**Comment by ESLyric** [comment]
如果可以打包的话，麻烦把能够重现的最小环境打包下，包含使用到的歌曲。

**Comment by charles7580** [comment]
我这边也是偶发情况，也不是每次都能复现，也困扰……等我能稳定复现的时候会第一时间上传环境
