### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xuedeer** [ESLyric/feedback#112]
qq音乐和qq音乐ex的源不显示标题艺术家,就是一片空白

![2023-09-03_231116](https://github.com/ESLyric/feedback/assets/32856677/a199d5e8-7826-4504-8c1e-719699366e71)

 Windows 10 19044.1682
 foobar2000版本 1.6.16

**Comment by a1waysbeta** [comment]
是只有这一首还是很多？把歌曲标题复制上来看看
