### ISSUE TITLE
Lyric Editor window disappeared after its window was minimized

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#113]
**Describe the bug**
1) Right-click and select "Edit Lyric" to open the Lyric Editor. 
2) Minimize the Lyric Editor window by **clicking the minus "-"** on the top right corner. 
3) The Lyric Editor window disappeared because **the Editor window was sent behind all other windows**. 

<img width="578" alt="Capture" src="https://github.com/ESLyric/feedback/assets/76891201/4efd6899-f7e1-4621-9e34-8dcb2bf03ce4">

4) Right-click again and select "Edit Lyric", the Lyric Editor is just minimized and will not maximize. 
<img width="122" alt="Capture1" src="https://github.com/ESLyric/feedback/assets/76891201/5880a08c-967c-4fd6-aa2e-e7b6ed5ee722">

5) The minimized window can be maximized by clicking the "small  square(s)", but occasionally **cannot be closed by clicking the "X"** although the background changed to Red (as above screenshot).

6) Changing the option to "Always on top" will let the window stay on the front, but it covers the status display.
<img width="292" alt="Captureyyy" src="https://github.com/ESLyric/feedback/assets/76891201/267044cd-6808-480a-aa2d-014ac976f332">

Wishes: 
1) The Lyric Editor window should be **minimized on taskbar** after clicking the minus "-".
2) Whenever, right-click and select "Edit Lyric", the Lyric Editor will maximize its window no matter whether the "Always on top" option is ticked or not. 

**Desktop (please complete the following information):**
 - ESLyric v0.5.4.1008
 - Windows 10 19041.1
 - Foobar2000 Version 2.0 x64

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.4.1011
