### ISSUE TITLE
无法让eslyric自动读取tag中的歌词并且桌面显示? 每首都需要reload :(

### ISSUE THREAD

**Issue by rsyqvthv** [ESLyric/feedback#117]
**问题描述**
我的mp3绝大部分都有tag歌词, 
LYRICS, UNSYNCED LYRICS都有
但我的eslyric"桌面歌词显示板"中无法自动加载tag歌词, 
它只显示歌曲的名称.
在大多数情况下我需要右键显示板, 选择reload lyrics才可以加载并显示歌词.
foobar每切换一个歌曲, 我就需要reload一下歌词. 
不然它会继续显示上一首歌曲的歌词.

但个别情况下, reload也没有用.

我使用的基本都是默认设置, 
只是关闭了自动搜索歌词的选项.

不知道我还需要做什么调整? 才能让tag歌词自动显示在桌面歌词面板中?

**重现步骤**
重现该问题的步骤:
1. 我在foobar中启用eslyric, 并在view>eslyric中开启桌面歌词.
2. 播放歌曲
3. 桌面歌词面板显示当前播放歌曲的名称, 但不显示歌词.

**期望表现**
让tag歌词自动显示在桌面歌词面板中, 而不需要我每首都要reload.

**截图**
无

**软件环境:**
 - Windows版本 (Windows 10 1809)
 - foobar2000版本 v2.0 x64

**Comment by a1waysbeta** [comment]
上传一首文件看看

**Comment by ESLyric** [comment]
> 我使用的基本都是默认设置, 只是关闭了自动搜索歌词的选项.
> 
开启自动搜索。桌面歌词只会显示有时间戳的歌词，所以桌面歌词不会显示UNSYNCED LYRICS

**Comment by rsyqvthv** [comment]
> 上传一首文件看看

[1695049600.zip](https://github.com/ESLyric/feedback/files/12649610/1695049600.zip)

**Comment by rsyqvthv** [comment]
> > 我使用的基本都是默认设置, 只是关闭了自动搜索歌词的选项.
> 
> 开启自动搜索。桌面歌词只会显示有时间戳的歌词，所以桌面歌词不会显示UNSYNCED LYRICS

感谢你的提示, 
我的tags可能多在UNSYNCED LYRICS中, 因为这样兼容poweramp. 
有办法不区别是否是unsynced的tag, 
而改成读取两种tag, 哪个有歌词就取用哪个, 
用正则判断是否有timestamp, 
有的话就按时间戳播放歌词,
没有的话按照估计播放歌词?

另外, 如果是只读lyrics的歌词, 
而忽略unsynced的,
为什么我reload一下就可以显示歌词了呢?

感谢.

**Comment by ESLyric** [comment]
不想手动reload就开启自动搜索。桌面歌词不会显示非同步歌词。面板歌词都会显示。

**Comment by rsyqvthv** [comment]
> 不想手动reload就开启自动搜索。桌面歌词不会显示非同步歌词。面板歌词都会显示。

感谢, 我开启了自动搜索后, 确实一些歌曲的tag能自动桌面显示了. 但是表现有些谜:

- 不光有lyrics tag的可以显示, 部分unsynced lyrics也可以显示.
- 但也有突然停止自动显示的时候, 往往是这个歌曲有unsynced lyrics

总之, 目前可能由于我使用unsynced tags, 所以才会有这个问题. 

感谢大家的帮忙.

**Comment by ESLyric** [comment]
你如果在UNSYNCED LYRICS保存了有时间戳的歌词也是可以显示的。桌面歌词如果有显示，那肯定会有时间戳。

**Comment by rsyqvthv** [comment]
> 你如果在UNSYNCED LYRICS保存了有时间戳的歌词也是可以显示的。桌面歌词如果有显示，那肯定会有时间戳。

非常感谢, 了解了.
