### ISSUE TITLE
Please add option to preface retrieved lyrics with their source

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#118]
Now that the potential sources of retrieved lyrics is radically increased by TT's new package of searcher scripts, it would be very useful to have the option to display the source of the lyrics at the top of their display panel instead of only in the context menu's Lyric Information field.  This makes it easier to better place the search order of the scripts based on best result experience for the user.  Thanks for your consideration.

**Comment by ESLyric** [comment]
Can you demonstrate how it looks like or behavior? I don't understand.

**Comment by ESLyric** [comment]
I dont want this. Its useless and not a common feature.

**Comment by ESLyric** [comment]
Its possible to use custom layout, but currently only standard title format fields are supported.
