### ISSUE TITLE
Special chars/symbols in artist/track names crash ESLyric

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#119]
Hi ohyeah,

while I was testing some font fallback method in my theme, I have encountered when a artist/track name has special chars/symbols it will crash ESLyric after some playback time ( ~30 seconds ).

I can always reproduce the crash with these symbols as track name:
🗲 🗲 test ♥ ◕ ⚡🗲↯ϟ 🌈 🌧 📣 🌚

Here is the crash dump:
[Crash_dump.zip](https://github.com/ESLyric/feedback/files/12749527/Crash_dump.zip)

-Tom

**Comment by ESLyric** [comment]
Got. will be fixed next version.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.4.1015

**Comment by TT-ReBORN** [comment]
@ESLyric, thanks for the quick hotfix, it works fine now =)
