### ISSUE TITLE
自动搜索预处理时无法区分title与artist区域

### ISSUE THREAD

**Issue by byzod** [ESLyric/feedback#120]
**问题描述**
在自动搜索设置预处理时，试图删除artist中逗号后的并列演唱者时由于预处理总是对artist和title同时处理，因此会误伤title中包含逗号的部分

**重现步骤**
重现该问题的步骤:
1. 在filed processing中新增regex remove规则 （见Fig. 2）
2. 搜索title中包含逗号的歌曲时发现title逗号及之后内容被删除

**期望表现**
只删除artist中逗号及其之后的内容

**期望行为**
1. 可选对artist及title区域分别进行预处理
2. 自动加载搜索结果时可设置选择部分匹配艺术家的模糊结果

**截图**
> Fig. 1 搜索时由于包含了并列艺术家，不会自动加载搜索结果的歌词
> ![1](https://github.com/ESLyric/feedback/assets/848607/08600140-9140-4724-9e5c-c55155a549f7)

> Fig. 2 如果加上删除逗号及其之后内容的规则，则会影响title部分
> ![1a](https://github.com/ESLyric/feedback/assets/848607/1fb80aaa-fb20-475f-9777-197e5c973d98)

> Fig. 3会被影响的单曲示例1
> ![2](https://github.com/ESLyric/feedback/assets/848607/815a4446-ce7c-42d2-aa27-570cb34e479c)

> Fig. 4 会被影响的单曲示例2 （虽然这个没歌词
> ![3](https://github.com/ESLyric/feedback/assets/848607/55da4ac9-b31d-4303-9f76-695e1a5cf2df)

**软件环境:**
 - Windows版本：Windows 10 家庭中文版 19044.3086)
 - foobar2000版本： v2.0 (x86)
 - eslyric版本：v0.5.4.1015 (Beta)

**其他信息**
无

**Comment by ESLyric** [comment]
下个版本添加一下处理的字段

**Comment by ESLyric** [comment]
试下是否正常
https://github.com/ESLyric/release/releases/tag/0.5.4.1018

**Comment by byzod** [comment]
> 试下是否正常 https://github.com/ESLyric/release/releases/tag/0.5.4.1018

感谢dalao，非常完美 💖

送你闪亮小蛋糕
૮︵⭒‿⊹˚₊🍰‧˚✧‿⋆︵౨
