### ISSUE TITLE
使用musictag编辑歌词后在FB2K中出现长串时间轴

### ISSUE THREAD

**Issue by alettertocat** [ESLyric/feedback#121]
**问题内容**
使用musictag软件编辑歌曲歌词后，FB2K的歌词内容会出现无意义的“长串时间轴”。且在对比ESLyric组件后猜测是该组件版本的问题。下图是修改后出现的“长串时间轴”。
![image](https://github.com/ESLyric/feedback/assets/114268438/beafd64d-f28b-481a-aa1a-796e60274ef0)
下图为对比的ESLyric版本
![image](https://github.com/ESLyric/feedback/assets/114268438/2e92ef20-b582-4935-8661-d377dede034f)
下图为歌词内容对比以及在musictag中编辑后的歌词
![image](https://github.com/ESLyric/feedback/assets/114268438/58b3bbd5-7d4b-41dc-919b-691be2501cc1)
![image](https://github.com/ESLyric/feedback/assets/114268438/3bace2d7-a883-43d1-941d-2531d06ff338)

**软件环境**
 - Windows10 19045.3324
 - foobar2000 1.6.10
 - 使用的ESLyric组件版本为0.5.4.1015

**其他信息**
使用musictag修改了几首歌的歌词均出现上述问题
只出现在[00:00.00]这个时间点，如果在这个位置有内容，则在此句下生成“长串时间轴”。
只要比[00:00.00]晚，如[00:00.01]，“长串时间轴”就会出现在此句之上。
希望了解这是bug还是您本意如此，或者是因我对于组件的不了解导致设置方面出现了错误从而发生了以上情况。
如果是bug请您修复，如果是您本意我想知道为何，如果是设置问题请告诉我如何修复
谢谢🙂

**Comment by ESLyric** [comment]
麻烦提供一下编辑后保存的歌词文件。

**Comment by alettertocat** [comment]
> 麻烦提供一下编辑后保存的歌词文件。

[NEW.zip](https://github.com/ESLyric/feedback/files/12844315/NEW.zip)
FB2K是使用FB2K保存的lrc文件，musictag同理
old是修改前，new是修改后。
修改操作在musictag中完成

**Comment by alettertocat** [comment]
发现[00:00.00]的行数是非0时间总行数的一半。也就是[00:00.00]下面有20句，则生成10行[00:00.00]

**Comment by ESLyric** [comment]
不知道你什么操作顺序，我用fb2k打开"夢笑顔 - 茶太_musictag_new.lrc"，然后使用eslyric的编辑器查看是正常的。

**Comment by alettertocat** [comment]
> 不知道你什么操作顺序，我用fb2k打开"夢笑顔 - 茶太_musictag_new.lrc"，然后使用eslyric的编辑器查看是正常的。

在musictag上修改完歌词，保存退出，然后在foobar2K中重载歌词，就这样了

**Comment by alettertocat** [comment]
我是直接把歌词保存到标签里的，不单独保存一个lrc。

**Comment by ohyeah2008** [comment]
有没有可重现的步骤？有时间我看下。可以的话麻烦直接提供一些重现文件，包含音频文件，歌词等。

**Comment by ESLyric** [comment]
有没有可重现的步骤？有时间我看下。可以的话麻烦直接提供一些重现文件，包含音频文件，歌词等。

**Comment by alettertocat** [comment]
我看看能不能录个视频，把视频和文件都发给你。可以提供一个邮箱吗，这上面上传文件大小可能不是很够。我尽量控制的小一点

**Comment by a1waysbeta** [comment]
QQ群315848052

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.4.1018

**Comment by alettertocat** [comment]
❤❤❤谢谢
