### ISSUE TITLE
Lyrics not spaced the same in display panel as in Edit or Info in .5.4.1018

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#122]
0.5.4.1018  Foobar 1.6.16

Noticed in new version that lyrics displayed in the Foobar panel for radio stream metadata are missing the section space line, which IS present in the Lyrics Editor or in Lyric Information.

However, the empty line between sections IS displayed in the Foobar panel in older version 0.5.4.1008 exactly as in the Lyric Editor and Lyric Information.  Am I missing a setting?

**Display panel:**
![es1](https://github.com/ESLyric/feedback/assets/130251824/e506f4a2-9ab2-4ebd-9144-42719a9bdcfc)

**Lyric Editor window:**

![es2](https://github.com/ESLyric/feedback/assets/130251824/ce051a35-3258-4b02-b218-a7ace720543e)

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.4.1019
