### ISSUE TITLE
Lyric Sources

### ISSUE THREAD

**Issue by amigx** [ESLyric/feedback#123]
**Describe the bug**
ESLyric v0.5.4.1019 (Beta)
1. Sources of lyrics3 stopped working
2. Continues searching for "Local Files" lyrics even if it is not selected. Noticed only for radio streams.

**Desktop (please complete the following information):**
 - Windows Version Windows 10 19045.3570
 - Foobar2000 Version 2.1 32-bit prev. 2023-10-13

**Comment by ESLyric** [comment]
I will remove lyrics3 source support next version. Its too hard to maintain and easily causing crash.
