### ISSUE TITLE
Radio streams: at a song change, when new lyrics start, the lyrics jump up past the top of the panel

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#124]
version 0.5.4.1019, Foobar 1.6.16 -- Radio Stream Metadata lyrics

When a song has lyrics properly displayed in Foobar with its first line at the correct set point, when a new song begins in that stream, its new lyrics display beginning past the top of the panel.  This does not happen in version 0.5.4.1008 with identical panel preferences.

Song playing while lyrics display at normal start point acc. to panel preferences:

![es1a](https://github.com/ESLyric/feedback/assets/130251824/21c69031-8a7c-483d-9d5f-75b1b07f80cc)

When another song begins on the same stream, its lyrics start projected past the top of the panel:

![es1b](https://github.com/ESLyric/feedback/assets/130251824/9afb23e8-7fd1-49be-9cbb-607a1d624023)

**Comment by ESLyric** [comment]
I didn't see any changes related to this......

**Comment by ESLyric** [comment]
[foo_uie_eslyric.fb2k-component.zip](https://github.com/ESLyric/feedback/files/12930538/foo_uie_eslyric.fb2k-component.zip)

I rarely used radio stream(or unsynced lyric). You can try the this one and see if its fixed.

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.4.1022
