### ISSUE TITLE
歌词源和桌面歌词有几个问题

### ISSUE THREAD

**Issue by Whuihuan** [ESLyric/feedback#125]
**问题描述**
1.歌词源在从API返回的结果和显示在候选列表的数量不同。这个可能是插件自动计算匹配度得出的结果。
![image](https://github.com/ESLyric/feedback/assets/6679148/b28fa1c7-7e4e-4063-8e53-c3917af8c2d6)
![image](https://github.com/ESLyric/feedback/assets/6679148/6f7c16ab-8751-4d23-904d-d21818889d71)
这种同名歌并且存在于好几个专辑里的，虽然歌词可能相同，但可能会导致自动选择歌词的时候不会选择，建议将专辑名纳入匹配度的判断或者让所有歌词都显示出来
2.桌面歌词设置完字体大小后，等软件重启后，字体大小又变回去了，弄得每次桌面歌词字体都很大

**重现步骤**
重现该问题的步骤:
1. 
2. 

**期望表现**
简要清晰的表述你期望的表现

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (如1.6.8)

**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件及对应音频文件
如崩溃请打包crashreport(crash reports目录下)

**Comment by ESLyric** [comment]
1. 实际搜索时歌词内容为空或者相同会忽略掉，相同内容的歌词会选择最匹配的。这个规则暂时不会修改了
2. 如果不是用的默认配置，麻烦用默认界面配置测试下，有些界面可能会通过脚本外部控制设置一些选项。
