### ISSUE TITLE
请问保存歌词怎么才能与音频文件同名,我不会设置

### ISSUE THREAD

**Issue by romanticgrass** [ESLyric/feedback#126]
**问题描述**
简要清晰地描述问题

**重现步骤**
重现该问题的步骤:
1. 
2. 

**期望表现**
简要清晰的表述你期望的表现

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (如1.6.8)

**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件及对应音频文件
如崩溃请打包crashreport(crash reports目录下)

**Comment by a1waysbeta** [comment]
参数选项-工具-ESLyric-歌词选项-保存设置-保存文件，修改为 %filename%

**Comment by romanticgrass** [comment]
> 参数选项-工具-ESLyric-歌词选项-保存设置-保存文件，修改为 %filename%

超级感谢
