### ISSUE TITLE
希望桌面歌词能够显示双语歌词

### ISSUE THREAD

**Issue by sprinox** [ESLyric/feedback#129]
**新功能或功能增强**
希望桌面歌词能够显示双语歌词

**功能简介**
面板内可以正常爬取显示双语歌词，但桌面歌词没有显示
![image](https://github.com/ESLyric/feedback/assets/66425054/7ab30ec1-bb1b-44ae-b370-d566e0d01192)

**Comment by ESLyric** [comment]
桌面歌词窗口右键菜单启用显示参照行歌词，是独立的配置。
