### ISSUE TITLE
空白歌词行显示问题

### ISSUE THREAD

**Issue by Ptilopsis01** [ESLyric/feedback#13]
**问题描述**
部分歌词软件导出的歌词会有结束时间（即在结束时间增加一空白歌词行）
当这一句歌词与下一句紧密相连时（即结束时间与下一句歌词开始时间相同），下一句歌词会无法显示（能读取出来但是未激活）
较早版本并未遇到此问题

**截图**
<img width="689" alt="image" src="https://user-images.githubusercontent.com/93318731/180608298-087e9853-6da6-4c25-be64-a2dc629c7811.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/93318731/180608380-2ed18c9e-f9f5-44f7-850b-a7d8e8a6094a.png">

**软件环境:**
 - Windows11 10.0.22000
 - foobar2000 1.6.11（Asion汉化版）
 
*另：降版本更新会导致foobar2000崩溃

**Comment by ESLyric** [comment]
新版本对于相同时间戳的歌词都当作原歌词+翻译歌词，这个没办法处理。
崩溃问题请提供版本相关信息，如从哪个版本降至哪个版本。

**Comment by Ptilopsis01** [comment]
> 新版本对于相同时间戳的歌词都当作原歌词+翻译歌词，这个没办法处理。 崩溃问题请提供版本相关信息，如从哪个版本降至哪个版本。

昨天0.5.2.1117降到哪个版本都会崩溃，今天倒正常了。。
