### ISSUE TITLE
用正则表达式或其他方法使桌面歌词不显示纯音乐

### ISSUE THREAD

**Issue by Sha1rholder** [ESLyric/feedback#130]
在播放从qq音乐等来源下载的纯音乐时，EsLyrics可能会显示这句歌词  
![image](https://github.com/ESLyric/feedback/assets/96712109/de9d148d-982d-4b8e-ad76-b5df6aeae65e)

请问有没有可能通过正则表达式自动过滤这些，如果可能的话该如何实现？或者作者可以考虑添加一个功能让我这种小白得以一键过滤这些吗？

非常好插件，爱来自中国❤️

**Comment by a1waysbeta** [comment]
![image](https://github.com/ESLyric/feedback/assets/11453148/088be9b3-3b76-458b-a64e-5906501b1072)
你试试。
顺便分享一下桌面歌词配色

**Comment by Sha1rholder** [comment]
> ![image](https://user-images.githubusercontent.com/11453148/283281807-088be9b3-3b76-458b-a64e-5906501b1072.png) 你试试。 顺便分享一下桌面歌词配色

非常感谢，很有用！配色是我随便调的

![image](https://github.com/ESLyric/feedback/assets/96712109/00a687df-1d58-49ad-96c4-620896de7b4a)

![image](https://github.com/ESLyric/feedback/assets/96712109/581f7b31-faf7-475d-8f3f-30ddf1e70af0)  
![image](https://github.com/ESLyric/feedback/assets/96712109/985364b4-d3fa-4418-9970-c214bc29e033)

![image](https://github.com/ESLyric/feedback/assets/96712109/e2b5e7c6-e077-49b3-9424-f39e610bbb4a)  
![image](https://github.com/ESLyric/feedback/assets/96712109/7a805301-4d1c-4dde-92ee-211e80dc549b)
