### ISSUE TITLE
歌词全屏显示错误

### ISSUE THREAD

**Issue by regenwind** [ESLyric/feedback#131]
**问题描述**
使用双显示器时，在副屏双击歌词界面全屏显示歌词时，不是全屏显示，看大小应该是显示了主屏的大小

**重现步骤**
1. 使用双显示器，且主屏分辨率小于副屏（如果分辨率相等应该看不到Bug，我的副屏在主屏右侧）
2. 把foobar2000窗体拖到副屏，双击歌词界面，此时会全屏显示歌词和封面，但是是按主屏的分辨率全屏的（在屏幕左上角，其他多余位置是白色）。我试了好几次，这个Bug必出

**期望表现**
副屏显示歌词全屏时，按照副屏的分辨率全屏

**软件环境:**
 - Windows 10 19045.3693
 - foobar2000 V2.0 x64

**Comment by regenwind** [comment]
补充插件版本：ESLyric v0.5.4.1022 (Beta)

**Comment by ESLyric** [comment]
双屏支持不好，暂时没计划没精力完善了。
