### ISSUE TITLE
歌词面板-面板参数选项设置没有持久化

### ISSUE THREAD

**Issue by liangyi9812** [ESLyric/feedback#132]
**问题描述**
非常 感谢您制作的如此易用和功能强大的歌词面板，在使用中我碰到了一些问题
面板参数选项设置没有持久化，
设置完参数后（例如字体，颜色等），切歌后没有带到其他歌上并且切回原歌曲效果也会重置

**期望表现**
持久化面板参数选项，并且应用到其他歌上

**软件环境:**
 - Windows版本 (Windows 10 专业版 22H2 19045.2604)
 - foobar2000版本 (2.0)

**Comment by a1waysbeta** [comment]
录制一个视频
