### ISSUE TITLE
Add context menu command to continue auto-search past current results

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#133]
ESLyric  .5.4.1022, Foobar 2.1 64-bit.

When on auto-search, ESL will sometimes stop at a source that presents a message like:

![es](https://github.com/ESLyric/feedback/assets/130251824/edbe502d-7ff3-43dd-a211-461c805f37a5)
In the case above, it was SongMeanings for lyrics for the song in the shot below;  afterwards, performing a manual search shows that both SongLyrics and NetEase DO have the lyrics but happened to be placed below SongMeanings in my search order:

![es1](https://github.com/ESLyric/feedback/assets/130251824/b9ee8624-ee20-409b-90aa-afbc9718eafe)

Can you please add a choice in the right-click context menu to "Continue auto search" that can be used when this happens?  This would also be useful when someone just wanted to compare the lyrics from different sources.  Lyric Show Panel 3 uses "Next lyrics" for this, while MusicBee uses "Search Next Provider."  Thanks for considering.

**Comment by ESLyric** [comment]
You can use the 'Lyric Processor' to remove these lyrics.

**Comment by ESLyric** [comment]
ESLyric will continue search if you remove these unwanted lyrics. Or uncheck 
![image](https://github.com/ESLyric/feedback/assets/102273569/ec0e75e0-886c-41ca-a802-d39df6d0a7e9)

**Comment by a1waysbeta** [comment]
![image](https://github.com/ESLyric/feedback/assets/11453148/2a9c2ad9-a759-4861-84ed-9e888f709b2d)
you can try it.
