### ISSUE TITLE
希望可以对日语歌词添加汉字上标假名功能 (振り仮名/furigana)

### ISSUE THREAD

**Issue by sora-jpht** [ESLyric/feedback#135]
**新功能或功能增强**
希望可以对日语歌词添加上标假名功能 (振り仮名/furigana)

**功能简介**
日语ktv唱歌思维会偏向于看上标假名方便发音
![image](https://github.com/ESLyric/feedback/assets/120781399/f668bcfb-0cde-4897-861e-01ef88acae1d)
图片上方为qq音乐效果，汉字上标假名对应了该字的假名读音，想要拥有类似的功能

**是否有参考软件实现**
qq音乐的歌词有实现该功能（如功能简介中图）假名的标注并不存在于本地文件中，我自己尝试加载本地歌词文件后发现软件会自动生成上标，并不会更改本地文件，虽然生成有时会不准确（日语中汉字会有不同的读法）但是日常唱歌简单参照足够
相关实现方法个人有在进行ass字幕制作中接触，其相关制作方式参见（主要可以参考对应假名生成方法）：
https://vmoe.info/6925

**其他信息**
上标假名生成网站（供参考）
https://www.jpmarumaru.com/tw/toolKanjiFurigana.asp

**Comment by ESLyric** [comment]
抱歉，不会实现类型的功能

**Comment by sora-jpht** [comment]
> 抱歉，不会实现类型的功能

好的，没关系，感谢回复
