### ISSUE TITLE
歌词已经设置置顶 但还是会被程序挡住

### ISSUE THREAD

**Issue by riversideview** [ESLyric/feedback#136]
**问题描述**
简要清晰地描述问题

**重现步骤**
重现该问题的步骤:
1. 我的歌词已经设置置顶了 还是会被我的游戏（DNF）给盖住 插件的版本是最新版
**期望表现**
简要清晰的表述你期望的表现

**截图**
![QQ图片20240106140336](https://github.com/ESLyric/feedback/assets/9318671/fb7a013a-f142-4c50-b426-59a4641ed14c)

**软件环境:**
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2021/‎5/‎7
操作系统内部版本	19045.3803
体验	Windows Feature Experience Pack 1000.19053.1000.0

 - foobar2000版本 (如1.6.8)
![QQ截图20240106140600](https://github.com/ESLyric/feedback/assets/9318671/25998815-ea79-4269-be98-cb85ab3c0e1e)

**其他信息**
我试过用网易云的歌词显示就不会问题

**Comment by a1waysbeta** [comment]
无解，设置一个快捷键，挡住的时候临时取消置顶再置顶一次
