### ISSUE TITLE
保存歌词至配置文件目录 保存位置错误

### ISSUE THREAD

**Issue by Cartagra** [ESLyric/feedback#137]
**问题描述**
版本：ESLyric v0.5.4.1028 (Beta)
歌词没有保存到修改后的位置，依然保存在默认目录

**重现步骤**
1. 在ESLyric 设置 “保存设置”里，修改“保存位置”为绝对路径
2. 在歌曲播放中，右键歌词面板》保存歌词至》配置文件目录

**期望表现**
歌词能正确保存到自定义的配置目录

**软件环境:**
 - foobar2000 2.1.1汉化版32位

**Comment by a1waysbeta** [comment]
使用右键菜单【保存歌词】，而不是【保存歌词至】

**Comment by Cartagra** [comment]
> 使用右键菜单【保存歌词】，而不是【保存歌词至】

我默认设置【保存歌词】是【保存到标签】
现在我想将歌词提取出来 保存到我配置的文件夹
使用这个【保存歌词至】功能，保存到的不是我在设置里配置的文件夹
这个不算是bug吗？

**Comment by ESLyric** [comment]
配置文件目录指的是fb2k配置文件所在的目录。可以选择保存到自定义目录。
