### ISSUE TITLE
歌词面板背景无法显示webp图片的问题

### ISSUE THREAD

**Issue by 820607454** [ESLyric/feedback#138]
**问题描述**
歌词面板背景无法显示webp图片

**重现步骤**
播放内封webp封面的flac，或者直接添加来源为webp的图片，歌词背景均无法显示

**期望表现**
希望歌词背景能够支持webp图片（有些歌扫图太大，想要无损放进flac只能用webp压缩才能小于16MB）

**截图**
![111](https://github.com/ESLyric/feedback/assets/130959292/41fbf7b7-bfdb-4d9c-a0da-ca26e2b00537)
![222](https://github.com/ESLyric/feedback/assets/130959292/0827f950-a611-4e29-b38c-d07df94dbd87)

**软件环境:**
 - Windows 11 22631.3007
 - foobar2000版本 1.6.11

谢谢大佬

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1010
