### ISSUE TITLE
pref.scripts.expose default to 1

### ISSUE THREAD

**Issue by Ottodix** [ESLyric/feedback#14]
Hi,

Would it be possible to set pref.scripts.expose to 1 by default? This is something required for the [Eole theme i developed](https://github.com/Ottodix/Eole-foobar-theme)

I don't know the security issues that it could raise, but without this setting set to 1, your version of ESLyric won't work with this theme. And as this setting isn't saved inside ColumnUI configuration files, users would need to enabled it themself when they install Eole. It will raise support issues on my side, that's why I'm asking there about a default value to 1, in order to include your ESLyric in this Eole theme.

An alternative would be to save this advanced setting into ColumnUI configuration files? I don't have any knowledge there, I just know that for most ColumnUI components, their settings are saved into the configuration file created during an export.

Thanks!
Have a good day

**Comment by ESLyric** [comment]
I'll see how to handle it

**Comment by Ottodix** [comment]
great, thanks

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1120

two ways:
1. create a empty file named `enable_script_control` in the same folder
2. create a `initial_enable_script_control` file, and the file will be deleted after fb2k startup.

**Comment by Ottodix** [comment]
Thanks! It work flawlessly now and we've got your component on Eole, it works much better than the old one
