### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xxbhpan** [ESLyric/feedback#140]
**问题描述**
QQ音乐搜索的歌词不显示详细信息

**重现步骤**
重现该问题的步骤:
1. 完全卸载foobar2000
2. 重新安装foobar2000
3. 安装foo_uie_eslyric.fb2k-component
4. 选择知名歌曲进行搜索，复现bug
5. 删除foobar2000程序主目录下的eslyric-data的相关文件
6. 重新搜索bug仍然能够复现
（该bug可能为个例）

**期望表现**
期待能够显示歌词详细信息

**截图**
![QQ图片20240209214214](https://github.com/ESLyric/feedback/assets/159548248/6d7bcbf9-589c-4349-b893-cb27947fce4e)

**软件环境:**
 - Windows版本 (Windows 10 专业版 22H2 19045.3996)
 - foobar2000版本 (如foobar2000 v2.1.2 x64 by Asion)

**其他信息**
无

**Comment by a1waysbeta** [comment]
参数选项，设置，里面点击 获取更多，重新更新一下脚本，尤其是解析脚本试试，64和32的不通用，有可能误复制32平台的脚本了
