### ISSUE TITLE
Implementing proper left and center-left line alignment

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#141]
**Is your feature request related to a problem? Please describe.**
Yes, it is. When using left/center-left alignment, if a line in a lyric file is long and split to 2 lines, the second line is not right under the first one. Difficult to explain, example in the first image. To me and most likely many other people this looks pretty bad, could also be taken as a bug.

**Describe the solution you'd like**
The 2nd line should be directly under the first one, like in right/center-right aligment. This looks clean and is how every lyrics panel should do it. Either a toggle between "poking out" and aligned would be nice or just making the properly aligned one the default. Example of proper alignment (center-right) in the second image.

**Describe alternatives you've considered**
I tried switching to center-right but it looks wrong. Reading on the right side of the display isn't for me.

**Additional context**
Left/center-left are wrongly aligned on both the fullscreen and non-fullscreen panels

I hope you understood what i meant 👍 

IMAGE 1 
![image_2024-02-22_142038089](https://github.com/ESLyric/feedback/assets/106167103/049163b3-6627-4128-abf3-1f2e0f355595)

IMAGE 2
![image_2024-02-22_141947062](https://github.com/ESLyric/feedback/assets/106167103/987b2690-f112-466e-89a1-f60944a05904)

**Comment by ESLyric** [comment]
Whitespaces in the beginning of lines?  if so, you can add a lyric processor rule to remove them.

**Comment by GZ2E01** [comment]
> Whitespaces in the beginning of lines? if so, you can add a lyric processor rule to remove them.

Yep, that was the issue. I feel so stupid 😭 Thank you so much!
