### ISSUE TITLE
Line opacity feature

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#142]
**Is your feature request related to a problem? Please describe.**
No. Translucent lyric colors would be nice, currently there's only 100% opacity ones.

**Describe the solution you'd like**
An opacity slider for the colors if possible would be ideal 

**Describe alternatives you've considered**
Currently I use light gray for normal lyrics and white for the highlighted line. Translucent would look waaaaay better

**Additional context**
Something like Apple Music's lyrics is a perfect example![Screenshot_20240222_153309_Apple Music.jpg](https://github.com/ESLyric/feedback/assets/106167103/5105dcc9-132b-459f-8494-d437d119e99f)

**Comment by ESLyric** [comment]
May be added when I finish refactoring with D2D

**Comment by ESLyric** [comment]
try the new alpha version.
https://github.com/ESLyric/release/releases/tag/1.0.0.1010
