### ISSUE TITLE
Eslyric能否实现歌词的横行变坚行?

### ISSUE THREAD

**Issue by Meisfuture** [ESLyric/feedback#143]
很想作者在Eslyrics添加一个歌词显示功能，就是把横行变竖行，如图所示：

![AAA](https://github.com/ESLyric/feedback/assets/133914863/982839ee-e4ac-4afe-a116-94d6136aec05)

**Comment by ESLyric** [comment]
算了吧，很個性化的顯示方式，後續維護也很麻煩。
