### ISSUE TITLE
歌词置顶问题

### ISSUE THREAD

**Issue by osr5** [ESLyric/feedback#146]
**问题描述**
谷歌浏览器放大缩小/或程序切换后置顶无效，打游戏的时候也无法置顶，比如：War3
 
系统：Windows LTSC

**Comment by a1waysbeta** [comment]
设置一个快捷键，临时取消置顶再置顶一次

**Comment by osr5** [comment]
666

**Comment by a1waysbeta** [comment]
勾选全局快捷键试试，不行的话，置顶问题无解，有些游戏或者软件置顶代码不遵守规则
