### ISSUE TITLE
無法搜尋到網易雲及中日歌詞

### ISSUE THREAD

**Issue by uyder120** [ESLyric/feedback#15]
您好 大約在一個禮拜前我在使用舊版時開始無法搜尋到來自網易雲的歌詞，在搜索時只要開著網易雲的選項總是要跑非常久，跑完也沒有出現任何的歌詞，後來我換到這個新版也依然如此

還有就是換到新版之後無法在找到像圖中那種中日都有包括在一個歌詞檔裡的歌詞了
[https://imgur.com/a/DHQn2kl](url)
我沒辦法確定是我自身的問題還是別的，還煩請您看看了

**Comment by zhtw2013** [comment]
![image](https://user-images.githubusercontent.com/9501406/182010257-52a7aef9-e421-4433-ac42-96adc82fcd13.png)
測試找得到

**Comment by uyder120** [comment]
那可能是我自己的問題，我再試試看 感謝

**Comment by uyder120** [comment]
我試了整個刪除乾淨然後重裝過乾淨的版本加上這個插件，依然是同樣的的問題
我還真想不到問題出在哪

**Comment by zhtw2013** [comment]
你有勾「顯示全部歌詞」嗎？

**Comment by uyder120** [comment]
有的

**Comment by ESLyric** [comment]
收到，有时间确认下

**Comment by uyder120** [comment]
謝謝 再麻煩了

**Comment by ESLyric** [comment]
> 謝謝 再麻煩了

能否提供搜索的关键词，我用几首流行歌曲搜索正常。

**Comment by uyder120** [comment]
Brave Shine
アカシア
海色

還有其他有名的也都是一樣的問題，無法找到網易雲以及中日歌詞

**Comment by ESLyric** [comment]
> Brave Shine アカシア 海色
> 
> 還有其他有名的也都是一樣的問題，無法找到網易雲以及中日歌詞

测试都可以搜到结果，双语歌词这个看缘分。

**Comment by uyder120** [comment]
看來是我自己的問題，我再等幾天看會不會自己好
謝謝 打擾了

**Comment by zhtw2013** [comment]
> 看來是我自己的問題，我再等幾天看會不會自己好 謝謝 打擾了

可以檢查是否有用過網路管理工具禁止了 foobar2000 聯網

**Comment by ESLyric** [comment]
可以自己在脚本输出日志看看
https://github.com/ESLyric/scripts/blob/234be159b02dd508c830411914f57b6c494df970/searcher/netease.js#L54
比如
`console.log("status: " + res.statusCode + ' ' + body)`

**Comment by uyder120** [comment]
終於找到問題點了，原來是我的電腦莫名其妙把網易雲擋起來了
謝謝兩位花那麼多時間幫我 謝謝!
