### ISSUE TITLE
卡拉OK模式中krc格式未判断为增强型歌词

### ISSUE THREAD

**Issue by gtianw** [ESLyric/feedback#151]
**问题描述**
卡拉OK模式中krc格式未判断为增强型歌词

**重现步骤**
重现该问题的步骤:
1. 歌词设置->卡拉OK模式，选中“当显示增强型歌词时开启”
2. 播放krc歌词对应的音乐，可以发现未按照卡拉OK模式显示歌词

**期望表现**
krc歌词可以自动出逐字效果
如果将设置改为“总是开启”，那么普通的lrc歌词会虚拟出逐字效果，这不是我想要的效果。

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (2.1.4)
 - ESLyric版本 (0.5.4.1028)

**歌词附件:**
[1.zip](https://github.com/ESLyric/feedback/files/15249945/1.zip)

**Comment by a1waysbeta** [comment]
贴一下歌词看看

**Comment by gtianw** [comment]
我这边是所有krc文件都不能判断为增强型歌词，并非特定krc文件
歌词文件已上传

**Comment by ESLyric** [comment]
你上传的KRC测试没问题。右键编辑歌词也能看到歌词行有多时间戳。
检查一下你用的KRC解析器是不是自带的。其他的想不到有什么原因。

**Comment by gtianw** [comment]
怎么看KRC解析器是不是自带的，我用的asion汉化版，不确定解析器有没有被修改

**Comment by gtianw** [comment]
如果解析器有问题的话，设置改为“总是开启”按理应该不能准确出逐字效果吧，但实际是可以的

**Comment by ESLyric** [comment]
反馈不到点上，都不知道怎么回复了。自己对比下吧。我也没啥好办法。

**Comment by gtianw** [comment]
![20240509225809](https://github.com/ESLyric/feedback/assets/91190888/94b706a3-5696-46ca-892a-cd213ab5351c)
我感觉大佬是不是没理解我的问题，截图中选中“总是开启”可以正常出逐字效果，选中“当显示增强型歌词时开启”就不行。

**Comment by ESLyric** [comment]
测试没问题。要么把你用的打包一下，要么自己全新安装一个看看。

**Comment by gtianw** [comment]
![20240510191313](https://github.com/ESLyric/feedback/assets/91190888/f90ff395-0022-4b2e-a9e2-b95f05056af8)
破案了，汉化版默认选中了“转换为标准格式”。。。
