### ISSUE TITLE
MiniLyrics或AZLyrics歌词源无效 (大概一个月前就不行)

### ISSUE THREAD

**Issue by a442509097** [ESLyric/feedback#152]
我有点忘了是MiniLyrics还是AZLyrics, 不过应该是MiniLyrics, 我打开MiniLyrics官网也是打不开的.

由于我把桌面歌词(非卡拉ok模式)设置成80号这样的大字体, 然后听一些英文歌, 如果遇到一句比较长的歌词(如Dire Straits - Sultans Of Swing这首歌), 就会后半句歌词显示很慢的问题(调偏移也不好使), 其它的歌词源基本不会分段, 唯有MiniLyrics会把较长的歌词划分成两段, 所以一直都是优先选择MiniLyrics的歌词. 

所以想问一下, 如果MiniLyrics不行, 有相关的设置, 设置到了指定数单词自动划分成两句的功能吗?

**Comment by ESLyric** [comment]
没有
