### ISSUE TITLE
桌面歌词使用第三方字体不显示。

### ISSUE THREAD

**Issue by nali558** [ESLyric/feedback#153]
只有部分字体有用，另有不少字体，不管在设置的预览还是桌面歌词，都直接不显示歌词了。
![QQ截图20240518220808](https://github.com/ESLyric/feedback/assets/109232659/2ff242ac-647e-4938-b72c-5f555e885bfc)

**Comment by ESLyric** [comment]
暂时无解，只能换个字体。

**Comment by Rakau** [comment]
不是第三方字体不支持，而是不支持多重字体和可变字体

**Comment by kelstna** [comment]
我重启foobar2000之后有一部分字体能用了

**Comment by ESLyric** [comment]
用新版 https://github.com/ESLyric/release/releases/tag/1.0.0.1010

**Comment by nali558** [comment]
只能说如用。虽然能显示了，但描边不再将字作为整体，而是每一个笔画作为个体进行描边。
