### ISSUE TITLE
Deskband 与 foobar2000最小化为图标

### ISSUE THREAD

**Issue by RitChan** [ESLyric/feedback#154]
**问题描述**
测出一个bug~Deskband功能与最小化为图标的兼容性问题

**重现步骤**
重现该问题的步骤:
1. File -> preferences -> Display -> Default User Interface -> Background and Notifications -> 选择Minimize hides, close exits
2. 打开Deskband功能
3. 最小化窗口（这时会卡几秒，并且要左右拖一下歌词任务栏才能正确显示歌词）

**期望表现**
窗口消失，foobar2000出现在右下角，歌词正确显示，不卡顿

**软件环境:**
 - Windows版本 (如Windows 10 19045.4412)
 - foobar2000版本 (如2.1.5)
 - ESLyric版本 (如0.5.4.1028)

**Comment by ESLyric** [comment]
> 作者仅提供基本说明，不对后续任务栏歌词问题或功能提供任何支持，即如果无法启用或存在其他相关问题或建议，请不要反馈至feedback仓库。
