### ISSUE TITLE
[Feature Request] Apply offset to Timestamps

### ISSUE THREAD

**Issue by ngs428** [ESLyric/feedback#155]
**Apply offset tag to Timestamps**
Some of my players don't support and offset value, so having the ability to apply the offset value to the individual timestamps would be very helpful.  This feature is present in OpenLyrics and works very well.

In ESLyrics you can hit "ctrl" and "left click" to drag and set the offset, seems to work well, but then following that up with applying the offset value to each timestamp and then removing the offset value at the top of the lyrics would be great.  

OpenLyrics is shown below.  You listen to the song and when it hits the line you need, you press the "Sync Line using offset tag" button, that is similar to your CTRL left click, then you would press the "Apply offset to timestamps" button to add the offset to the timestamps and remove the offset value.  

![OpenLyrics](https://github.com/ESLyric/feedback/assets/13911615/22dc3f6e-5324-44b2-9160-b54f93f7a39b)

**Comment by ESLyric** [comment]
try the alpha version. access via the editor's menubar
https://github.com/ESLyric/release/releases/tag/1.0.0.1010

**Comment by ngs428** [comment]
Thank you for the update!  Applying the offset works great!  

On a similar note, in ESLyrics you can hit "ctrl" and "left click" to drag and set the offset,  Where is this offset saved to?  I hit "ctrl" and "left click" to drag and set the offset, then right click, adjust offset, the offset is there, then I hit OK.  The offset value is not saved to the top of the .lrc file and also the timestamps are not changed.  Ideally the offset would be applied to the top of the file, then this new command could be used to apply to the timestamps.  Or the timestamps could be adjusted automatically per what that offset is.  

Is there another way to do this or am I missing something?

**Comment by ESLyric** [comment]
‘offset’ was saved in memory default and you should use 'Save' in the context menu to save to original location(file or meta) or save to configured location if is online lyric.

**Comment by ngs428** [comment]
I tried the “Save” originally and it did not save to the .lrc file.  Can you please test to make sure that is working properly?

**Comment by ESLyric** [comment]
Seems to be broken. wait for fix

**Comment by ngs428** [comment]
Works great in [https://github.com/ESLyric/release/releases/tag/1.0.0.1013](url)

Thanks!
