### ISSUE TITLE
【功能增强】日文歌词汉字 标注平假名

### ISSUE THREAD

**Issue by Itukii** [ESLyric/feedback#158]
**新功能或功能增强**
功能建议

**功能简介**
在汉字上标注 平假名 桌面歌词以及窗口歌词
![image](https://github.com/ESLyric/feedback/assets/68493667/fc00d2d5-9eab-46c0-be71-9fde557aa432)
![image](https://github.com/ESLyric/feedback/assets/68493667/64d3767b-06d4-49b3-aae6-11ef88521e26)

**是否有参考软件实现**
是否有其他已有的软件实现参考
qq音乐

**Comment by a1waysbeta** [comment]
不会考虑此功能。https://github.com/ESLyric/feedback/issues/135
