### ISSUE TITLE
找到歌词后，下一次再播放时还是重新搜索定位歌词，能否下载完歌词后，下次直接调用上次保存的歌词

### ISSUE THREAD

**Issue by bluessb** [ESLyric/feedback#159]
**问题描述**
找到歌词后，下一次再播放时还是重新搜索定位歌词，能否下载完歌词后，下次直接调用上次保存的歌词

**Comment by ESLyric** [comment]
手动关联保存的歌词

**Comment by bluessb** [comment]
如何具体操作呢，先搜索歌词，然后在歌词栏选择“保存歌词”，再选“歌词关联”，“管理关联”，选中歌词文件，再确定么？不行呢

**Comment by bluessb** [comment]
或者先搜索歌词，选择保存歌词，再选关联该歌词，下次播放还是不调用歌词，但现实已关联歌词了

**Comment by bluessb** [comment]
或者是不是因为我安装的一个已经集成歌词的版本的foobar2000的缘故，需要重新安装呢

**Comment by bluessb** [comment]
对了，我这个好像关联正常的歌，比如“标题”是歌名，“艺术家”是演唱者的歌时，好像很快能匹配上，给别的匹配不上。但我的歌很多都是这个格式的，比如，歌名会显示“歌名-演唱者”，“艺术家”一栏会显示比如“超级星论坛”这样的字样，凡是出现这类的歌便每次都要搜索，关联了好像也没用

**Comment by bluessb** [comment]
仿佛之前版本的eslyric是可以正常关联的，比如我下了一个1.5.1版的foobar2000的歌词是没问题的，但下了个2.1.5版本的foobar2000就存在上述问题，而且一般是在我描述的标题和艺术家与原版不符的状况下，就算关联了歌词也不会调用，而搜索之后搜索栏里列表中有本地歌词，并显示已关联，但就是无法调用

**Comment by ESLyric** [comment]
说这么多还是没明白在说什么，打包一下fb2k及歌词，并说明一下如何重现吧。

**Comment by bluessb** [comment]
在 2024-06-09 16:49:03，"ESLyric" ***@***.***> 写道：

说这么多还是没明白在说什么，打包一下fb2k及歌词，并说明一下如何重现吧。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
打包.rar (26.5M, 2024年6月24日 17:25 到期)
下载

**Comment by bluessb** [comment]
以已邮件形式发送了，谢谢

**Comment by ESLyric** [comment]
我不知道你传到哪了。github可以直接传文件。

**Comment by bluessb** [comment]
用email附件传的哦，我不会在这里传，哈哈

**Comment by bluessb** [comment]
[Uploading 打包.zip…]()

**Comment by bluessb** [comment]
rar文件是，因为附件只能传zip，所以改名为zip了，可以恢复成rar解压

**Comment by bluessb** [comment]
我再分享一个百度网盘的下载地址吧：链接：https://pan.baidu.com/s/19PwqJfGsRBGbpjNqdbcZsw?pwd=jvuj 
提取码：jvuj 
--来自百度网盘超级会员V10的分享

**Comment by ESLyric** [comment]
用你打包的照你的说明操作没出现你说的问题，保存后就能正常加载。
高级选项里有个debug开关，双击设置为1，重启fb再操作一次。贴一下控制台的所有输出看一下。(视图->控制台)
![image](https://github.com/ESLyric/feedback/assets/102273569/a53ea53f-4830-4bf2-8467-6cfbbf1112bc)

**Comment by bluessb** [comment]
> 您可以将歌词保存到音乐文件中，也可以保存为单独的文件；右键单击找到的歌词，选择 “保存歌词到->标签”，或选择三个文件夹之一。
> 
> 要使歌词显示出来而无需再次搜索，请进入 “偏好设置/歌词来源”，将 “标签 ”和/或 “本地文件 ”移到列表顶部，然后点击 “配置 ”链接进行设置。

找不到，偏好设置/歌词来源，只找到了路径为：文件/参数选项/ ESlyric/歌词选项/歌词来源。而这时右边显示一个列表，列表内容为：“关联歌词/配置”“音频标签/配置”“本地文件/配置”“酷狗音乐”“网易云音乐”“QQ音乐”和“QQ音乐ex”

**Comment by bluessb** [comment]
非常感谢
