### ISSUE TITLE
问题反馈：已安装字体较多时无法更改字体

### ISSUE THREAD

**Issue by flisrkr** [ESLyric/feedback#163]
**问题描述**
如题，装了个汉化组的字体整合包后电脑里有八千多个字体，结果插件读不出字体列表，无法更改桌面歌词字体了

**重现步骤**
1. ESLyric-桌面歌词-字体
2. 如截图所示

**期望表现**
希望能解决该问题

**截图**
下图为插件提示：
![foobar2000_MU7H2L6Hms](https://github.com/ESLyric/feedback/assets/82390194/dbcfd755-01c6-49e1-b6d0-654215c74119)
控制面板里的设置：
![explorer_ERssPbdA9v](https://github.com/ESLyric/feedback/assets/82390194/0f019d0b-ca4c-491d-8c13-6e40cfc2fc3b)
两个复选框都分别点选尝试过了，结果上来说没有任何区别

**软件环境**
 - Windows 11 24H2 26100.863
 - foobar2000 v2.1.2 x86
 - ESLyric v0.5.4.1028 (Beta)

**Comment by a1waysbeta** [comment]
你自己的问题，安装成隐藏的了。百度一下字体文件夹，去里面看看。

**Comment by ESLyric** [comment]
什么都没有我怎么解决

**Comment by a1waysbeta** [comment]
Fonts 文件夹字体右键，显示。或者属性，取消勾选隐藏。
![微信截图_20240623162050](https://github.com/ESLyric/feedback/assets/11453148/f267c117-c1cb-445a-9d1b-ba0ac4f231ce)

**Comment by a1waysbeta** [comment]
再换一些更强大的资源管理器

**Comment by ESLyric** [comment]
哎，你提供这么多东西，不如提供一下你的什么字体包。
