### ISSUE TITLE
Extremely laggy dyn blur feature in newest alpha release.

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#164]
**Describe the bug**
I'm sure this is already a known issue but the background with dyn blur as the image refreshes every 1 second and that is just slow. 
**Expected behavior**
At least 30 frames per second would be good. I don't know if that's possible but it would look really nice.

**Screenshots**
https://pixeldrain.com/u/r1hnqkMn

**Desktop (please complete the following information):**
 - Windows Version [Windows 11 Pro 22631.3737]
 - Foobar2000 Version [v2.1.5]

**Additional context**
60 frames would be even better 😺

**Comment by GZ2E01** [comment]
> Normally it should be 60fps, I have no clue why it‘s so laggy in your env.

Huh, that's weird. From what I know my machine isn't like weak in any way. I have a GTX 1660 Super, i5 10-500 and 32 GB 3600 mHz RAM. It's this way on both my 2.1.5 and my 1.6.11 versions of Foobar, I'll try portable now

**Comment by ESLyric** [comment]
Cannot fix without reproduce ;(

**Comment by GZ2E01** [comment]
> Cannot fix without reproduce ;(

I started foobar today normally without changing any settings and it's 60 fps now. I have no clue what fixed it but wow this looks so good. Keeping this open in case the issue comes back

**Comment by GZ2E01** [comment]
@ESLyric can you suggest anything I could try to get the 60 FPS back. I have zero processes in the background so it's not actual hardware restrictions

**Comment by GZ2E01** [comment]
> @ESLyric can you suggest anything I could try to get the 60 FPS back. I have zero processes in the background so it's not actual hardware restrictions

man i updated windows to a slightly newer version and its perfect i dont understand this, keeping this open in case it comes back AGAIN

**Comment by oozan22** [comment]
doesnt it detiriorate over time? it seems like 60+ fps right after starting windows , then after a while it becomes laggy   (20-30 fps)(as the problem is consistent across multiple foobars at once may it has to do with the player for dyn blur?)

**Comment by GZ2E01** [comment]
> doesnt it detiriorate over time? it seems like 60+ fps right after starting windows , then after a while it becomes laggy   (20-30 fps)(as the problem is consistent across multiple foobars at once may it has to do with the player for dyn blur?)

Yes it does, I actually found sort of a fix. Whenever this happens updating windows resets the cycle

**Comment by oozan22** [comment]
wow such a fast response :)
Thx
