### ISSUE TITLE
No lyrics display with new alpha (foobar2000 on Linux through WINE)

### ISSUE THREAD

**Issue by Lovecraft-github** [ESLyric/feedback#165]
I'm using foobar2000 v2.2 preview 2024-06-24 on Linux (KDE-Arch) through WINE 9.11

With the new Alpha version, there are no lyrics displayed in the panel, only a black panel.

The console said

[ESLyric]eslyric_window::CompositeRenderTargets failed,  [0x88990028]
[ESLyric]eslyric_window::CreateEffects failed, �1큠ो�1�1�1�1�1 [0x88990028]

And the configuration window have the text selection disabled

![Screenshot_20240628_105702](https://github.com/ESLyric/feedback/assets/127577072/7b8dbe18-6c23-43ad-bc58-f4628e81d590)

**Comment by ESLyric** [comment]
Use old version or other lyric components instead.
