### ISSUE TITLE
1.0.0.1006:  Un-checking "autoscroll" in context menu not working

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#166]
Foobar v.2.2 64-bit, Windows 11 23H2
ESLyric 1.0.0.1006 Alpha

When any lyrics are displayed in Foobar panel, they autoscroll, and un-checking "Autoscroll" in the context menu has no effect.  This worked correctly in 0.5.4.1028.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1007
