### ISSUE TITLE
[1.0.0.1007 Alpha] Component cannot be installed

### ISSUE THREAD

**Issue by MG240** [ESLyric/feedback#167]
I get this error upon installing the component:
"Could not load component "foo_uie_eslyric.fb2k-component": This component was built for a different processor architecture."

This doesn't happen with 1.0.0.1006 Alpha.

Windows 11 64-bit
foobar2000 v2.2 preview 2024-06-30 64-bit

**Comment by ESLyric** [comment]
Updated. Plz re-download it.
