### ISSUE TITLE
Alpha .1007: "unsync lyric when play internet radio" not working with Musixmatch

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#168]
While 1.0.0.1007 fixed the issue of the "autoscroll" context option not working with any lyrics, I noticed that when radio streaming lyrics are grabbed from a database where the script is designed to return ONLY synced lyrics, like "Musixmatch (Synced)", the setting "unsync lyric when play internet radio" does not work.  The "autoscroll" option does not appear in these cases.

There are so few sources (2 or 3?) that are marked as "synced" that this is practically a non-issue, but since Musixmatch is a major lyrics provider I thought it worth mentioning.

**Comment by ESLyric** [comment]
the autoscroll menus only shows in real- none timesptamps lyrics.

**Comment by ESLyric** [comment]
What source?

**Comment by ESLyric** [comment]
I mean the radio source.

**Comment by ESLyric** [comment]
Sources needed.

**Comment by ESLyric** [comment]
cannot reproduce

**Comment by ESLyric** [comment]
the autoscroll menu will be added in next version.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1010
