### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Sickid** [ESLyric/feedback#169]
**问题描述**
1、桌面歌词：斜体字显示不完整（右上缺一角）；字体描边不全（见图）。
2、英文版右键菜单，很多英文单词大小写不太统一。

**软件环境:**
 - Windows LTSC 1809
 - foobar2000 2.2 2024-06-30
 - ESLyric 1.0.0.1007
 - 字体：Segoe UI Black

![Snipaste_2024-07-01_21-15-12](https://github.com/ESLyric/feedback/assets/5845381/c220f8f7-2041-4954-8b17-b33a744e9e82)
![Snipaste_2024-07-01_21-16-17](https://github.com/ESLyric/feedback/assets/5845381/d5f2dfa1-2be5-4a3d-8e3b-bf7c6c542b56)
![Snipaste_2024-07-01_21-28-51](https://github.com/ESLyric/feedback/assets/5845381/cffba7ad-d0e7-4dc7-bf56-36a7c84a112f)

**Comment by ESLyric** [comment]
试试新的 https://github.com/ESLyric/release/releases/tag/1.0.0.1010

**Comment by dghgw2022** [comment]
搜索歌词如果没有歌手名,只有标题的话,搜索出奇的慢,半天都没搜索出来

**Comment by a1waysbeta** [comment]
> 搜索歌词如果没有歌手名,只有标题的话,搜索出奇的慢,半天都没搜索出来

歌曲有同名的可能，数据库庞大，你最好完善歌曲信息
