### ISSUE TITLE
能否实现识别音频中人声的的时间,实现精准匹配歌词版本呢?

### ISSUE THREAD

**Issue by eAtmApp** [ESLyric/feedback#17]
一首歌有很多版本的歌词
很多版本时间对不上
我看有些视频处理软件也是用ffmpeg,能将人声翻译成文字
所以....
能否利用现有接口,识别出音频流中第一句人声的时间,然后对比搜索到的lrc歌词
达到精准匹配...
作者有考虑过这功能吗...
-----------------------
另外,作者用的是什么js引擎啊,编译出来那么小的

**Comment by a1waysbeta** [comment]
ESLyric 使用了[QuickJS](https://github.com/bellard/quickjs)引擎的[移植版本](https://github.com/c-smile/quickjspp) 提供自定义外部歌词源等功能，引擎中std及os模块未导出。

**Comment by ESLyric** [comment]
没有考虑过
