### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by endredaol** [ESLyric/feedback#170]
**问题描述**
ESLyric由v0.5.4.1028 (Beta) for foobar2000更新至Alpha版后渐变无法正常工作

**重现步骤**
重现该问题的步骤:
1. 更新ESLyric组件
2. 启用桌面歌词

**期望表现**
在渐变角度设置为45时无法正常工作

**截图**
v0.5.4.1028 (Beta) for foobar2000
![屏幕截图 2024-07-10 122706](https://github.com/ESLyric/feedback/assets/158291565/f2065aad-1611-4a7d-b01a-272760187738)

v1.0.0.1001 (Alpha) for foobar2000及以上
![屏幕截图 2024-07-10 123632](https://github.com/ESLyric/feedback/assets/158291565/8188f1cb-9df8-4a10-b366-c93c242544a7)

**软件环境:**
 - Windows版本 (如Windows 11 26120.961)
 - foobar2000版本 (如2.1.5)
 - ESLyric版本 (如v1.0.0.1001 (Alpha) for foobar2000)

**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件(推荐)
如崩溃请打包crashreport(crash reports目录下)
作者在此反馈信息基础上能直观了解或重现问题则能更快速处理，否则可能被作者忽略。

**Comment by ESLyric** [comment]
渐变还是有的，不过效果不太一样。下个版本会稍稍改善点。

**Comment by ESLyric** [comment]
试试 新的 https://github.com/ESLyric/release/releases/tag/1.0.0.1010

**Comment by endredaol** [comment]
> 试试 新的 https://github.com/ESLyric/release/releases/tag/1.0.0.1010

已解决
