### ISSUE TITLE
问题反馈：桌面歌词最后一行显示异常

### ISSUE THREAD

**Issue by Sickid** [ESLyric/feedback#171]
**问题描述**
桌面歌词最后一行显示异常，就是到了最后一行，会把第一行卡出来。

![Uploading Snipaste_2024-07-21_13-38-17.png…]()

**Comment by Sickid** [comment]
![Uploading Snipaste_2024-07-21_13-38-17.png…]()

**Comment by ESLyric** [comment]
感谢反馈。请更新最新版本。
https://github.com/ESLyric/release/releases/tag/1.0.0.1015
