### ISSUE TITLE
TT has found an error in the letras.js searcher script

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#173]
@ohyeah: after an update to the letras website, the letras.js searcher script broke.  TT found the line to fix and asked that I report it to you here;  I have confirmed that the new code DOES fix the searcher:

"In line 64 (EDIT: 63 in Notepad++) of the script:"

Change:

`if (attribute.key === 'class' && attribute.value === 'lyric-original') {`

to:

`if (attribute.key === 'class' && attribute.value.startsWith('lyric-original')) {`

Original reference in Foobar forum: [https://hydrogenaud.io/index.php/topic,122571.msg1048140.html#msg1048140](url)

**Comment by ESLyric** [comment]
Fixed.
