### ISSUE TITLE
新版的桌面歌词辉光宽度不生效

### ISSUE THREAD

**Issue by gitpaladin** [ESLyric/feedback#174]
**问题描述**
新版1.0.0.1015
![image](https://github.com/user-attachments/assets/174b2b9a-e84a-4b1c-b5c4-eae15d8361c0)
旧版 0.5.4.1025 (beta)
![image](https://github.com/user-attachments/assets/be136fa3-4485-4205-bb55-d9312de8cd7d)

**重现步骤**
重现该问题的步骤:
1. 调整辉光
2. 轮廓宽度为10

**期望表现**
和旧版辉光宽度应该10px

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 2.1.5 x64
 - ESLyric版本 (如0.5.1.1028)

**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件(推荐)
如崩溃请打包crashreport(crash reports目录下)
作者在此反馈信息基础上能直观了解或重现问题则能更快速处理，否则可能被作者忽略。

**Comment by ESLyric** [comment]
就是这样的效果

**Comment by gitpaladin** [comment]
![image](https://github.com/user-attachments/assets/1e0cc113-511a-454c-ad94-31a8d7e5594d)
那描边的效果也不对吧，描边开到10，应该是文字覆盖到描边的上方。而不是描边效果把文字本体盖住了

**Comment by ESLyric** [comment]
现在就是这样的了 暂时不会修改
