### ISSUE TITLE
歌词编辑器无法显示参照行歌词

### ISSUE THREAD

**Issue by YonderMiruku** [ESLyric/feedback#175]
**问题描述**
歌词编辑器无法显示参照行歌词，保存后也会直接丢失翻译

![QQ20240728-141114](https://github.com/user-attachments/assets/37297f24-b92f-40c2-b8a1-97db78f24b90)

**软件环境:**
 - foobar2000版本 2.1.5)
 - ESLyric版本 (1.0.0.1015)

**Comment by ESLyric** [comment]
试试这个 https://github.com/ESLyric/release/releases/tag/1.0.0.1016
