### ISSUE TITLE
问题反馈：歌词显示异常

### ISSUE THREAD

**Issue by xxbhpan** [ESLyric/feedback#176]
**问题描述**
歌词显示异常。注：无论是增强型歌词，还是卡拉OK歌词，还是逐行歌词，此问题均能出现。
特别提示：只在更改歌词后会出现异常，如果新建歌词，暂时还没有出现该现象。

**截图**
显示效果（已打开显示参照行歌词）
<img width="325" alt="Snipaste_2024-07-28_18-50-56" src="https://github.com/user-attachments/assets/6f3d4ce3-3ffe-4ace-8bcf-66c1db882c57">
实际歌词
<img width="513" alt="Snipaste_2024-07-28_18-55-45" src="https://github.com/user-attachments/assets/428ecf11-0d91-43a1-b317-b5b6784c431b">
歌词编辑器内歌词
<img width="575" alt="Snipaste_2024-07-28_18-56-20" src="https://github.com/user-attachments/assets/1ff426e0-ba7b-4576-8ce2-6d4393c4304b">
经过ESLyric插件另存为的异常显示的歌词
<img width="799" alt="Snipaste_2024-07-28_18-57-08" src="https://github.com/user-attachments/assets/2737a275-5c8e-40af-9d91-072df723b297">

**软件环境:**
 - Windows版本：Windows 10 19044.4651
 - foobar2000版本：2.1.4 Asion
 - ESLyric版本：v1.0.0.1015 (Alpha)

**log**
```
打开用于播放的音轨: "D:\Computer\Music\HonkaiStarRailOST\07 不眠之夜 WHITE NIGHT EP [2024-01-27]\01 不眠之夜 (中文 WHITE NIGHT) - HOYO-MiX, 张杰.flac"
[ESLyric]request lyric for "不眠之夜" by "HOYOMiX 张杰", search preprocessor enabled.
[ESLyric][1/2]request lyric from service: 音频标签
[ESLyric]meta search service read lyric from: LYRICS|UNSYNCED LYRICS|SUBTITLE|LYRICS-KTV|SRT|LYRICS-OK|SRT-EN
[ESLyric][2/2]request lyric from service: 音频标签, finish.
[ESLyric][1/2]request lyric from service: 本地文件
[ESLyric]found local lyric, stop search external sources due to settings.
[ESLyric][2/2]request lyric from service: 本地文件
[ESLyric]request file search service:
[ESLyric]file names: 01 不眠之夜 (中文 WHITE NIGHT) - HOYO-MiX, 张杰|HOYO-MiX, 张杰 - 不眠之夜 (中文 WHITE NIGHT)|HOYOMiX 张杰 - 不眠之夜
[ESLyric]extensions: lrc|txt|krc|qrc
[ESLyric]searching directory "D:\Computer\Music\HonkaiStarRailOST\07 不眠之夜 WHITE NIGHT EP [2024-01-27]\", recursive: false
[ESLyric][2/2]request lyric from service: 本地文件, finish.
文件末尾有垃圾(ID3 标签?)
```
（完）

**Comment by ESLyric** [comment]
麻烦提供一下原始歌词以及出现问题的步骤

**Comment by XiaoBaiXBS** [comment]
进过测试，将前面显示异常的行数前**时间显示**，用下面正常显示的歌词前**时间显示**进行替换，该异常效果消失。根据肉眼比对，无法察觉到替换前后的差异（上面**实际歌词**的图片也有展示）。
**时间显示**→[00:00.00]

**Comment by ESLyric** [comment]
提供一下音频文件?

**Comment by XiaoBaiXBS** [comment]
由于github无法发送25MB以上大小的附件，故采用蓝奏云。
https://wwd.lanzoub.com/iv0ud25vqisb  密码:ah5v
注：请注意相关标签，LYRICS标签下为异常状态歌词，LYRICS-KTV是通过我上一个评论操作后的歌词。
特别注释：在更新至1.0.0.1015 Alpha之前，1.0.0.1006 Alpha或者是1.0.0.1007 Alpha（我记不太清了，自0.5.4.1028之后，我只用过这两个版本中的其中的一个）无此现象（即便如此仅供参考，也有可能是我记忆的问题，但0.5.4.1028的时候，同样的歌词**确定**无此现象）。
对了，我通常使用Notepad3处理或者添加歌词，Notepad3默认打开时的编码为UTF-8。

**Comment by ESLyric** [comment]
这个歌词是自带的还是用ESL保存的？前面几行行首都有编码BOM就很奇怪（正常情况只有文件头会带编码BOM）。如果是自带的建议手动编辑下吧。
现在ESL解析歌词稍有变更，行首必须由[开始，解决一些标签混用的情况。

**Comment by XiaoBaiXBS** [comment]
这个歌词是通过复制正常歌词的前后部分（某些歌曲会把作曲编曲制作人和歌手放在最前面，然后其他制作信息放到最后面）分别复制到Notepad3中，在通过复制首行的时间轴替换到其他各个行中，以保证格式统一，然后再重新修改00:xx.00或者00:00.xx（xx表示修改的地方），最后将整个文字复制回歌词中。
你提到“正常情况只有文件头会带编码BOM”，是否我将“过复制首行的时间轴替换到其他各个行中”引起了时间轴混乱。有如下图所示，从图片中可以看到，首行显示是正常的，如果是因为这个原因的话，以后我修改自己的习惯就行。
<img width="244" alt="Snipaste_2024-07-30_00-24-59" src="https://github.com/user-attachments/assets/91dd8e66-c46f-4f50-976f-b96512c0d9b1">
(End)

**Comment by ESLyric** [comment]
> 你提到“正常情况只有文件头会带编码BOM”，是否我将“过复制首行的时间轴替换到其他各个行中”引起了时间轴混乱。

大概率是的。保存在LYRICS标签中的原始数据中，前几行每行行首都带有UTF8-BOM。由于第一行的BOM刚好是文件头，所以解析和显示没问题。

**Comment by XiaoBaiXBS** [comment]
OK，以后我注意一下就可以了，谢谢大佬的付出！
