### ISSUE TITLE
Lines split poorly when it comes to apostrophes, brackets and other symbols

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#177]
**Describe the bug**
When a lyric needs to be split to multiple lines because of a set margin, often the word is split in the middle as symbols such as "," "(" ")" "." and others are treated as separate words instead of a letter in a word.

**To Reproduce**
1. Set a margin for the lyrics panel
2. Play a song with ad-libs / words such as "I'm", "We're", "They're", etc. in it's lyrics
3. Adjust the margin to make it split a word containing one of the symbols

**Expected behavior**
The symbols should just count as part of the word and move with the rest to the second line.

**Screenshots**
![Screenshot (18)](https://github.com/user-attachments/assets/04b9772f-c229-4136-8552-7ab16498f0de)
![Screenshot (17)](https://github.com/user-attachments/assets/11bcdb27-c485-41f9-85a6-9fa9c7b00ddb)

**Desktop (please complete the following information):**
 - Windows Version [e.g. Windows 11 Pro 22631.3880]
 - Foobar2000 Version [2.1.5]

**Additional context**
Changing the margin is not my issue.

**Comment by ESLyric** [comment]
may regard white space as separator when split lines in next alpha version.

**Comment by GZ2E01** [comment]
The new alpha update fixed the issue perfectly, thanks a lot!
![image](https://github.com/user-attachments/assets/3bed2149-59d4-40ba-804d-3a4b1da077bf)
