### ISSUE TITLE
无法识别出带卡拉OK的增强型歌词（将增强型歌词视为一般歌词）

### ISSUE THREAD

**Issue by AkihaTatsu** [ESLyric/feedback#179]
**问题描述**
 - 在更新Foobar至2.0+版本和Eslyrics组件后，原先在本地的、带卡拉OK的增强型歌词无法正确识别，会被识别为没有卡拉OK效果的普通歌词；
   - 具体表现为：将右键-卡拉OK模式切换为“当显示为增强型歌词时开启”时，其表现和“关”完全一致，切换为“总是开启”则只会将整行视为一个单词进行从左至右的颜色替换，而非根据增强型歌词中每个单词的时轴进行颜色替换。
 - 直接保存后，带卡拉OK的增强型歌词可能会被替换为没有卡拉OK效果的普通歌词。
   - 以上两个问题随着Foobar和Eslyrics版本号不同会产生不同的表现，具体见下方“软件环境”一栏。

旧版Foobar和Eslyrics能够正确识别带卡拉OK的增强型歌词并保存。
参考歌词：[Revolutionary Protest Choir - La Varsovienne.txt](https://github.com/user-attachments/files/16470590/Revolutionary.Protest.Choir.-.La.Varsovienne.txt)

**期望表现**
上方为新版（即无法正确识别版本）的效果，下方为旧版（即能够正确识别版本）的效果；“卡拉OK模式”一栏均为“当显示为增强型歌词时开启”
![Comparison](https://github.com/user-attachments/assets/7619f4c8-c7cc-44d6-b518-f49a441018b1)
 - P.S. 如图所示，**旧版的Foobar和Eslyrics在遇到带翻译的歌词（即两行以同一时间开始）时会自动将歌词居中，而新版的Foobar和Eslyrics则并不会自动处理**；不清楚这也是bug还是暂时还未实现此功能

**软件环境:**
 - Windows 11 专业版 10.0.22631
 - 能够识别增强型歌词的版本（旧版）：
   - Foobar版本：1.6.16
   - ESLyric版本：0.5.3.1031 (Beta)
 - 不能够识别增强型歌词、保存不会替换原歌词的版本（新版）：
   - Foobar版本：2.1.5
   - ESLyric版本：0.5.4.1028 (Beta)
 - 不能够识别增强型歌词、保存会替换原歌词的版本（新版）：
   - Foobar版本：2.1.5
   - ESLyric版本：1.0.0.1016 (Alpha)

**Comment by ESLyric** [comment]
用foobox的话自己翻设置吧，歌词处理会默认启用一个转换为标准歌词的规则。
桌面歌词居中在右键菜单有选项。

**Comment by AkihaTatsu** [comment]
> 用foobox的话自己翻设置吧，歌词处理会默认启用一个转换为标准歌词的规则。

感谢解答，歌词规则的问题解决了，这应该跟foobox没关系，是我之前没有注意到这项设置发生了变化。

>  桌面歌词居中在右键菜单有选项。

关于翻译歌词居中的问题：我仔细检查了一下Elyrics的右键菜单，“对齐方式”一栏似乎只是对软件内显示歌词起作用（而且是无条件强制对齐），对桌面歌词的对齐不起作用；桌面歌词-重置位置只是重置歌词整体的位置到中央，而非只将有翻译参照行的歌词居中对齐；参数面板中桌面歌词-显示配置-首行 / 次行对齐也是无条件的强制对齐。

![QQ截图20240802223932](https://github.com/user-attachments/assets/07fbdb9e-a0dd-4266-baba-23f1520e83ed)
![QQ截图20240802224041](https://github.com/user-attachments/assets/e5d011bd-e131-4d63-b915-54257bb3763c)

这是前述三个版本（分别为有foobox、无foobox、有foobox；不过我个人测试猜测和foobox关系不大）下带翻译和不带翻译歌词的对比（参数面板中桌面歌词-显示配置均为“首行对齐-居左对齐”、“次行对齐-居右对齐”），是还有某项设置可以具体调整吗？

**Comment by ESLyric** [comment]
桌面歌词窗口上右键

**Comment by Cooperking112** [comment]
好兄弟怎么才能显示增强型歌词啊，能不能教教我
