### ISSUE TITLE
Support mxmlGetOpaque

### ISSUE THREAD

**Issue by wolfdate25** [ESLyric/feedback#18]
**Is your feature request related to a problem? Please describe.**
Need to parse full text (include whitespace) in xml node.
See [Discussion](https://www.msweet.org/mxml/mxml.html#mxmlGetText) item.

**Describe the solution you'd like**
Support the mxml getOpaque function or tell me other solution.

**Describe alternatives you've considered**

**Additional context**

**Comment by ESLyric** [comment]
OK, will add to next version.

Also, you can use other 3rd-party javascript libs to parse XMLs. (put in the 'lib' subdirectory)
For example:
https://github.com/NaturalIntelligence/fast-xml-parser

```
evalLib('fast-xml-parser/lib/fxp.min.js');
const parser = new fxp.XMLParser();
const docObj = parser.parse(xmlContent);
console.log(JSON.stringify(docObj));
```

**Comment by wolfdate25** [comment]
Thanks.
I have already used the txml library to solve the problem, but it is good that the built-in function increases.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1123

**Comment by ESLyric** [comment]
try the new version
```
let doc = mxml.loadString(xmlText, mxml.MXML_OPAQUE_CALLBACK);
...
let str = xmlNode.Opaque();
```

**Comment by wolfdate25** [comment]
works fine 👍
