### ISSUE TITLE
无法正确显示增强型歌词

### ISSUE THREAD

**Issue by CooperKing112** [ESLyric/feedback#180]
**问题描述**
自己下载到本地的增强型歌词无法正确显示，如下图所示，会把增强型歌词里的时间戳都显示上去
![foobar](https://github.com/user-attachments/assets/25162be2-8730-4e45-9873-7a216dcbbd68)

**Comment by CooperKing112** [comment]
1，只有从搜索里搜索完歌词，再选择歌词的时候，只有选酷狗的才有增强歌词也就是逐字歌词，选别的都没有增强歌词
2，并且酷狗的增强型歌词没有翻译，
3，即使我自己手动加上翻译，在桌面歌词上也无法显示
![foobar1](https://github.com/user-attachments/assets/f8835c1f-d3da-429d-a51f-752821cb779e)
![foobar2](https://github.com/user-attachments/assets/f23f28fd-d8ac-40cc-b94a-642f6048c4a1)

**Comment by ESLyric** [comment]
提供插件版本及有问题的歌词文件。

**Comment by CooperKing112** [comment]
插件版本：v0.5.4.1028 (Beta)，但是我试了最新的插件也是一样的问题（图1是最新版插件）（图2，3是v0.5.4.1028 (Beta)）
[音乐.zip](https://github.com/user-attachments/files/16486405/default.zip)
文件内容：Avril Lavigne - Alone(1)是用ESLyric插件搜索下载的酷狗的歌词
                  Avril Lavigne - Alone是我用LDDC软件下载的歌词
                  LDDC软件地址：https://github.com/chenmozhijin/LDDC

**Comment by ESLyric** [comment]
现在时间标签只有解析<xx:xx.xx>形式的，不识别<xx:xx.xxx>。等下个版本吧

**Comment by CooperKing112** [comment]
谢谢大佬解决！
我自己修改成xx.xx.xx格式后确实能正常显示了

目前还有一个疑问就是下图两种带翻译的歌词格式
![foobar3](https://github.com/user-attachments/assets/297f1948-ec9e-4c3c-a6ea-648691976679)
原词与翻译词时间戳一样的格式，桌面歌词无法显示出翻译
而翻译词在下一句原词的前xx.xx.01s时才能正常显示

**Comment by ESLyric** [comment]
为什么都不会在桌面歌词窗口右键？回复过不知道多少次了。

**Comment by CooperKing112** [comment]
啊，原谅我是小白，即使我知道右键看设置，但我并不明白参照行歌词是啥意思，我还是翻到前面issue129才明白，如果大佬有余力的话可以写一个简单的常见问题汇总，这样对小白会友好一些，也不会发issue打扰了。
最后还是感谢作者一直以来付出的更新和维护，期待下个版本！
