### ISSUE TITLE
1.0 Alpha版本引起系统死机

### ISSUE THREAD

**Issue by wangzz18** [ESLyric/feedback#182]
**问题描述**
打开foobar2000，随便动动，或者拿鼠标拖动一下foobar2000的窗口，系统就会直接卡死。
是画面卡死，鼠标键盘都没响应，但不会蓝屏，只能通过长按电源键重启。
可100%复现。
问题在更新N卡的显卡驱动后出现，怀疑是与N卡驱动的兼容问题。

**软件环境:**
 - Windows版本 (Windows 11 22631.3958)
 - foobar2000版本 (2.1.5 x64)
 - ESLyric版本 (1.0.0.1001 Alpha - 1.0.0.1006 Alpha)
 - CPU: 13600KF / 显卡：NVIDIA 4060 驱动版本：560.81 发布日期：08/06/2024

**其他信息**
- 将ESLyric回退到正式版0.5.4.1028问题消失。
- 跑甜甜圈或3DMark都不会出问题。
- 很可能更早的驱动也有问题只是不严重，因为这个卡死的问题已经有很长一段时间了。之前大约半个月到一个月左右会遇到一次。我发现卡死时都有foobar2000在运行，一度怀疑是WASAPI插件引起的，还禁用了foo_out_wasapis。
- 系统卡死后只能长按电源键来强制关机，重启后在系统日志中找不到任何当时错误的信息。
- V1.0以上版本使用Direct2D/DirectWrite渲染，可能与这个有关吧。

**Comment by ESLyric** [comment]
同样版本驱动测试没有问题

**Comment by wangzz18** [comment]
我的另一台机器，同样的驱动一样也没问题。但出问题机器还是可以100%重现。
一个R3程序无论如何也不应该把系统干死机了， 这里肯定是其他人的问题。只是想探究一下什么操作会触发。因此进行了进一步的测试：

1. 一个全新的foobar2000，不安装任何附加的扩展，Layout选择为Album List+Properties(tabbed)
2. 安装foo_uie_eslyric.1.0.0.1006 Alpha.fb2k-component
3. View-ESLyric-Show desktop lyric 打开桌面歌词
4. View-Layout-Enable layout editing mode，在左边All Music位置右键，选择Replace UI Element，将其替换成ESLyric

有如下现象：
刚替换完成时，是不会死机的，在界面上晃鼠标或用其他窗口去遮挡foobar的界面都不会死机。在用鼠标拖动窗口后立刻死机。
如果替换完就关闭界面，再重新打开foobar，什么都不干也没事，在用鼠标拖动窗口后立刻死机。
只有在替换界面Element和显示桌面歌词同时都开启才会死机，缺少其中任意一个都不会死机。
测试时没导入词曲。
希望以上的信息对于定位会有帮助，因为是死机，我无法提供现场信息。如果有其他的调试方法请提供给我。

**Comment by ESLyric** [comment]
看有没有其他人反馈吧。可能是什么问题导致我完全无头绪。

**Comment by oozan22** [comment]
I have also had that problem, its solved by itself somehow
i think that problem has to do with dyn blur as also after a while the fps decreases a lot

**Comment by wangzz18** [comment]
虚拟机上，windbg抓到的D2D相关的异常，不知道是否有关
`0:000> kv
 # Child-SP          RetAddr               : Args to Child                                                           : Call Site
00 0000009b`2b52f0c0 00007ffa`453baf9d     : 00000247`e9e79fa0 ffffffff`ffaa14e7 0001aa01`00000b68 00007ffa`40a68b48 : KERNELBASE!RaiseException+0x69
01 0000009b`2b52f1a0 00007ffa`408ab1c7     : 00007ffa`40880000 00000247`e9f705f0 ffffffff`aa0114e7 00007ffa`44c54cf0 : msvcrt!CxxThrowException+0xad
02 0000009b`2b52f210 00007ffa`4088a6be     : 00000247`0000006d 00000247`e9f67280 00000247`e9c886b8 00007ffa`40a83940 : d3d11!ThrowFailure+0x37
03 0000009b`2b52f260 00007ffa`408af175     : 00000000`40000502 00000247`e9f705f0 00000247`e9e700b0 00000000`00000000 : d3d11!NDXGI::CResource::CGdiInterop::CreateDeviceBitmap+0x126
04 0000009b`2b52f2e0 00007ffa`408ae386     : 00000247`e9e700b0 00000000`00000000 00000000`00000000 00000247`e9f67128 : d3d11!NDXGI::CResource::CGdiInterop::GetDC+0x231
05 0000009b`2b52f3c0 00007ffa`4045c7ea     : 00000000`00000000 00000247`e9de7040 00000000`00000000 0000009b`2b52f5b0 : d3d11!NDXGI::CResource::GetDCCore+0x286
06 0000009b`2b52f530 00007ffa`403927b3     : 00000000`00000000 00000000`00000000 0000009b`2b52f6e8 00000247`e9f67160 : d2d1!BitmapRealization::GetDC+0x126
07 0000009b`2b52f590 00007ffa`403800e9     : 0000009b`00001f80 00000247`e9de61b0 00000000`00001504 00007ff9`00009fc0 : d2d1!DrawingContext::GetDC+0x147
08 0000009b`2b52f600 00007ff9`fdef0d34     : 00000247`e9f64748 00000000`00000001 0000009b`2b52f7b0 00000000`00000001 : d2d1!D2DDeviceContextBase<ID2D1BitmapRenderTarget,ID2D1BitmapRenderTarget,ID2D1DeviceContext6>::GetDC+0x89
09 0000009b`2b52f650 00007ff9`fdeed56e     : 00000247`e9f645c0 3f91110c`97bdf747 0000009b`2b52f8d8 00000247`e9cf0fc2 : foo_uie_eslyric!DllGetClassObject+0x31694
0a 0000009b`2b52f7f0 00007ff9`fdef916b     : 00000247`e9f64618 3f91110c`97bdf747 0000009b`2b52fa60 00007ff9`fdefb613 : foo_uie_eslyric!DllGetClassObject+0x2dece
0b 0000009b`2b52f830 00007ff9`fdef8ff5     : 00000247`e9f64858 00000000`00028b0a 0000009b`2b52f8d8 00000000`00000b68 : foo_uie_eslyric!DllGetClassObject+0x39acb
0c 0000009b`2b52f880 00007ff9`fdeee16c     : 00000247`e9f64858 0000009b`2b52f9e0 0000009b`2b52f9e8 0000009b`2b52fa60 : foo_uie_eslyric!DllGetClassObject+0x39955
0d 0000009b`2b52f8d0 00007ff9`fdefac6b     : 00000247`e9f645c0 00007ff9`00000001 00000247`e9cf0fb0 0000009b`2b52f9f0 : foo_uie_eslyric!DllGetClassObject+0x2eacc
0e 0000009b`2b52f900 00007ff9`fdef8c75     : 00000247`e9f645c0 00000000`001d05d2 0000009b`00001504 00000000`00000000 : foo_uie_eslyric!DllGetClassObject+0x3b5cb
0f 0000009b`2b52f9b0 00007ff9`fde902ab     : 00000247`e9f645c0 00000000`001d05d2 00000000`00001504 00000000`00000000 : foo_uie_eslyric!DllGetClassObject+0x395d5
10 0000009b`2b52fa10 00007ffa`321e1598     : 00000247`e9f645c0 00007ff9`00001504 00000000`00000000 00000000`00000000 : foo_uie_eslyric!foobar2000_get_interface+0x9039b
11 0000009b`2b52fae0 00007ffa`44c474d6     : 00000000`00000001 00000000`00000000 0000009b`2b52fbe8 00000247`e718d960 : atlthunk!AtlThunk_0x1D+0x18
12 0000009b`2b52fb20 00007ffa`44c46ff2     : 00000247`e79e3970 00007ffa`321e1580 00000000`001d05d2 0000009b`2b52fdb0 : USER32!UserCallWinProcCheckWow+0x266
13 0000009b`2b52fca0 00007ff7`be034516     : 0000009b`2b52fdb0 0000009b`00000000 00000000`00000000 0000009b`2b52fdb0 : USER32!DispatchMessageWorker+0x1b2
14 0000009b`2b52fd20 00007ff7`be034345     : 00007ff7`be2ec0f0 00000247`e710bb01 00000000`00000000 00000247`e710bb70 : foobar2000+0x104516
15 0000009b`2b52fd70 00007ff7`be0367b9     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : foobar2000+0x104345
16 0000009b`2b52fdf0 00007ff7`be1ec262     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : foobar2000+0x1067b9
17 0000009b`2b52fef0 00007ffa`46a27ac4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : foobar2000+0x2bc262
18 0000009b`2b52ff30 00007ffa`4794a8c1     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
19 0000009b`2b52ff60 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21`

**Comment by oozan22** [comment]
Update: its back, showed a blackscreen for like 2 seconds, then the pc seeemed normal again but when dragging foobar the pc still freezes.
Happened totally at random, tries to reupdate windows and update graphics driver, did not help the problem.

**Comment by ESLyric** [comment]
可以试试最新的版本
https://github.com/ESLyric/release/releases/tag/1.0.0.1025
