### ISSUE TITLE
Lyric lines with no timestamp will default to [00:00.00] when .lrc files is saved

### ISSUE THREAD

**Issue by ngs428** [ESLyric/feedback#184]
Not sure if this is a bug or designed feature, but if a .lrc file is saved with missing timestamps on lines, the lines missing timestamps will all be saved as [00:00.00] on the lyric line.  Example below:

[00:00.00] I've been in this town so long that back in the city
[00:00.00] I've been taken for lost and gone
[00:00.00] And unknown for a long, long time

I am on ESLyric v1.0.0.1019 (Alpha) with Foobar 2.1.5 X64.

Other lyric editors will just leave them as is with no timestamp, that would be preferred.

I've been in this town so long that back in the city
I've been taken for lost and gone
And unknown for a long, long time

**Comment by ESLyric** [comment]
by design
