### ISSUE TITLE
Banner text alignment in 1019 Alpha

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#185]
In 1.0.0.1016, the display.banner.text entry appears centered in the panel:

![esl1](https://github.com/user-attachments/assets/552093e8-b04b-41e8-b75a-1dc83e8f3683)

After updating to 1.0.0.1019 (settings unchanged), the text is no longer centered:

![esl2](https://github.com/user-attachments/assets/99536e97-57f8-4f55-ab7c-ea6bd644a654)

While this is only a cosmetic issue, it does look "untidy" and makes you wonder if it is linked to a problem elsewhere.

Foobar v.2.2 x64, Windows 11 x64

**Comment by ESLyric** [comment]
Are you using custom layout? looks fine on my machine

**Comment by sveakul** [comment]
> Are you using custom layout? looks fine on my machine

No I am not.  Installed 1019 directly over 1016 without touching any settings, and banner text dropped down on its own.  First time that's happened after any other updates.

![layout](https://github.com/user-attachments/assets/aa491afa-965c-4e99-b4c0-628fba60788b)

**Comment by ESLyric** [comment]
Can you pack and upload your fb2k setup? I cannot figure out without reproduce

**Comment by sveakul** [comment]
> Can you pack and upload your fb2k setup? I cannot figure out without reproduce

I found out what affects it!  In Panel Options, it's the Display->Spacing->Line Space setting.  When set to "0", the banner is perfectly centered.  However, I use "150" there in order to make the lyrics start their display closer to the top of the panel, otherwise THEY are too far down.
In all previous versions, this setting never affected the position of the banner text, ONLY the lyrics.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1020

**Comment by sveakul** [comment]
> https://github.com/ESLyric/release/releases/tag/1.0.0.1020

Fixed in this version, thank you!
