### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Teto314** [ESLyric/feedback#186]
**问题描述**
对于没有任何歌词的音乐
手动编辑歌词写入后没有自动保存
虽然在歌词框中当前能显示
但点击在文件夹中打开却显示一个空的txt
点击其他歌曲再回来就直接无法匹配之前编辑的歌词了，同时文件夹中也只有那个空txt

不清楚如何触发的，之前使用时是可以自动保存为lrc的，突然就所有歌曲都无法保存了

**期望表现**
，不明原因，歌词自动保存lrc失败
希望恢复

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本: Windows 11 22631.4037
 - foobar2000版本: 1.6.16 UWP
 - ESLyric版本: 1.0.0.1020

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1021

**Comment by Teto314** [comment]
更新后问题解决了
