### ISSUE TITLE
System Crash unresponsive.

### ISSUE THREAD

**Issue by oozan22** [ESLyric/feedback#187]
**Describe the bug**
windows system crash -alpha version
Unable to shut down, screen freezes, music still playing. 

**To Reproduce**
Create a big panel of eslyric, 
drag foobar window aggressively and swiftly,
(Eole skin) switch between panels fast,
Also happens randomly when clicking anywhere in foobar.
Start foobar right as you start windows

**Expected behavior**
to not crash unable to shutdown, bad for pc health.

**Desktop (please complete the following information):**
 - Windows Version 23h2 latest
 - Foobar2000 Version 2.1.5

**Additional context**
Happened to another guy here if I recall.

**Comment by oozan22** [comment]
please dont ignore this issue, if its happened to more people, eslyric cant really advance from alpha state
i have reverted back to latest stable version, and its gone luckily

**Comment by oozan22** [comment]
i fear it has to do with audio drivers- wasapi shared/ exclusive mode compatability with used software/engine to run features and animations in background- dyn blur, shadowed lyrics blur effect, transparency mode for stuff.

**Comment by wangzz18** [comment]
我也一样遇到卡死时音乐会继续播放，直到一首歌结束的情况。同时我可以排除WASAPI引起的问题，因为我后来的测试使用的是一个干净的foobar2000，没有安装除ESLyric外的任何第三方插件。
我的怀疑是多线程引起的驱动死锁，可以排查一下是否有多线程对某个D2D/DDraw对象的调用。

这个BUG在大部分情况下是偶发的，一般很难意识到是ESLyric的问题。最初我怀疑过SSD，因为我的SSD温度一直都很高，特别是入夏后。后来加了散热片和风扇加强散热，大概排除了这个原因。接着又怀疑是超频引起在低功耗时的不稳定以及13、14代CPU引发的问题。最终因为多次的卡死时都在播放音乐，这才怀疑到foobar2000上。而foobar2000里最有可能卡死的只有WASAPI(其实这玩意儿的新版本也不可能卡死系统)。如果不是我在更新NV驱动后100%卡死，我用排除法去筛查插件，是无论如何都定位不到ESLyric上的。
鉴于发现问题是如此的困难，我不认为会有更多的用户来报告这个问题。

**Comment by oozan22** [comment]
For me the problem was immediately after installing the alpha version, so i knew it was that.
After copying my foobar to a portable version the problem is gone, so it has to do probably with threading priority and how the system handles several requests at once(hence why it was temporarily resolved updating windows - 2 weeks clean)

**Comment by ESLyric** [comment]
> 我也一样遇到卡死时音乐会继续播放，直到一首歌结束的情况。同时我可以排除WASAPI引起的问题，因为我后来的测试使用的是一个干净的foobar2000，没有安装除ESLyric外的任何第三方插件。 我的怀疑是多线程引起的驱动死锁，可以排查一下是否有多线程对某个D2D/DDraw对象的调用。
> 
> 这个BUG在大部分情况下是偶发的，一般很难意识到是ESLyric的问题。最初我怀疑过SSD，因为我的SSD温度一直都很高，特别是入夏后。后来加了散热片和风扇加强散热，大概排除了这个原因。接着又怀疑是超频引起在低功耗时的不稳定以及13、14代CPU引发的问题。最终因为多次的卡死时都在播放音乐，这才怀疑到foobar2000上。而foobar2000里最有可能卡死的只有WASAPI(其实这玩意儿的新版本也不可能卡死系统)。如果不是我在更新NV驱动后100%卡死，我用排除法去筛查插件，是无论如何都定位不到ESLyric上的。 鉴于发现问题是如此的困难，我不认为会有更多的用户来报告这个问题。

插件没有用到多线程渲染。方便的话加下Q群，周末有时间的话看看。 315848052

**Comment by Teto314** [comment]
> 我也一样遇到卡死时音乐会继续播放，直到一首歌结束的情况。同时我可以排除WASAPI引起的问题，因为我后来的测试使用的是一个干净的foobar2000，没有安装除ESLyric外的任何第三方插件。 我的怀疑是多线程引起的驱动死锁，可以排查一下是否有多线程对某个D2D/DDraw对象的调用。
> 
> 这个BUG在大部分情况下是偶发的，一般很难意识到是ESLyric的问题。最初我怀疑过SSD，因为我的SSD温度一直都很高，特别是入夏后。后来加了散热片和风扇加强散热，大概排除了这个原因。接着又怀疑是超频引起在低功耗时的不稳定以及13、14代CPU引发的问题。最终因为多次的卡死时都在播放音乐，这才怀疑到foobar2000上。而foobar2000里最有可能卡死的只有WASAPI(其实这玩意儿的新版本也不可能卡死系统)。如果不是我在更新NV驱动后100%卡死，我用排除法去筛查插件，是无论如何都定位不到ESLyric上的。 鉴于发现问题是如此的困难，我不认为会有更多的用户来报告这个问题。

你是什么版本的foobar
我用卸载了wasapi的uwp旧版1.6.16暂时还没有遇到这个问题

**Comment by ESLyric** [comment]
If you are using the desktop lyric at the same time, you can try the latest alpha version.
