### ISSUE TITLE
Lyrics don't show up when I play the track before activating the ESLyric popup window

### ISSUE THREAD

**Issue by MG240** [ESLyric/feedback#188]
I use ESLyric as a popup window (not a part of the layout)
When I play the track before activating the ESLyric popup window, lyrics don't show up.
I have to re-play the track to make the lyrics show up.

- Windows 11 23H2 64bit
- foobar2000 v2.2 preview 2024-08-22 [x64]
- ESLyric v1.0.0.1021 (Alpha)

**Comment by a1waysbeta** [comment]
waiting for the fix

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1022

**Comment by MG240** [comment]
Lyrics are now being displayed properly after activating the ESLyric popup window. Thanks a lot!

But now, the popup window panel options are identical to the full-screen options. For example, if I change the font size in the popup window, it also affects the full-screen options. This was not the case before. Should I create a separate issue for this?

**Comment by ESLyric** [comment]
The fullscreen window and popup window were the same. You can use foo_flowin to create a separated one.

**Comment by MG240** [comment]
> The fullscreen window and popup window were the same. You can use foo_flowin to create a separated one.

Alright then. I will check out foo_flowin. Thank you very much.
