### ISSUE TITLE
Option to not auto-search unless panel is visible

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#189]
ESLyric 1.0.0.1021, Foobar v2. x64

When auto-search when playback starts is activated, auto-searching is performed even when the ESLyric panel is not open.

The downside of this is that if another searching plugin happens to be open and searching, the "closed" ESlyric will also be performing the same search in the background.  This can result in over-activity at the source website by the user, which could lead to an IP suspension/ban.

Please add an option to "Do not auto-search when the ESLyric panel is not visible/open."  Thank you for your consideration.

**Comment by ESLyric** [comment]
If it still automatically searches without a panel, please check if the theme you're using has set an ESLyric callback or use the default theme instead.

**Comment by sveakul** [comment]
> If it still automatically searches without a panel, please check if the theme you're using has set an ESLyric callback or use the default theme instead.

I'm using the default theme and DUI.  Below shows the single Foobar panel that has 3 tabbed lyric searchers in it, the end one being "ESLyric."  If the settings in ESLyric Lyric Search is set to "Automatically search when playback starts", it performs a search in the background no matter what tab is actually open/active.

There should be the option to "Automatically search when playback starts only if ESLyric is selected as the active/open tab"

![panel1](https://github.com/user-attachments/assets/4cf6b8d1-2bad-4a93-a4b1-4ba20618dc29)

**Comment by ESLyric** [comment]
few people need this.

**Comment by sveakul** [comment]
> few people need this.

In the Foobar world, LOTS of people use more than one of anything--spectrum analyzers, artwork tools, and yes lyric searchers.  They back up each other by allowing the user to have more than one search tool--some perform better on some sites than the other.  What they DON'T need is the possibility of getting site-banned because of sources being searched at the same time from the same IP.

Would it be that difficult to add "Autosearch only when ESLyric panel is visible"?  Please consider this.

**Comment by ESLyric** [comment]
> > few people need this.
> 
> In the Foobar world, LOTS of people use more than one of anything--spectrum analyzers, artwork tools, and yes lyric searchers. They back up each other by allowing the user to have more than one search tool--some perform better on some sites than the other. What they DON'T need is the possibility of getting site-banned because of sources being searched at the same time from the same IP.
> 
> Would it be that difficult to add "Autosearch only when ESLyric panel is visible"? Please consider this.

I dont think lots of people use multiple lyric components.
