### ISSUE TITLE
歌词面板“”高亮颜色“功能如何取消

### ISSUE THREAD

**Issue by ppqcool-1988** [ESLyric/feedback#190]
**问题描述**

每次播放歌曲，歌词的高亮颜色功能会自动启用

**截图**
![image](https://github.com/user-attachments/assets/c3b51ce8-c604-4a4c-a2d9-bd12f7d85f8e)

**Comment by ESLyric** [comment]
高亮颜色旁边这么大的一个勾选项不会勾？
