### ISSUE TITLE
Crash issue in 1.0.0.1022

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#192]
Foobar 1.6.18 Windows 11 x64, ESL 1.0.0.1022

When in Foobar Preferences, just selecting the option "Eslyric->Desktop Lyric" will cause Foobar to crash.  Crash report is attached.  Repeatable.

In case it is relevant, I never actually USE the Desktop Lyric display (only panel) which was turned off at the time 1022 was installed over 1021.
[failure_00000002.txt](https://github.com/user-attachments/files/16915243/failure_00000002.txt)

**Comment by ESLyric** [comment]
plz upload the .dmp file and foo_multisource.dll

**Comment by ESLyric** [comment]
I reupload the attachment, try reinstall to see if it works.

**Comment by sveakul** [comment]
> I reupload the attachment, try reinstall to see if it works.

Works now, no crash!
