### ISSUE TITLE
希望添加和老版本一样的仿真透明歌词页面背景。

### ISSUE THREAD

**Issue by osakana313** [ESLyric/feedback#193]
作者大大，不知可否在alpah版本里添加上仿真透明背景的歌词页面背景，和之前老版本一样的。感谢作者大大

![_HM%{V4EIMAC_45 G_BH5G5](https://github.com/user-attachments/assets/48010645-8e14-400f-a584-08c994d3ec0e)

**Comment by ESLyric** [comment]
不会再加回去了
