### ISSUE TITLE
关于歌词还有动态模糊得一些问题

### ISSUE THREAD

**Issue by gebilaowang66662** [ESLyric/feedback#196]
就是那个参考歌词翻译可以跟着一起高亮嘛
![_WHL_V_(YB8%48~URXD JR2](https://github.com/user-attachments/assets/f9e2d408-d8fe-4ae9-ad47-19412a136a01)
![3EL5)53W$Z9Z7Y`ZEC$U)VY](https://github.com/user-attachments/assets/0d2f2a32-a91f-450a-a8fc-ae7ff22e83ab)
就像下面这样
![2BIAR9___D( ~_2ZE5Y6THS](https://github.com/user-attachments/assets/034fb2f3-b178-4ee4-86d6-a4ae508e6cb8)
以及歌词背景那个动态模糊有点低帧，不知道怎么设置
还有歌曲那个歌词逐字有点不准，不知道能逐字显示得条件是什么

**Comment by ESLyric** [comment]
不能。现在面板歌词及桌面歌词都是60fps。
