### ISSUE TITLE
[Feature Request] Option to disable image fade effect when switching songs

### ISSUE THREAD

**Issue by Fizbin99** [ESLyric/feedback#197]
1.0.0.1019 Alpha
优化歌曲切换时面板显示效果

Please add an option to disable the above feature, introduced in version 1.0.0.1019 Alpha.

**Comment by ESLyric** [comment]
no

**Comment by Fizbin99** [comment]
No? What do you mean, no?  It would take 2 seconds to do this. It's such a radical change you made to the way the image is presented. It makes it look slow to load. I want the image to load instantly like it did before.

**Comment by ESLyric** [comment]
It should not take 2 seconds. you can make a screen record and upload, I will see if it is expected.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1023

**Comment by Fizbin99** [comment]
"display.background.transition.duration" - Thank you very much, sir!
