### ISSUE TITLE
希望能增加歌词滚动预览

### ISSUE THREAD

**Issue by shardine** [ESLyric/feedback#20]
**功能简介**
通过鼠标滚轮可以上下预览歌词而不影响播放进度，现在只能用鼠标拖动调整进度

**是否有参考软件实现**
类似于流媒体软件歌词界面，用户可以滚动页面预览歌词

**Comment by ESLyric** [comment]
需要这么预览的使用场景是什么？

**Comment by shardine** [comment]
就是想要边听边研究歌词，现在这样的话听到后面的时候如果需要回看前面的歌词就不得不调整进度了

**Comment by ESLyric** [comment]
> 就是想要边听边研究歌词，现在这样的话听到后面的时候如果需要回看前面的歌词就不得不调整进度了

那弹出一个窗口显示纯文本歌词也行吧？

**Comment by shardine** [comment]
> > 就是想要边听边研究歌词，现在这样的话听到后面的时候如果需要回看前面的歌词就不得不调整进度了
> 
> 那弹出一个窗口显示纯文本歌词也行吧？

是有替代方案。我是提个意见，希望能在eslyric里加上这个功能，我觉得加上这个功能用起来更方便

**Comment by ESLyric** [comment]
感觉是比较小众的功能，要实现好的话会增加复杂度。可能暂时不会考虑加入，但是简单的弹出歌词文本信息倒是可以。

**Comment by a1waysbeta** [comment]
右键增加一个切换模式可行不？纯文本模式，歌词模式

**Comment by shardine** [comment]
> 右键增加一个切换模式可行不？纯文本模式，歌词模式

实现起来困难的话，我觉得这个暂时的替代方案蛮好的

**Comment by ESLyric** [comment]
> 实现起来困难的话，我觉得这个暂时的替代方案蛮好的

对我来说是一样的，最简单的是弹个纯文本的信息窗口。

**Comment by medp7060** [comment]
其实0.3.6就基本上有“歌词滚动预览”：在触摸屏上，按住歌词显示窗口，向上下（前后）滑动即可看前后的歌词。不过手一松开，播放就从当前位置重新开始了。在华为手机自带的播放器中，这样上下滑动看前后的歌词是不影响播放的，如果几秒后不再滑动，歌词显示就恢复正常。ESLyric和华为对滑屏的处理各有优缺点。”弹个**纯文本**的信息窗口“是个好注意！

**Comment by ESLyric** [comment]
歌词信息中显示了文本歌词
https://github.com/ESLyric/release/releases/tag/0.5.3.1005

**Comment by Reapor-Yurnero** [comment]
> 歌词信息中显示了文本歌词 https://github.com/ESLyric/release/releases/tag/0.5.3.1005

请问一下在哪里，没有找到？

**Comment by a1waysbeta** [comment]
右键，歌词信息

**Comment by Reapor-Yurnero** [comment]
> 右键，歌词信息

谢谢 没更新哈哈
