### ISSUE TITLE
外部JS面板控制接口

### ISSUE THREAD

**Issue by gebilaowang66662** [ESLyric/feedback#201]
大佬，这个接口只局限于下面这些吗，还是还有别的功能。我做好js该放哪里
![3G713}0SO)GTBS{ISUHOFHB](https://github.com/user-attachments/assets/0f256cb5-6d9a-4982-89ce-5d6729d9d126)

**Comment by a1waysbeta** [comment]
你可以参考https://github.com/dream7180/foobox-cn

**Comment by gebilaowang66662** [comment]
> 你可以参考https://github.com/dream7180/foobox-cn

其实我是想看看还有没有能通过其他方法，自定义那个全屏歌词页面 ：）
