### ISSUE TITLE
背景模糊开启一段时间会掉帧

### ISSUE THREAD

**Issue by gebilaowang66662** [ESLyric/feedback#202]
大佬救命，背景模糊开启一段时间会掉帧，掉帧的状态下关闭全屏再打开，还是关闭软件再打开，都没有用，唯一的解决方法是重启电脑才能解决，难道是内存溢出了？

![4@NBQ8K95TKK}O {E`W(%{8](https://github.com/user-attachments/assets/0e60d099-b03f-44e9-9b59-94d8f6972bc9)

![_ALF789MXEH (CGA TIU)H4](https://github.com/user-attachments/assets/e975847f-7d2d-4081-b11e-c3fa72a74752)

**Comment by ESLyric** [comment]
不使用动态模糊会不会出现？还有“一段时间”是多久？

**Comment by gebilaowang66662** [comment]
> 不使用动态模糊会不会出现？还有“一段时间”是多久？

就是动态模糊的背景而已，歌词没事，背景平移会随着开启的时间增加慢慢变得卡顿，一个小时左右
下面是录屏还有配置文件

https://wwpt.lanzoul.com/b02ihtsgmj
密码:5sri

**Comment by gebilaowang66662** [comment]
我这1050ti，这占用没问题把

![) M7O(6`IFI0L0G 5LB%C4W](https://github.com/user-attachments/assets/47be81f3-41f6-4918-bfc9-5e973d3f8b1b)

**Comment by ESLyric** [comment]
要过段时间才能再看了

**Comment by gebilaowang66662** [comment]
> 要过段时间才能再看了

好滴

**Comment by gebilaowang66662** [comment]
这个插件是依赖什么运行的，我可不可以强制停止依赖运行的应用程序，看看能不能释放一下

**Comment by gebilaowang66662** [comment]
还是算法里面的数值变得大了还是怎么样了

**Comment by ESLyric** [comment]
> 还是算法里面的数值变得大了还是怎么样了

是的，只能重启。

**Comment by gebilaowang66662** [comment]
啊这，可以通过算法重置吗，重启有点难受

**Comment by ESLyric** [comment]
> 啊这，可以通过算法重置吗，重启有点难受

现在只能重启，修复要过段时间。

**Comment by gebilaowang66662** [comment]
好滴

**Comment by ESLyric** [comment]
试试这个版本
https://github.com/ESLyric/release/releases/tag/1.0.0.1025

**Comment by gebilaowang66662** [comment]
好的
