### ISSUE TITLE
关于歌词规则

### ISSUE THREAD

**Issue by gebilaowang66662** [ESLyric/feedback#203]
大佬，这个歌词可以自定义规则吗，我想把歌词开头，还有间隔较长的中间添加像ktv那样得三个大点○○○
就像这样
![43KGY2CWNCWL~59%68~MM I](https://github.com/user-attachments/assets/5de7d2d4-b8ab-4e85-8330-47723fd450a7)

![Z W}GC) 6B2W~9@YG77~RBY](https://github.com/user-attachments/assets/e8466e86-fbd1-42e3-81f1-178d801df974)

**Comment by ESLyric** [comment]
没有
