### ISSUE TITLE
本地歌词不会自动加载

### ISSUE THREAD

**Issue by shimo-saki** [ESLyric/feedback#204]
**问题描述**
简要清晰地描述问题。反馈清晰易于重现的问题会较快速的处理；过于简略的反馈作者会忽略。
1. 歌词显示异常请附上歌词文件，内嵌歌词请保存为文本文件后附上(此时先载入该保存的歌词确认问题仍存在)。
2. 崩溃问题请将crash reports目录打包后附上。

**重现步骤**
重现该问题的步骤:
1. 加载ESLyric歌词面板
2. 歌词未加载
3. 手动搜索歌词后选择本地歌词可正常加载

**期望表现**
本地歌词自动加载

**截图**
![image](https://github.com/user-attachments/assets/81057e8d-91fe-4436-877e-d19883407d0f)
![image](https://github.com/user-attachments/assets/f50d8c37-67a8-443b-9d5e-8c1501978513)
![image](https://github.com/user-attachments/assets/68a059be-a300-45b0-b851-5de79f938ecb)

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586) `Windows 11 22631.4317`
 - foobar2000版本 (如1.6.8) `2.1.5`
 - ESLyric版本 (如0.5.1.1028) `1.0.0.1023 (Alpha)`

**其他信息**
其他与问题相关的信息

**Comment by shimo-saki** [comment]
不是某一首歌不加载，是所有歌都不加载
使用`0.5.4.1028`版本无此bug

**Comment by ESLyric** [comment]
你没有看过设置项吗

**Comment by shimo-saki** [comment]
我是直接从`0.5.4.1028`更新的，设置项和旧版本是一致的

**Comment by ESLyric** [comment]
看下选项里自动加载的几个选项，注意下匹配度

**Comment by shimo-saki** [comment]
好的，没改匹配度，把自动加载改成`自动选择当前最佳匹配歌词`就可以了，不过为什么用`搜索全部歌词源后自动选择最佳匹配歌词`却不行呢

**Comment by ESLyric** [comment]
有个最小的匹配度，你手动搜索的时候勾选了全部显示，不勾选的话，那个候选歌词应该是隐藏的。看起来文件名后面带了一串其他的字符。

**Comment by shimo-saki** [comment]
没有，我歌曲和歌词文件名是完全相同的

**Comment by ESLyric** [comment]
截图下你原先不会自动加载的设置项，然后上传一下你的歌词和歌曲文件

**Comment by shimo-saki** [comment]
> 截图下你原先不会自动加载的设置项，然后上传一下你的歌词和歌曲文件

![1](https://github.com/user-attachments/assets/69f04e21-42f1-4c43-a358-03b40d314f14)

**Comment by shimo-saki** [comment]
对于所有歌曲都是这样，不局限于某一首歌

**Comment by ESLyric** [comment]
> 对于所有歌曲都是这样，不局限于某一首歌

我不知道你歌词及音频怎么命名的，所以需要打包一下你的歌词文件及歌曲

**Comment by shimo-saki** [comment]
[Uploading ClariS (クラリス) - 幻想恋慕.zip…]()

**Comment by ESLyric** [comment]
> Uploading ClariS (クラリス) - 幻想恋慕.zip…

传的有问题，无法下载

**Comment by ESLyric** [comment]
收到，但是本地重现不了。

**Comment by shimo-saki** [comment]
> 收到，但是本地重现不了。

需要我打包一份我的环境吗

**Comment by a1waysbeta** [comment]
打包一份看看

**Comment by shimo-saki** [comment]
https://www.airportal.cn/764392/bQj72LQLBE

**Comment by a1waysbeta** [comment]
https://github.com/user-attachments/assets/6dda59d6-2bd2-436d-9b89-7a8bffb953c8

没有复现

**Comment by ESLyric** [comment]
试试这个版本
https://github.com/ESLyric/release/releases/tag/1.0.0.1025

**Comment by shimo-saki** [comment]
> 试试这个版本 https://github.com/ESLyric/release/releases/tag/1.0.0.1025

感谢修复
