### ISSUE TITLE
歌词滚动效果在Foobar2000重启后恢复Default

### ISSUE THREAD

**Issue by shimo-saki** [ESLyric/feedback#205]
**问题描述**
简要清晰地描述问题。反馈清晰易于重现的问题会较快速的处理；过于简略的反馈作者会忽略。
1. 歌词显示异常请附上歌词文件，内嵌歌词请保存为文本文件后附上(此时先载入该保存的歌词确认问题仍存在)。
2. 崩溃问题请将crash reports目录打包后附上。

**重现步骤**
重现该问题的步骤:
1. 设置任意歌词滚动效果
2. 重启Foobar2000
3. 滚动效果被恢复成`Default`

**期望表现**
重启保留配置

**截图**
![recording](https://github.com/user-attachments/assets/07dc0a2e-4404-4bdd-a283-d29d65c7bdc0)

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586) `Windows 11 22631.4317`
 - foobar2000版本 (如1.6.8) `2.1.5`
 - ESLyric版本 (如0.5.1.1028) `1.0.0.1023 Alpha`

**其他信息**
其他与问题相关的信息

**Comment by ESLyric** [comment]
只是显示问题，设置值是生效的，下个版本修复。
