### ISSUE TITLE
After updating to 1.0.0.1025 Alpha album art no longer appears in custom layout

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#206]
**Describe the bug**
After updating to 1.0.0.1025 Alpha tagged album art no longer appears in custom layout

**To Reproduce**
Make custom layout including albumart as one of the elements

**Expected behavior**
The album art should work like in the previous version

**Screenshots**
![image](https://github.com/user-attachments/assets/bdec1767-d6ac-44f0-983c-15f623f32b8e)
![image](https://github.com/user-attachments/assets/7339391b-3a3d-4b32-80e4-392f4b95d42a)
(screenshot from yesterday)

**Desktop (please complete the following information):**
 - Windows Version [Windows 11 Pro 22631.4317]
 - Foobar2000 Version [2.1.5]

**Additional context**
Thank you for finally fixing the dyn blur framerate issue! ❤️

**Comment by GZ2E01** [comment]
![image](https://github.com/user-attachments/assets/3bf549ad-1199-4a8c-b624-e0587afa9a51)
Here is the layout. Credit to @gebilaowang66662

**Comment by ESLyric** [comment]
Layout is in development. so dont report layout issues.
You must explicitly set album art type or set "follow-background" to "1".
```
<!--same as -->
<element type="albumart" .... follow-background="1" />
```
or
```
<element type="albumart" .... album-art="front" use-stub="0" />
```

**Comment by GZ2E01** [comment]
that fixed it, thanks ❤️ 
![image](https://github.com/user-attachments/assets/8185ce03-8261-49cd-9b9d-738ed85ab545)
