### ISSUE TITLE
Album art element not displayed in the latest version

### ISSUE THREAD

**Issue by pierx** [ESLyric/feedback#207]
**Describe the bug**
Album art element not displayed in the latest version 1.0.0.1025 Alpha

**To Reproduce**
This custom layout works just fine in the previous ESLyric version
`
<panel layout="stack" name="test" orientation="vertical">
    <element type="container" anchor="stretch">
        <element type="lyric" margin="0,24,0,-180" text-align="center" anchor="stretch"  />        
    </element>
    <element type="container" anchor="stretch" orientation="horizonal" width="100%" height="20%" >
        <element type="albumart" margin="18,100,0,0" width="100" height="100" options="4" />
            <element type="container" anchor="stretch"  orientation="vertical">
                <element type="text" text-align="left" margin="12,190,0,0" caption="[%artist%]" font-size="12" text-color="#ffffff" height="50" width="100%" line-space="12" />        
                <element type="text" text-align="left" margin="12,-15,0,0" caption="%title% '('%year%')'" font-size="12" text-color="#efefef" height="50" width="100%" line-space="2" />
            </element>
    </element>
</panel>
`

**Expected behavior**
This is what it looks like on previous version v1.0.0.1023 (Alpha)
![foobar2000_u6zZq86Qzz](https://github.com/user-attachments/assets/2ac1600b-664a-4b7c-b22c-517f1a4bf277)

**Screenshots**
Album art element not displayed in the latest version 1.0.0.1025 Alpha
![foobar2000_V8f3LdfIeC](https://github.com/user-attachments/assets/efad7643-6fff-4f11-adce-1bd5b64d0978)

**Desktop (please complete the following information):**
 - Windows Version 10
 - Foobar2000 v.2.1.5 x86 
 - Foobar2000 v.2.24 Preview x64

Thank you

Regards

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/feedback/issues/206
