### ISSUE TITLE
A couple of feature requests I think would be nice additions.

### ISSUE THREAD

**Issue by GZ2E01** [ESLyric/feedback#208]
1. A gradient color transition instead of a straight line for word by word lyrics
Currently it looks like this:
![image](https://github.com/user-attachments/assets/9b118d29-4114-4302-b810-bcea7452845c)
A gradient / blur of some kind (possibly a toggle) would be greatly appreciated for this. I don't think it's that hard to implement and objectively results in way better looks, something like this: 
![image](https://github.com/user-attachments/assets/a9d078b6-9243-456f-85b2-ef5f38e69994)

2. Customizable dyn blur: saturation, blur intensity, fill stretch, adapt and center. Maybe even animation speed. Overall similar to this
![image](https://github.com/user-attachments/assets/bf6d4360-e875-4dbc-b265-909f9b19ab0e)

3. Multiple lines could highlight at the same time if both at the same timestamp, without scrolling further, something like on Apple Music

https://github.com/user-attachments/assets/b086f009-67e5-42e2-9218-954462eafa46

4. Word by word highlight should stop when there's a pause in the word by word lyrics instead of slowly highlighting past

https://github.com/user-attachments/assets/a713658d-af95-4368-9920-71037e2dc15a

Please let me know which of these could be added and which not.

**Comment by ESLyric** [comment]
1.2 I dont know what you mean
3. No plan to change.
4. You should adjust your lyric timestiamps.
