### ISSUE TITLE
Can't Jump to First Lyric Line

### ISSUE THREAD

**Issue by MG240** [ESLyric/feedback#209]
**Bug Description**

When I play a track, I can't use mouse drag to jump forward to the first lyric line. It only works if I need to jump back.

**Steps to Reproduce**

1. Play a track.
2. Mouse Drag in the Lyrics Panel to the first lyric line. Nothing happens.

**Desktop Information**
 - Windows 11 24H2
 - Foobar2000 v 2.24 preview 2024-11-06 [x64]
 - ESLyric 1.0.0.1031 (Alpha)

**Comment by a1waysbeta** [comment]
Don't understand

**Comment by MG240** [comment]
I tried the `Ctrl+Alt+Scroll Wheel` shortcut that you mentioned in another issue, and it worked, but the mouse drag method is not working.

Here's what I mean:

https://github.com/user-attachments/assets/4f649ca8-77ff-4e5b-882a-2a6f0b1b42b7

**Comment by a1waysbeta** [comment]
https://github.com/user-attachments/assets/611f39de-3f70-4924-8e6c-740eb793274a

**Comment by MG240** [comment]
I'm only talking about jumping forward by dragging the mouse to the **first lyric** (line).

For example: Consider a song with a lengthy intro, and you want to skip to the **first lyric** by dragging the mouse.

**Comment by a1waysbeta** [comment]
I don't understand what you mean. Are your lyrics pure text? Or is it a synchronized lyric with a time stamp? Watch my video and want to drag to the line. Drag to the line.

**Comment by MG240** [comment]
Synced Lyrics. I've watched your video, and yes, dragging generally works, but it doesn't **go forward** to the first lyric.

Maybe I'm just nitpicking, and this is by design.

Here's another video with sound, which makes it clearer:

https://github.com/user-attachments/assets/db1839af-2ac0-4222-b6ee-1fc68766ef42

**Comment by a1waysbeta** [comment]
Is your first line of lyrics an introductory text without time? The display matches the timestamp and the playback progress. If your text does not have a time stamp, how do you let it stay?

**Comment by MG240** [comment]
No, the first line is not an introductory text; it's a synced lyric.

![2024-11-16_033329](https://github.com/user-attachments/assets/4d3c2980-9425-407b-b6eb-3fff0cd2f4e7)

**Comment by a1waysbeta** [comment]
I finally understand what you mean. You can insert a blank line of lyrics with a time stamp of 0 in front of the first line of lyrics to solve this problem.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1035

**Comment by MG240** [comment]
> I finally understand what you mean. You can insert a blank line of lyrics with a time stamp of 0 in front of the first line of lyrics to solve this problem.

Thank you for the tip. That would help mitigate the issue, but we’re fortunate that the latest release (1.0.0.1035) has completely fixed it.

> https://github.com/ESLyric/release/releases/tag/1.0.0.1035

Thank you very much.
