### ISSUE TITLE
保存歌词到标签，但是其他的播放器无法识别

### ISSUE THREAD

**Issue by meihus** [ESLyric/feedback#21]
音乐内嵌的歌词速度不对，调整了之后保存到标签，但是其他的播放器识别不出来。
没有内嵌歌词的音乐，搜索网上的歌词，写入标签，potplayer也识别不出来。

**Comment by a1waysbeta** [comment]
这个没说要兼容其他播放器

**Comment by meihus** [comment]
用音乐标签就都可以识别出来，每次切换音乐标签很麻烦，这个插件是前面加了offset改的时间，而不是改每一个时间点，别的软件也能识别出出，增加兼容性觉得挺好的。

**Comment by ESLyric** [comment]
> 音乐内嵌的歌词速度不对，调整了之后保存到标签，但是其他的播放器识别不出来。

`offset`标签是‘规范’的做法，你可以反馈给其他播放器让其支持下。

> 没有内嵌歌词的音乐，搜索网上的歌词，写入标签，potplayer也识别不出来。

插件用fb2k的SDK接口写入的标签，如果其他播放器不读取的话我也没啥办法？不会考虑用第三方的标签库。

**Comment by meihus** [comment]
哦哦，这样啊，我明白了
