### ISSUE TITLE
[1.0.0.1035 Bug] Issue with Context Menus Failing to Expand on Mouse Hover

### ISSUE THREAD

**Issue by MG240** [ESLyric/feedback#211]
**Bug Description**

1.0.0.1035 release causes a lag in foobar context menus, and submenus **randomly** fail to expand on mouse hover.
This happens with tracks, whether they have lyrics or not.

I rolled back to 1.0.0.1031 and can confirm that the issue does not occur with that version.

**Steps to Reproduce**

It's hard to reproduce and notice, but here's a video that shows what I mean:

https://github.com/user-attachments/assets/dae5a1c3-7ea2-47e2-bc76-6f13be017eb9

**Desktop Information**

- Windows 11 24H2
- Foobar2000 v 2.24 preview 2024-11-14 [x64]
- ESLyric 1.0.0.1035 (Alpha)

**Comment by ESLyric** [comment]
Plz pack and upload your setup if possible.

**Comment by MG240** [comment]
The issue still occurs with a fresh portable installation of (foobar2000-x64_v2.24_preview_2024-11-14) and a new installation of ESLyric 1.0.0.1035 as the only component, and it is not limited to my setup.

I've also noticed that the freeze issue also affects interface elements such as the seekbar, status bar, and visualizations.

Here's another video:

https://github.com/user-attachments/assets/47f51bfb-299e-4a43-8d8c-38b90b6d0b2f

Also, sometimes when I minimize and restore the window, some interface elements don't appear and take time to load.

![2024-11-18_074618](https://github.com/user-attachments/assets/44034b9b-a156-4ffc-b48b-b152f85e1568)

**Comment by sveakul** [comment]
I just updated to 1.0.0.35 and notice the same issue as MG240--immediately Foobar GUI elements like VU meters began having strange "freezes" and stop/start behavior.  Rolled back to 1.0.0.31 and the problem ceased.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1036

**Comment by MG240** [comment]
1.0.0.1036 fixed the issue for me. Thank you so much.
