### ISSUE TITLE
问题反馈 歌词保存到标签无效

### ISSUE THREAD

**Issue by Rakau** [ESLyric/feedback#213]
**问题描述**
歌词保存到标签无效

**重现步骤**
重现该问题的步骤:
1. 歌词正常显示
2. 右键歌词【歌词保存到标签】
3. 查看标签，歌词标签为空

**期望表现**

歌词标签存在歌词

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows 11 专业工作站版 23H2
 - foobar2000 2.1.2.0
 - ESLyric版本 v1.0.0.1036 (Alpha)

**其他信息**
其他与问题相关的信息

**Comment by a1waysbeta** [comment]
文件什么格式？最好录屏。我这里操作正常

**Comment by Rakau** [comment]
> 文件什么格式？最好录屏。我这里操作正常

FLAC，我是在播放器里的歌词页面保存的，没有效果。从桌面歌词保存就有效。这2个应该不是一个插件吧？

**Comment by a1waysbeta** [comment]
回退老版本可以不？还有别的特殊信息不。目前无法重现

**Comment by Rakau** [comment]
> 回退老版本可以不？还有别的特殊信息不。目前无法重现

用0.5也不行，估计和主题程序有冲突，我用的是georgia-reborn主题。原版没试过，应该是georgia-reborn的问题
