### ISSUE TITLE
Improvements to the Lyric Control Scroll function for unsynced lyrics and some bugs

### ISSUE THREAD

**Issue by TOPMukS** [ESLyric/feedback#214]
**Is your feature request related to a problem? Please describe.**
Thank you for very useful feature Lyric Control Scroll Up and Down! But there are some problems of full use this feature:
1) Low amount of scrolling: I have to press the hotkeys or use mouse wheel many times to scroll half a page.
2) Bug of scrolling when press (Playback / Pause) button: when I do it for playing track and try to scroll up (or down) by mouse wheel it worked 1-2 times of scrolling and after this function and autoscrolling function were not work (freezing!).
3) Bug: save scrolling position. Then you scroll unsynced lyrics for Track1 the scrolling position was saved. And if you play Track2 and play again Track1 (the beginning of the track, 00:00) in the ESLyric Panel will be displayed lyrics on saved positions. This is very inconvenient.
4)Bug: if you assign hotkeys to scroll down, scrolling down is jerky when a track is playing. Scrolling up with hotkeys works faster and smoother.

**Describe the solution you'd like**
1) I think the scroll size should be increased by 4 or 8 times. And it would be ideal if this parameter was configurable by user.
2) It was very useful if Lyric Control Scroll function will be work stable then user press Pause button.
3) In foo_uie_eslyric 3.0.6 (last for Windows XP) it was worked correctly: then you run playing track (the beginning of the track, 00:00) scrolling position set as default (just below the middle of the ESLyric Panel).
4) It would be very nice if scrolling down will be worked as smoothly and at the same speed as scrolling up using hotkeys.

**Additional context**
I use foobar2000 v1.5.11 (very stable release) on Windows 10 x64, Windows 7 x64 and Windows Xp (32 bit) systems (notebooks and desktops). Thank you for support for versions 1.5.. of foobar2000.  And it's a shame that support of versions for Windows XP was ended. Thank you for you foobar2000 component.

**Comment by a1waysbeta** [comment]
This component is mainly used for synchronized lyrics. For asynchronous lyrics, it is best to find a text display script or plug-in. Don't expect too much from updates to this feature.
At the same time, you can upload a sample so that everyone can test it when they have time.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/1.0.0.1037

**Comment by TOPMukS** [comment]
Hi! This is awesome! Unbelievable! Thanks to the developer! 
Now the scrolling setting can be set by the user, it is very convenient. 
Bug number 3 was completely fixed! 
Bugs number 2 and 4 were fixed for the full-screen panel. But there are scrolling freezes after 1-2 times both with the mouse wheel and with hot keys (I set Scroll Up to Ctrl+Up, Scrolling Down to Ctrl+Down) in the regular ESLiric panel on the window of foobar2000. 

I made a video about this and posted it on Youtube (limited access via the link):
https://youtube.com/shorts/CMmIT4bo2RY

Thank you!

**Comment by ESLyric** [comment]
please provide your text lyric and panel settings

**Comment by ESLyric** [comment]
Updated. please reinstall the component.

**Comment by TOPMukS** [comment]
[Cheri, cheri lady - Modern Talking (remix) (-).txt](https://github.com/user-attachments/files/17893284/Cheri.cheri.lady.-.Modern.Talking.remix.-.txt)
![Снимок экрана (814)](https://github.com/user-attachments/assets/46c56f4a-8cb6-426d-89d7-1af2448a5cb7)
![Снимок экрана (815)](https://github.com/user-attachments/assets/1e1532c4-6a39-46c9-badc-adde8555815a)
![Снимок экрана (816)](https://github.com/user-attachments/assets/7a8db1e7-2a3e-4ff6-8c1a-d8caa847cc11)
![Снимок экрана (817)](https://github.com/user-attachments/assets/1658be65-b8a3-4169-b2da-910003686ea8)
![Снимок экрана (818)](https://github.com/user-attachments/assets/fc4422c6-bc85-405a-b23d-04daf40d61a3)
![Снимок экрана (819)](https://github.com/user-attachments/assets/0931eb1c-f6de-44a1-89c1-288a949bfbf8)

**Comment by ESLyric** [comment]
btw you can change scroll factor, valid when page up/down:
![image](https://github.com/user-attachments/assets/d22443b1-a040-4d08-bf9e-9e225c4a00f0)

**Comment by TOPMukS** [comment]
Wow! Thanks for Hotfix! Works very smoothly, perfectly! All bugs were fixed!

P.S. I just noticed that there is a text scaling feature. This is awesome, it is a very useful feature!!! Thank you)
