### ISSUE TITLE
Line space function problem with 1037 hotfix

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#215]
Fixed lyrics, radio stream metadata, Foobar 2.24 x64, Windows 11 23H2.

Previously, when adjusting Panel Options/Spacing Options/Line Space, increasing the number used to move the entire body of the lyrics closer to the top of the panel, maxing out at about 170, which I've used on past versions to make the lyrics start closer to the top of the panel (see 1036.png).

In 1037, the lyrics body start is at one non-movable lower position, and "Line Space" just performs exactly like adjusting the "sentence" value, causing the space between lyrics lines to be way too big when used like in 1036

1036:
![1036](https://github.com/user-attachments/assets/b3c0b5c5-ad50-47aa-88b8-720de9ce6f68)

1037:
![1037](https://github.com/user-attachments/assets/fd628335-6ae9-40f7-b0a4-a424ae05788c)

Please restore the earlier behavior.

**Comment by ohyeah2008** [comment]
1037 was the expected behavior, won't change.

**Comment by ESLyric** [comment]
1037 was the expected behavior, won't change.
