### ISSUE TITLE
Please add option to align lyrics text display to top center

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#216]
Please add the option to align display of fixed lyrics to top center of the panel in oder to make use of empty space when the text language font allows it.  Example from OpenLyrics:

![align top](https://github.com/user-attachments/assets/c5d68286-a15a-47cf-8fdc-ba87ff400004)

Result of "Top centre":

![top centre](https://github.com/user-attachments/assets/af6cfc09-d15d-4288-abc8-0f6bb84b534d)

**Comment by sveakul** [comment]
I was hoping to see a "top center" alignment option for fixed panel in the 1.0.1.2 release, but alas it was not to be.

Surely one of the strengths of ESLyric is that intentionally or not it can function as a desktop display, or within a DUI Foobar text panel.  I would urge the developer to add the option "Top Center" to the ALREADY EXISTING "Alignment" parameters (Left, Center, Center-Left, Center-Right, Right) that appear when using the context menu when lyrics are displayed in the panel.  It would not be a "new feature", but just adding one additional value to an existing feature.  Thanks!

![topcenter](https://github.com/user-attachments/assets/77defc10-2a6c-4b8d-95b6-33ab81bfb382)

**Comment by a1waysbeta** [comment]
Provide a sample of lyrics for special needs, and I'll see what it looks like.

**Comment by sveakul** [comment]
Thanks alwaysbeta for giving this another look!

My lyric sample is the one shown in my comment above--ALL lyrics from any radio streams start at the same height in the panel as this one.  And as you can see, the "Alignment" option is already provided in the context menu, but is just missing a "Top Center" (or Center-Top) choice from the ones already there.  That way there is no wasted blank space at the top of the panel.

**Comment by a1waysbeta** [comment]
Provides a specific stream + which lyrics source to use.

First of all, when I listen to streaming media, I hardly pay attention to the lyrics. I tested it and randomly selected several streaming media to play, but I couldn't find the synchronized lyrics. The non-synchronized lyrics scroll mechanically in the panel. Since my lyrics interface is relatively small, the displayed lyrics can't match the playback content. So this is not a matter of simply adding an option, but using a text display panel instead or right-clicking the lyrics information to view the full lyrics. There is no point in adding a top display. Of course, I will test it again after you provide an example.

**Comment by sveakul** [comment]
All the streams that provide lyrics look the same in the panel, but an example is PopTron ([http://ice1.somafm.com/poptron-128-aac](url)).

I think you are misunderstanding my concern.  It has nothing to do with synced lyrics (most sources are NOT synced); or trying to display ALL the lines at once, only with how static lyrics are aligned in a Foobar panel.  I know those can be autoscrolled but I have that option un-checked in the context menu, and just use the mouse to pull them up or down when I want to see more.

I do not expect to see the full lyrics at once--then the panel would have to be made too big.  I just want them to begin their display at the top of the panel in use instead of halfway down it.  I'm not talking about adding a "top display", just adding the ability to your existing "alignment" option to begin the lyrics centered at the top of the panel in use--a "Center-Top" option, as OpenLyrics offers for its fixed panel display.

The screenshot below shows the placement of the ESLyric panel within Foobar, tabbed for use with other plugins.  The PopTron stream is playing, and its non-synced lyrics begin halfway down the panel, which is just strange looking.  Yes I could pull down the panel's own top margin, but that leaves too small of a space to enjoy the content.  If I can help explain it any better, please let me know.

![poptron](https://github.com/user-attachments/assets/f9623877-4099-4760-8337-93791acf0729)

**Comment by a1waysbeta** [comment]
This request should be either not considered or at the very bottom of the priority list. It is too niche.

**Comment by sveakul** [comment]
A single addition to the already existing "Alignment" option values in the context menu, "Center-Top," is all I was asking for, to join the 5 other ones already there.  It's disappointing that something simple is described as not to be considered.


![center-top](https://github.com/user-attachments/assets/fafe2409-1f2d-41d6-b0a9-5d9527053575)

**Comment by a1waysbeta** [comment]
Because you confused the concepts, the two alignments are not the same concept.

I downloaded openlyrics and tried it. From the results, whether it is synchronized lyrics or non-synchronized lyrics, this fleeting display of the current playing line is not acceptable. The development of components will not tend to be the same.
![微信截图_20241216084127](https://github.com/user-attachments/assets/1f96ea4d-5fad-48e3-a7b6-97e7e484f338)

**Comment by sveakul** [comment]
Not sure what you mean by "fleeting display of the current playing line,"  but I think it has to do with a misunderstanding about the setup and display of lyrics tools in a fixed Foobar panel using "Layout Editing mode."  Below is my tagged panel that can show results from 3 different lyrics plugins.

For streaming radio. when OpenLyrics finds non-synced lyrics after a search, it displays them all in the panel, beginning with the first line, which is aligned to center-top in the panel.  The part of the lyrics that cannot be completely shown due to the length of the panel can be scrolled to by moving them with the mouse.  I'm not using the Library "Album List" display at all, these are not library files.  When the song changes on the stream, the lyrics in the panel are automatically replaced by the ones from the new song, if found.  ESLyric does the same thing, but it starts the first line halfway down the panel, as shown in the post here: [https://github.com/ESLyric/feedback/issues/216#issuecomment-2543849561](url)

![openlyric](https://github.com/user-attachments/assets/4542e5c7-cbe9-4f3b-8f78-ca48e98d6fd4)

**Comment by a1waysbeta** [comment]
1. As you said, the display of lyrics is always subject to the length of the panel and needs to be dragged manually. ESLyric: For asynchronous lyrics, if it starts to play pure music, you can wait for it to scroll by itself. If the vocals have been played when the lyrics are matched, and the lyrics are not fully displayed, you can drag them manually.

2. My screenshot is just a quick test of openlyric. The label name has not been modified, and it is still displayed as album list.

3. For the unique lyric source of ESLyric, you can request openlyric to increase it. After all, it already has the functions you expect.

**Comment by ESLyric** [comment]
You can enabled the highlighted lyric offset option.

**Comment by sveakul** [comment]
> 3\. For the unique lyric source of ESLyric, you can request openlyric to increase it. After all, it already has the functions you expect.

True, but ESLyric is a more advanced plugin than OpenLyric (the Lyric Processor, Search Settings, quantity of searchers) :) .  Anyway, I give up on the request, but thank you for having taken the time to discuss it.  I am certainly going to keep using it.

**Comment by a1waysbeta** [comment]
The method given by the author above can meet your needs.

**Comment by sveakul** [comment]
> You can enabled the highlighted lyric offset option.

THIS WORKS!!!  Man who knew, it was there all the time and I didn't realize it.  For those looking for it, it's in the right-click Panel Options, here:

![offset](https://github.com/user-attachments/assets/9ca98250-d4c7-42e5-ad67-d5cc29b58262)

If you check it and change the default value, the start line of the static display can be adjusted at will.  I found that "34" works for me in my own panel geometry:

![offset2](https://github.com/user-attachments/assets/8370dc70-082e-4a75-af48-ac8e5ec7450d)

**ESLyric (and alwaysbeta!), THANK YOU** so much for staying with me and providing the answer.  **SOLVED!**
