### ISSUE TITLE
Failed to initialize Direct3D, try to upgrade your display driver

### ISSUE THREAD

**Issue by TOPMukS** [ESLyric/feedback#217]
**Describe the bug**
When I intalled ESLyric v.1.0.0.1037 (Alpha) to desktop with Windows 10 it worked perfectly.
But when I installed it to notebooks and desktop with OS Windows 7 I got a red screen with message: "Failed to initialize Direct3D, try to upgrade your display driver". I updated the display drivers but the problem was not solved. I installed all versions with index 1.0.0.... All of them did not work. Version 0.5.4.1028 (Beta) worked. In earlier ESLyric versions GDI and GDI+ worked perfectly. 
I tried to find information about the problem here in ESLyric-Feedback-Issues. The only thing I found was the information in the header of version 1.0.0.1001 Alpha - further translated: The panel and desktop lyrics are rendered using Direct2D/DirectWrite, removing traditional GDI and GDI+ support. Does this mean that there will never be GDI and GDI+ support in the extension? You as a programmer have done a great job of ESLyric development! ESLyric is very useful, beautiful component for the foobar2000 player. Please do not refuse to component support for operating systems versions less than 10.
We hope that maybe you can find a way to create at least irregular releases with the latest changes for legacy operating systems, as Peter Pawlowski does.

Best regards, fans of your talent

**Screenshots**
![photo_2024-11-26_23-49-18](https://github.com/user-attachments/assets/038eb3fa-4a7b-4fca-82be-a1396dd49db6)
![photo_2024-11-26_23-49-15](https://github.com/user-attachments/assets/c07c13e3-8553-4c2a-900b-e113e0e9fdbe)
![photo_2024-11-26_23-49-10](https://github.com/user-attachments/assets/0d00efec-73a4-4c03-8f49-93bedb8e0b1a)

**Desktop (please complete the following information):**
 - Windows Version Windows 7 32-bit and Windows 7 64-bit, Windows XP SP3 with One-Core-Api
 - Foobar2000 Version 1.5.11

**Comment by ESLyric** [comment]
All I can do is adjust the hints.
