### ISSUE TITLE
"Top margin" setting being ignored in 1.0.1.1

### ISSUE THREAD

**Issue by sveakul** [ESLyric/feedback#218]
In Panel Options/Display/Spacing, setting the value for "Top margin" to "0" still results in the first lyrics line being placed way below the top margin, not at zero.  This bug has been present consistently across versions.

![ESLyric](https://github.com/user-attachments/assets/ab9c0ac1-9230-4c70-bd66-05952becf8ed)
![top margin](https://github.com/user-attachments/assets/bcbea959-3f5c-4246-a85a-1f9afbc380e1)

**Comment by ESLyric** [comment]
You probably misunderstand what these margins are, when you adjust margins, you should see the overlay area.

**Comment by sveakul** [comment]
I guess my primary concern is the lyrics themselves and not image overlays, etc. as I do not use the desktop display and just a black background for the panel.  Is there a reason why you DON'T top-align the text?  If there is, I'd like to understand it.  All of the other major lyrics plugins start the lyrics at the top of the panel, as opposed to half-way down the page, like most written material does.  Is there a reason to not even have the OPTION to do so in ESLyric?  Just the OPTION to do so, is all I ask.

The reason I am so concerned with this issue is that ESLyric is my number one lyrics provider and has more performance and more options than any other.  I realize a lot of work has gone into the very popular desktop display option with its image overlays which is beautiful indeed.  And yet using it as a simple fixed panel within Foobar has such an obvious visual problem, that to me would seem easy to provide one additional alignment option for in such a sophisticated package.
