### ISSUE TITLE
COM Automation

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#219]
Hi ttsping,

I need to write two foobar2000 user-components and I need to implement COM automation to have an interface with
JavaScript via the ActiveX object.

I know that your ESLyric and also foo_ui_hacks and foo_vis_vumeter have implemented COM automation because
I am using them.

Do you have a sample you can show me how to implement it?
I have tried with embedded type library, coclass and IDispatch but it seems I can not successfully register
and create the instance via the ActiveXObject. Also none of the user-components ( including yours ), 
are registering and set the UUID's in the registry because I checked via regedit and found no entries. How are you doing it? 
Is it registration-free COM method via manifest file? I also tried but it does not work...

I would appreciate it a lot if you could help me, thanks!

-TT

**Comment by ESLyric** [comment]
You can check [foo_flowin](https://github.com/ttsping/foo_flowin/blob/722a52ebf3ad2ae0b13a0f1528c1bb0fe92809b0/src/initquit.cpp#L38)
which need manifest either.
It may not be the best way to achieve cause it may affect others which uses 'ActiveCtx' and I'm not look into it.

**Comment by ESLyric** [comment]
Or the hacky way, CoRegisterClassObject your class facory and hook 'CLSIDFromProgID', translate your ProgID to CLSID(replace system lookup).

**Comment by TT-ReBORN** [comment]
Thanks! I'll take a look and see how it goes.

**Comment by TT-ReBORN** [comment]
@ESLyric,

I have successfully implemented the interface, but right now, I need to use the `CLSID` instead of the `ProgID`
to create the ActiveX object.

I have successfully mapped the CLSID/ProgID but I am not sure how to implement the hook. 
Do you know the implementation of the hook for the `CLSIDFromProgID` method? 
From my understanding you need to catch and re-route all calls from the original `CLSIDFromProgID` method,
is this done via [Microsoft Detours](https://github.com/microsoft/Detours)? I want to avoid the usage of third-party libs if possible...

I also tried your manifest implementation but it does not work and there is a conflict when two or more components 
are using this method. Example, I have loaded both `ESLyric` and `Flowin` and it does crash, when I remove `ESLyric` from the user-components, it does successfully create the ActiveX object for `Flowin`. Maybe this can be solved if you use the `Isolated COM` feature ( `Project properties` > `Manifest Tool` > `Isolated COM` ) for both of your components.

-TT

**Comment by TT-ReBORN** [comment]
@ESLyric,

I have successfully implemented it, take a look here if you are interested:
https://hydrogenaud.io/index.php/topic,121047.msg1056486.html#msg1056486

Also tried your manifest method but it does not work, loaded both `Flowin` and `ESLyric` 
and tried to create the ActiveX obj but it has conflict. When I removed `Flowin` from the user-components, 
ESLyric did work again. Maybe you could try to use the Isolated COM feature for both in 
`Project Properties` > `Manifest Tool` > `Isolated COM`. 

Wanted to let you know for your info.

Cheers!

-TT
