### ISSUE TITLE
Text in new line with the same timestamp as previous line, isn't prioritized during playback

### ISSUE THREAD

**Issue by xiiyuki** [ESLyric/feedback#220]
**Describe the bug**
When lyrics has blank line at timestamp X, and in the next line there's text starting on X timestamp, it will then get ignored, and the first

**To Reproduce**
For the sake of example, I'll use song `The Marías - No One Noticed`
1. Open foobar2000 with ESLyric plugin
2. Play song `The Marías - No One Noticed`
3. Load [lyrics](https://cdn.discordapp.com/attachments/1016764207246626927/1315827107699626065/The_Marias_-_No_One_Noticed.lrc?ex=6758d2fd&is=6757817d&hm=b49a48c35fd45efe7c70f123faaabe7d8761969903c69e10290ba3ba249140cf&) in ESLyric
4. Notice that each time there's a line of text after a break, it will get skipped

**Expected behavior**
ESLyric displays every line of text without skipping

**Screenshots**
![{0E5B9C01-159A-48E3-B873-DD116CA30AEC}](https://github.com/user-attachments/assets/1f164894-f31e-49d6-8e5e-bf573f3859a3)
![{6017FE0A-E771-42DD-A234-B92FA7A28A4B}](https://github.com/user-attachments/assets/29a1ee10-ff9b-4861-8790-88dae4976c70)

**Desktop**
 - Windows 26100.2314
 - Foobar2000 v2.24 Preview

**Comment by a1waysbeta** [comment]
Right click and check "Show reference lines"

**Comment by xiiyuki** [comment]
> Right click and check "Show reference lines"

It was checked, and unchecking it only removes the line on the second timestamp (So not only it's skipped, it's not displayed at all)

![{9FAD16E2-FAF0-4A8F-8869-7AD61A36151A}](https://github.com/user-attachments/assets/43a26af4-a6a9-4d09-a675-be5e1379791d)

**Comment by a1waysbeta** [comment]
I don't understand what you are talking about. Hasn't every line been shown in your screenshot? It was not skipped either.

**Comment by ESLyric** [comment]
Its expected behavior. Edit your lyrics.
