### ISSUE TITLE
桌面歌词无法显示

### ISSUE THREAD

**Issue by Reapor-Yurnero** [ESLyric/feedback#23]
**问题描述**
打开卡拉OK模式后桌面歌词无法显示，这个问题其实从老版本的eslyrics开始我就一直经历，之前一直可以正常显示桌面歌词，自从某一次叉掉之后就再也显示不出来。尝试过重装foobar，重装不同版本的eslyrics都无法解决。

**软件环境:**
 - Windows10 19044.1889
 - foobar2000 v1.5.5

**Comment by a1waysbeta** [comment]
1，桌面歌词是独立的开关，2，有没有把桌面歌词拖动到屏幕外面去，3，1.5.5好久没用了，你换最新版，便携安装测试一下呢

**Comment by Reapor-Yurnero** [comment]
很神奇 突然就可以了哈哈
