### ISSUE TITLE
希望能在找不到歌词的时候banner显示歌名/艺术家

### ISSUE THREAD

**Issue by ssdzmh** [ESLyric/feedback#24]
**功能简介**
老版本的eslyric似乎在找不到歌词或歌词无效的时候显示歌名和艺术家，希望能在选项里加入此功能。
或是让编辑banner功能支持%title%之类的语法，能提供预览最好。

**Comment by a1waysbeta** [comment]
右键，面板设置，高级，后备文本

**Comment by ssdzmh** [comment]
桌面歌词的部分并不支持使用后备文本，抱歉没有说清楚。

**Comment by a1waysbeta** [comment]
桌面显示，一般没这个需求，你可以考虑在主程序参数选项里设置歌曲改变或暂停时，右下角弹窗通知，自定义通知内容，或者好像有一个foo_osd的插件，可以试试

**Comment by ESLyric** [comment]
有时间看下，但不会有预览

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1015   高级设置里面，你试试
