### ISSUE TITLE
全屏时隐藏歌词问题

### ISSUE THREAD

**Issue by Marisa-Shiriame** [ESLyric/feedback#25]
**问题描述**
勾选"桌面其他窗口全屏时隐藏桌面歌词"后，关闭或者最小化全部程序时歌词会消失

**重现步骤**
重现该问题的步骤:
1. 勾选"桌面其他窗口全屏时隐藏桌面歌词"
2. 关闭或者最小化全部程序，只显示桌面

**软件环境:**
 - Windows11 22000.918&Windows11 22622.590（别的版本没试，我的系统是22622、朋友的是22000，都有这个问题）
 - foobar2000版本 1.6.12

**Comment by a1waysbeta** [comment]
暂时无法复现你的问题，或者给桌面歌词设置一个快捷键，临时显隐切换一下，解决

**Comment by Marisa-Shiriame** [comment]
> 


https://user-images.githubusercontent.com/110273314/188587446-7c329978-3c43-4541-bc02-1488eeab4851.mp4

这样子的情况emmm我这边“显示桌面”也是正常的

**Comment by Marisa-Shiriame** [comment]
> > 关闭或者最小化全部程序，只显示桌面
> 
> 这是怎么操作的，我用右下角任务栏上的 “显示桌面” 未能重现。

这样子的情况emmm我这边直接点击“显示桌面”也是正常的，就是最小化或者关闭全部应用后歌词会随之消失，打开后歌词又会出现

https://user-images.githubusercontent.com/110273314/188588340-4a8d2be9-05a4-4b66-b43e-cbec33344111.mp4



https://user-images.githubusercontent.com/110273314/188588274-f87b837a-c8ae-4676-af02-d8350b6ae233.mp4

**Comment by ESLyric** [comment]
是否有其他工具类软件在运行？可以将其他全部软件退出后再试试。暂时不清楚为什么会有这种情况。
