### ISSUE TITLE
希望能够增加修改歌词标签功能

### ISSUE THREAD

**Issue by Marisa-Shiriame** [ESLyric/feedback#26]
**功能简介**
希望能够在当歌词信息与音乐标签不匹配时，增加选项选择是否根据搜索出的歌词进行音乐标签修改，然后增加一个总开关管理这项功能的开关这样子

**Comment by ESLyric** [comment]
没太明白想要什么，最好带图说明。

**Comment by Marisa-Shiriame** [comment]
> 没太明白想要什么，最好带图说明。

唔，比如说这首歌，假设这首歌是John K的Let Me Let You Go
![TIM图片20220906164214](https://user-images.githubusercontent.com/110273314/188589423-7b1c31a9-5daf-49eb-981d-5726ae0a5bcb.png)，但是由于一些原因，音乐音乐属性信息显示的是One OK Rock的Let Me Let You Go，就是通过音乐属性信息搜索歌词的逆向过程，通过歌词修改音乐属性信息，在使用eslyric的搜索功能手动搜索歌词的时候，如果获取到的歌词的相关信息与音乐属性信息对应不上，选择是否将对应歌曲属性信息替换为歌词的相关信息这样子。

**Comment by ESLyric** [comment]
这个只是少数情况吧，如果音轨的标签信息有误，可以使用其他专门的工具来批量修正。歌词插件没必要做这个。
