### ISSUE TITLE
Force saving lyrics as a prefered format.

### ISSUE THREAD

**Issue by Noobgamer0111** [ESLyric/feedback#29]
An issue I've encountered is that this component likes to save lyrics as either *.lrc or as *.txt. Since I'm using this to grab synced lyrics for my Plex Media Server (PMS), I would like to avoid using *.txt (basic, untimed) as *.lrc is for timed lyrics.

How PMS handles local lyrics: [https://support.plex.tv/articles/215916117-adding-local-lyrics/#:~:text=Naming%20and%20Organization](url)

I would like to choose what format I want to save my lyrics as. This can be added as a drop-down menu under the Lyric Save options (Foobar2000->Tools->ESLyric->Lyric Option).

I have used foo_openlyrics, but the singular dev is somewhat slow in updating, as he prefers to update as slow version (as in 1.1, 1.2, 1.3 etc.)

**Comment by ESLyric** [comment]
do you mean give a option to force save all(include unsynced lyrics) to .lrc files?

**Comment by Noobgamer0111** [comment]
My fault, I meant could I exclude unsynced lyrics, and only search (and save) synced/timed lyrics as *.lrc?

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1015
