### ISSUE TITLE
歌词不能正确置顶

### ISSUE THREAD

**Issue by WritingWithFire** [ESLyric/feedback#30]
**问题描述**
在某些游戏全屏运行时，歌词不能置顶

**重现步骤**
重现该问题的步骤:
1. 勾选“歌词始终在最上面”
2. 打开minecraft，按f11全屏
3. 歌词没有置顶

**软件环境:**
 - Windows 10 pro 21H2 19044.2006
 - 1.6.12

**Comment by ESLyric** [comment]
这个不会“修复”了，因为“窗口置顶”在windows上本就是无限制的。不止游戏，也有可能其他窗口都可以无限制的设置在最上。
