### ISSUE TITLE
希望桌面歌词可以关闭卡拉OK模式

### ISSUE THREAD

**Issue by Hinako0102** [ESLyric/feedback#31]
旧版0.3.6可以在【桌面歌词】【卡拉OK模式】切换卡拉OK模式
更新0.5.3.1011后，选项【卡拉OK模式】变成切换面板显示歌词的模式。【桌面歌词】中没有【卡拉OK模式】无法切换，桌面歌词一直保持卡拉OK模式。

FB2K版本是 1.6.5
操作系统为 windows11 25217

**Comment by ESLyric** [comment]
窗口歌词窗口上右键有
