### ISSUE TITLE
Lyrics Search Results for selection after closing the search window

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#32]
**新功能或功能增强**
In v0.3.6, the search results are still available in the right-click menu for selection after closing the search window. This is useful to test which lyrics is the best. 

However, this function is missing in the v0.5.x version. It is only available in the Desktop "Lyric List". Hope it can be added in the right click menu.

Thanks.

**Comment by ESLyric** [comment]
you can reopen the search window.
