### ISSUE TITLE
双语歌词中的中文翻译在桌面歌词上不显示

### ISSUE THREAD

**Issue by Inotia-216** [ESLyric/feedback#34]
**问题描述**
虽然主界面歌词框内可以显示双语歌词，但是桌面歌词不能显示其中的中文翻译

**重现步骤**
1. 搜索歌词，显示参照行歌词，桌面歌词设置是双行显示、居中对齐
2. 桌面歌词只显示原文，不显示中文翻译

**期望表现**
桌面歌词正确显示中文翻译
**截图**
如可能，请添加截图帮助阐述问题
![QQ图片20221010232645](https://user-images.githubusercontent.com/53962506/194902031-ad051cce-01d1-43d6-95b1-af5b163480b6.png)
![QQ图片20221010232654](https://user-images.githubusercontent.com/53962506/194902133-42e553a7-c6f0-45df-b8a4-96f36d42b51b.jpg)
![QQ图片20221010233836](https://user-images.githubusercontent.com/53962506/194904191-441eb200-57db-43cb-9458-917f3aad77f9.png)

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (如1.6.8)
Win10 企业版 LTSC
Foobar v1.6.12
**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件及对应音频文件
如崩溃请打包crashreport(crash reports目录下)

**Comment by ESLyric** [comment]
在桌面歌词窗口上右键勾选。这个开关各个面板是独立设置的。
