### ISSUE TITLE
匹配到非歌词文件

### ISSUE THREAD

**Issue by vvsolo** [ESLyric/feedback#35]
**问题描述**
有时会匹配到非歌词文件，因为体积过大造成卡顿

**重现步骤**
重现该问题的步骤:
1. 2022 - VA - fabric presents TSHA 专辑
2. 01. Soulful Behaviour - Get To Groove.flac
3. 由规则 `tags` 匹配到一篇小说

**期望表现**
希望添加歌词文件阀值，或限定后缀名（？？）

**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本 (如Windows 11 22621.608)
 - foobar2000版本 (如2.0 beta 12)

**其他信息**
https://wwp.lanzouw.com/iiBZW0drpxyd

**Comment by ESLyric** [comment]
右键菜单手动过滤下这个文件不要搜索歌词。在文件里保存这种东西本来就不是正常的事。

**Comment by vvsolo** [comment]
> 右键菜单手动过滤下这个文件不要搜索歌词。在文件里保存这种东西本来就不是正常的事。

是这样处理的，但遇到这种文件，能卡3、4分钟
建议能设定歌词的字符最大长度，太大的直接过滤

**Comment by ESLyric** [comment]
从tag里删除才是正常的吧

**Comment by vvsolo** [comment]
> 从tag里删除才是正常的吧，或者保存到其他字段，不要保存到歌词的字段。

电子版自带的，不会特意去注意到
总之，感谢你的帮助！

**Comment by ESLyric** [comment]
> > 从tag里删除才是正常的吧，或者保存到其他字段，不要保存到歌词的字段。
> 
> 电子版自带的，不会特意去注意到 总之，感谢你的帮助！

正常应该不会卡这么久 有时间确认下

**Comment by vvsolo** [comment]
608行，60万个字符
渲染时 CPU 风扇狂响🤣

**Comment by vvsolo** [comment]
特意做了测试：
1、openlyrics 和 lyrics3 同样如此
2、CUI 和 DUI 同样如此
3、1.6.12 和 2.0 同样如此
可能是 foobar 本身的问题，并非你的插件原因
抱歉占用了你的时间，再次感谢！
