### ISSUE TITLE
Colours to differentiate singers

### ISSUE THREAD

**Issue by PlaylistsTrance** [ESLyric/feedback#36]
**Is your feature request related to a problem? Please describe.**
Groups with multiple singers often take turns with who's singing. Currently with LRC files it is only possible to show who's singing by adding their name at the start of their line line. It would be nice if it was possible to use colours instead.

**Describe the solution you'd like**
I'm not entirely sure about the best way to implement this as there is no existing standard for it, and sometimes a line is sung by multiple people at the same time. One option would be something like HTML tags such as <c=#fffffff>lyric text</c>, or the user could have a local JSON file with names and colours, such that this could work {Name1}lyric text{/Name1}. When something is sung by multiple people, there is no nice solution, but one way might be to stack colours vertically, such that the top 50% of the letters use the first member's colour, and the bottom half use the other member's.

**Describe alternatives you've considered**
`(Name1)` at the start of someone's line. Example:
```
(Name1/Name2) lyric text ((Name3) ad-lib)
```

**Additional context**
Example can be found here: https://loonatheworld.fandom.com/wiki/Girl_Front#Lyrics

**Comment by ESLyric** [comment]
sorry i has no interest in implmenting a feature without standard specification. there are compatiable issues.

**Comment by PlaylistsTrance** [comment]
I understand. It's probably something I'll need to make myself, unfortunately for me. It's true that it would only work for ESLyric, but maybe that's an advantage as more people might start using ESLyric because of it ;)
