### ISSUE TITLE
Pattern matching priority for automatic LRC association

### ISSUE THREAD

**Issue by PlaylistsTrance** [ESLyric/feedback#37]
**Is your feature request related to a problem? Please describe.**
For example, I have an audio file called "Artist - Title.mp3". Nowadays, I either make karaoke sync `[timestamp]this [timestamp]is [timestamp] lyrics[timestamp]` or line start+end sync `[timestamp] this is lyrics[timestamp]`. However, I always make a standard LRC version (only line start times) for my phone. Therefore, I have filenames `Artist - Title.karaoke.lrc`, `Artist - Title.al.lrc` (`al` stands for AutoLyric, the first software I used that supported line start/end timestamps), and `Artist - Title.lrc`. I like to have the priority in the order of karaoke > fades > standard automatically, but I don't think this is currently possible.

**Describe the solution you'd like**
Similar to the filter interface, I'd like to have an association interface where you can add a way to match by filename (without extension) and additional text (in this case my files end with .karaoke.lrc or .al.lrc).

**Describe alternatives you've considered**
I don't really know an alternative because I need to keep the regular LRC files with identical names as the audio files in the same folder, because my phone's music app doesn't recognize LRC files otherwise, and it only supports standard LRC.

**Comment by ESLyric** [comment]
Goto source list -> local files settings.
add the three filename patterns to the filenames listview in order.
If not works, it could be a bug.

**Comment by ESLyric** [comment]
it seems you cannot add new filename pattern with the latest version. wait for fix. :(

you can try with older versions.

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1016

**Comment by PlaylistsTrance** [comment]
Where can I find source list -> local files settings?

**Comment by a1waysbeta** [comment]
Lyrics source, local file, double click or left click, configuration button on the right side.

**Comment by PlaylistsTrance** [comment]
Okay, I found it. I added `%filename%.al% as pattern and put it at the top, but it still uses the LRC file with the same name as the audio file. Any idea what's causing this?

**Comment by ESLyric** [comment]
yes, audio filename and lyric saved filename are prefered before custom search filenames.

**Comment by ESLyric** [comment]
you can rename your lyric files

**Comment by ESLyric** [comment]
emm... Higher priority for karaoke lyrics when match confidence equals seems reasonable. I will add next version.

**Comment by ESLyric** [comment]
Not configurable. Internal rules.

**Comment by PlaylistsTrance** [comment]
Alright, unfortunate.
