### ISSUE TITLE
歌词搜索区分自动查找和手动查找歌词源范围, 自动查找允许设置为仅从本地文件查找

### ISSUE THREAD

**Issue by Reginald-Yoeng-Lee** [ESLyric/feedback#39]
**新功能或功能增强**
歌词搜索功能区分自动和手动查找两种模式的歌词源范围, 自动查找仅限于从本地歌词文件加载(或指定的数据源), 需要从线上下载时再从其余(或另外)的数据源获取歌词.

**功能简介**
当前版本中, 如果取消`Automatically search when playback starts`选项, 即使歌曲同一目录下已有歌词文件, ESLyric 也不会自动加载本地的数据. 相反, 如果启动了自动搜索, 每次播放一些本地没有歌词的歌曲就会自动在线搜索. 然而存在这样一种场景: 某些歌并非官方版本, 或太冷门没有匹配的歌词, 这样自动搜索就有可能每次都自动加载不匹配的歌词, 或弹出选择框需要用户手动关闭 (视具体配置而定). 如果可以分别独立配置两种搜索歌词方式的查找范围, 应该可以避免这个问题.

**是否有参考软件实现**
千千静听
![擷取](https://user-images.githubusercontent.com/20593866/200341549-9bff4ce6-7761-4565-bc3f-1233cbaa882f.PNG)

**其他信息**
暂无

ESLyric 是个十分优秀的插件, 万分感谢作者的付出.

**Comment by ESLyric** [comment]
自动搜索增加一个选项只从本地源搜索是不是就可以？

**Comment by Reginald-Yoeng-Lee** [comment]
是的, 这样就能解决当前的问题. 如果想要更细粒度的控制, 允许自定义自动和手动两种场景的源无疑是更理想的. 但我对C++不熟,
所以不清楚两者的工作量差异有多大, 可以设置自动搜索只从本地源搜索就已经完全可以满足需求了. 再一次感谢您的时间.

ESLyric ***@***.***> 於 2022年11月8日週二 下午11:00寫道：

**Comment by ESLyric** [comment]
了解。可能会在搜索窗口的搜索按钮菜单上加下。分开设置的时候在这里设置手动搜索歌词源。

**Comment by Reginald-Yoeng-Lee** [comment]
嗯嗯, 如果能保存最近一次的手动搜索的歌词源设置, 不用每次手动搜索都选一次就更方便了

ESLyric ***@***.***> 於 2022年11月9日週三 下午7:56寫道：

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1018

**Comment by Reginald-Yoeng-Lee** [comment]
您好, 已安装最新版本, 删除歌词和选择歌词菜单项可以正常显示, 但自动搜索与手动搜索分开设置歌词源的设置项没有找到, 麻烦能简单说明一下选项位置和使用方式吗?

**Comment by ESLyric** [comment]
搜索窗口搜索按钮上的菜单，不要勾选同步设置就是独立的

**Comment by Reginald-Yoeng-Lee** [comment]
好像还是有点小问题, 重现步骤如下: 
1. 从偏好设置对话框里设置仅从本地文件搜索
2. 重新打开Foobar2000后, 确认即使本地没有歌词文件, 也没有自动从线上查找
3. 进行一次手动歌词搜索, 取消勾选同步设置然后选上其它线上源, 点击搜索, 加载线上歌词. 此时偏好设置对话框里没有同步线上源的设置, 仍然只选中了本地文件
4. 关闭Foobar2000 (没有保存歌词), 重新打开没有本地歌词的歌曲, 触发了自动线上查找歌词

**Comment by ESLyric** [comment]
感谢反馈 修复了 重新下载下

**Comment by Reginald-Yoeng-Lee** [comment]
感谢, 问题已完美解决
