### ISSUE TITLE
双语歌词显示问题

### ISSUE THREAD

**Issue by lychichem** [ESLyric/feedback#4]
**问题描述**
简要清晰地描述问题
桌面歌词无法正确以双排显示双语歌词
**重现步骤**
重现该问题的步骤:
1. 下载一个双语歌词文件
2. 在打开桌面歌词时播放此音频

**期望表现**
简要清晰的表述你期望的表现
期望一行是外语歌词一行是中文翻译
**截图**
如可能，请添加截图帮助阐述问题
![image](https://user-images.githubusercontent.com/9316590/173581955-67b43e0b-ee78-4827-8744-e8303cf9cda2.png)

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (如1.6.8)
Windows 11 22621.160
foobar 1.6.11官方版
**其他信息**
其他与问题相关的信息
如崩溃请附上crashreport(crash reports目录下)
插件信息：
```
Core (2022-05-04 11:52:44 UTC)
    foobar2000 core 1.6.11
foo_albumlist.dll (2022-05-04 11:52:02 UTC)
    Album List 1.6.11
foo_cdda.dll (2022-05-04 11:51:56 UTC)
    CD Audio Decoder 1.6.11
foo_converter.dll (2022-05-04 11:52:00 UTC)
    Converter 1.6.11
foo_dsd_processor.dll (2022-04-29 07:29:24 UTC)
    DSD Processor 1.1.5
foo_dsp_eq.dll (2022-05-04 11:51:58 UTC)
    Equalizer 1.2.2
foo_dsp_std.dll (2022-05-04 11:51:54 UTC)
    Standard DSP Array 1.6.11
foo_fileops.dll (2022-05-04 11:52:00 UTC)
    File Operations 1.6.11
foo_freedb2.dll (2022-05-04 11:52:00 UTC)
    Online Tagger 0.8
foo_input_dts.dll (2020-04-13 12:01:18 UTC)
    DTS decoder 0.6.8
foo_input_dvda.dll (2022-01-19 05:36:46 UTC)
    DVD-Audio Decoder 0.5.3
foo_input_monkey.dll (2021-09-13 06:55:30 UTC)
    Monkey's Audio Decoder 2.5
foo_input_sacd.dll (2022-04-29 07:30:00 UTC)
    Super Audio CD Decoder 1.4.10
foo_input_std.dll (2022-05-04 11:52:16 UTC)
    FFmpeg Decoders 4.4.1
    Standard Input Array 1.6.11
foo_input_tak.dll (2022-05-08 08:23:52 UTC)
    TAK Decoder 0.5.6
foo_input_tta.dll (2020-02-28 06:44:50 UTC)
    TTA Audio Decoder 3.6
foo_out_asio+dsd.dll (2021-12-21 08:47:24 UTC)
    ASIO+DSD support 0.1.6
foo_out_wasapi.dll (2020-12-30 05:08:46 UTC)
    WASAPI output support 3.4
foo_playcount.dll (2020-07-01 14:00:50 UTC)
    Playback Statistics 3.0.4
foo_rgscan.dll (2022-05-04 11:52:02 UTC)
    ReplayGain Scanner 1.6.11
foo_ui_columns.dll (2022-04-22 09:57:02 UTC)
    Columns UI 2.0.0-alpha.1
foo_ui_std.dll (2022-05-04 11:52:04 UTC)
    Default User Interface 1.6.11
foo_uie_eslyric.dll (2022-06-10 17:57:38 UTC)
    ESLyric 0.5.2 (Beta)
foo_uie_vis_channel_spectrum.dll (2008-05-17 19:02:12 UTC)
    Channel Spectrum panel 0.17.2
foo_unpack.dll (2022-05-04 11:52:08 UTC)
    ZIP/GZIP/RAR/7-Zip Reader 1.6.11
```
此外，面板能正确显示，说明歌词解析器本身应该没有问题，只是输出到桌面歌词并呈现的环节有点问题

**Comment by ESLyric** [comment]
在桌面歌词窗口上右键勾选下显示参考行，面板和桌面歌词开关是独立的

**Comment by lychichem** [comment]
感谢前辈，现在可以显示了，只是旧版eslyric保存的逐字歌词的参考行显示有点问题，如图：
![image](https://user-images.githubusercontent.com/9316590/173590933-4f704bfd-9d94-462c-bece-ef48bb004774.png)
应该是在
```語れない 眠れない
无话可说  辗转难眠
```
之后空行，桌面歌词也应该显示是上日语下中文，这里的空行显示好像不太对

**Comment by lychichem** [comment]
内嵌歌词的音频文件链接：https://1drv.ms/u/s!Av7yB71GRfhCk4BRKXvSKjhuqnYZFw?e=oCtUd8

**Comment by ESLyric** [comment]
之前的版本对于这种两行相同时间戳的歌词都是同时显示的。新版本则将相同时间戳的首个作为主歌词，所以上面这种情况看起来只能编辑歌词了。
issue可以先放着，看后续是否有其他反馈。

**Comment by lychichem** [comment]
> 之前的版本对于这种两行相同时间戳的歌词都是同时显示的。新版本则将相同时间戳的首个作为主歌词，所以上面这种情况看起来只能编辑歌词了。
> issue可以先放着，看后续是否有其他反馈。
> 
> 相同时间戳的歌词行可以不相邻，只要保持先后顺序就可以，下面这种形式也是可以正常解析的。
> 
> [00:00.00]英文xxx
> [00:10.00]英文yyy
> [00:00.00]中文xxx
> [00:10.00]中文yyy
> 
> 

明白了，目前我的解决方案是参考前辈这个原理解释，把中文行的起始时间戳改成外文行的起始时间戳就可以了

**Comment by ESLyric** [comment]
> 估计问题原因是这样的：旧版显示双语歌词的时候，中文行（现在的辅助行）的时间戳和下一行一样，现在要求和上一行一样，所以才出现问题了

之前的版本没有考虑过双语歌词的显示，所以行为是不确定的，只是刚好这样的歌词形式可能可以勉强达到想要的显示效果。

**Comment by MC-dusk** [comment]
> 估计问题原因是这样的：旧版显示双语歌词的时候，中文行（现在的辅助行）的时间戳和下一行一样，现在要求和上一行一样，所以才出现问题了

如果两行或多行时间戳一样，我这里（v0.3.6旧eslyric插件）会显示最后一行的内容。所以此时其余相同时间的行相当于上一句歌词（双行桌面歌词会预显示）。

事实上为了更可控的输出效果，会把翻译行的时间戳设为下一行原文时间戳减去一个很短的时间（比如20ms），这样可以间接模拟实现双行显示时，一行原文，一行译文的效果。

[旧版ESLyric-LyricsSource](https://github.com/Robotxm/ESLyric-LyricsSource/tree/master/legacy)和我捣鼓的[QRCD_M](https://github.com/MC-dusk/QRCD_M)都是这么干的。感觉不是插件的预期设计，但确实实现了想要的效果。
