### ISSUE TITLE
双语歌词相关功能请求

### ISSUE THREAD

**Issue by HuxiaoRoar** [ESLyric/feedback#40]
**新功能或功能增强**
1、请问能否添加qq音乐或者更多双语歌词获取？（主）
2、请问能否添加手动选择双语歌词样式？（次）
**功能简介**
试了10首英、日流行歌曲，网易源 能搜出参考行，其他似乎都不行，是因为TME版权相关吗？主要有部分歌曲qq only。如果二者能互补，基本就能涵盖绝大部分歌曲了。
**是否有参考软件实现**
![0](https://user-images.githubusercontent.com/39586235/200865147-88782a4e-c68b-4498-8545-11ceb13dd087.gif)
新插件分板块选择参考行的功能超级赞，非常喜欢，足以满足日常听歌、自动检索桌面歌词使用，不过如果能手动检索不同形式的双语歌词，或许可以满足一些特殊使用的场景。
**其他信息**
非常感谢大佬制作的插件，更感激一直维护更新，老版本已经出现许多兼容性问题了，本想截个图补充说明，但现在已经无法在win 11 dev版 打开0.3.6版本的搜索歌词对话框，打开fb直接闪退，只能找了找以前的gif图。

不知新版脚本能实现上述的两种效果吗？如果可以，我会努力试着根据wiki 搓个脚本出来。主要还是qq源的问题，有了参考行，有没有别的样式也还好了。
个人能力属实有限，感谢大佬读到这里，多有打扰，还请见谅。谢谢

**Comment by a1waysbeta** [comment]
先用qq音乐测试，服务器上是否有这首歌的歌词？是否是带翻译的

**Comment by HuxiaoRoar** [comment]
> 先用qq音乐测试，服务器上是否有这首歌的歌词？是否是带翻译的

测试过，这些歌在QQ音乐都是带翻译的，像群青，向夜晚奔去，梦龙的believer，包括GIF图里，洛天依的t.a.o.都是有歌词和翻译的

**Comment by ESLyric** [comment]
老版本可以显示的形式 新版本都可以，需要自己修改下脚本。解析的时候时间戳相同就会当作有参考行的歌词，原始歌词在前，参考歌词行在后，只要保持这个先后顺序就可以。

**Comment by HuxiaoRoar** [comment]
> 老版本可以显示的形式 新版本都可以，需要自己修改下脚本。解析的时候时间戳相同就会当作有参考行的歌词，原始歌词在前，参考歌词行在后，只要保持这个先后顺序就可以。

感谢大大的回复，那我之后也再摸索看看，祝你生活愉快。

**Comment by MC-dusk** [comment]
双语歌词（Q音、酷狗）可以参考：https://github.com/Robotxm/ESLyric-LyricsSource/tree/master/current 
有些QQ音乐客户端有歌词，但这里脚本搜不到，很奇怪，比如：https://y.qq.com/n/ryqq/songDetail/215573310
