### ISSUE TITLE
Add option "Change lyric" and "Delete lyric" to the context menu

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#42]
Hi ohyeah,

could you please add two options in the context menu ( shift View > ESLyric ) ?
- Shift View > ESLyric > Change lyric ( This function would change the current loaded lyric to the next available lyric source, 
  this is currently working in the Lyric search if you manually double click on a different source, marked green )
- Shift View > ESLyric > Delete lyric ( This function would delete the current loaded saved lyric in the lyric folder )

I would appreciate it, thanks!

-TT

**Comment by ESLyric** [comment]
OK, will add to next version.

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1018

**Comment by TT-ReBORN** [comment]
Thank you ohyeah, tested and it's working good in your ESLyric panel.

The problem is I can't get the "Next lyric" source to work properly in my lyric script.
I need to have the lyric first saved on HDD and then loaded via script to be able to display the lyric.

I'm using this timer method:
```
this.lyricsSearchTimer = setInterval(() => {
	if (this.findLyrics()) {
		clearInterval(this.lyricsSearchTimer);
		initLyrics();
	} else {
		fb.RunMainMenuCommand('View/ESLyric/Panels/Save lyric');
	}
}, 1000);
```

It will search lyrics until found and then automatically saved to lyric directory. After that it will be displayed.

I think you are first loading the lyrics to memory and then display it in your ESLyric panel, is it possible to access it also via Javascript?

I'm trying this workaround but it does not work properly because of delete prompt/confirmation:
```
fb.RunMainMenuCommand('View/ESLyric/Panels/Delete lyric');
fb.RunMainMenuCommand('View/ESLyric/Panels/Select lyric/Next lyric');
fb.RunMainMenuCommand('View/ESLyric/Panels/Save lyric');
initLyrics();
on_playback_seek();
```

-TT

**Comment by ESLyric** [comment]
You probably can't change lyric this way now. ESLyric will execute asynchronously when you run 'Next lyric'. 

You can try the ActiveXObject that eslyric exposed.  [Docs1](https://github.com/ESLyric/release/wiki/%E5%A4%96%E9%83%A8JS%E9%9D%A2%E6%9D%BF%E6%8E%A7%E5%88%B6%E6%8E%A5%E5%8F%A3) and [Docs2](https://github.com/ESLyric/release/wiki/%E6%AD%8C%E8%AF%8D%E6%BA%90%E5%8F%8A%E8%A7%A3%E6%9E%90%E5%99%A8%E8%84%9A%E6%9C%AC)

Enable the interface(see docs) and then:
```
function on_lyric_changed(lyricMeta)
{
       // lyricMeta is a IESLyricMetaInfo object, may be null when not set
       your_parse_func(lyricMeta.lyricText)
}

var eslCtrl = new ActiveXObject("ESLyric");
eslCtrl.SetPlayingLyricChangedCallback(on_lyric_changed);
```
btw. you dont need a hidden panel when you set a callback.

**Comment by ESLyric** [comment]
set 'pref.lyric.deletion.no.prompt'(ESLyric->Advanced) to 1 to disable the prompt when delete lyric.

**Comment by TT-ReBORN** [comment]
Thanks, I got it working, not ideal and perfect but it's working ;-)
