### ISSUE TITLE
Enhanced Lyric .lrc 兼容0.3.X版本ESLyric

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#44]
**Enhanced lyric format**

When a KGmusic .krc is converted to Enhanced lyric, 0.5x handles it differently from 0.3x

0.3x format:
```
[02:02.48]word1[02:02.93]word2[02:03.43]word3[02:03.99]word4[02:04.74]
```

0.5x format, i.e. adding a timestamp at the beginning and changed the timestamp symbol from [ to < for words
```
[02:02.48]<02:02.48>word1<02:02.93>word2<02:03.43>word3<02:03.99>word4<02:04.74>
```
Therefore, the 0.5x enhanced .lyc files cannot be read and used correctly by 0.3x.

However, 0.5x can still read the 0.3x format and display them correctly. When re-saving the lyric file, and the 0.3x format will be used, i.e. it will not be saved in the 0.5x format.

**Suggestion**: 
For a wider compatibility,  the 0.3x format should be used in the 0.5x when converting KGmusic .krc to enhanced .lyc . This is because 0.3x has been there for a while, there are many lyrics in the old format.

A better option is to direct save the **.krc** lyric, rather than converting it to .lrc. This is because Foobar2000 can read .krc format. This will also reserve the .lrc extension to the traditional non-word accurate format. Avoid displaying the timestamps by other players when they read .lrc files that are actually in the enhanced .lrc format.

**Comment by ESLyric** [comment]
0.3 was a 'private' format which should not be used anymore. no plan to save to raw lyric directly.

**Comment by medp7060** [comment]
Understood. Thanks.
