### ISSUE TITLE
Local File Search Settings > Search directories does not accept Title Formatting Syntax

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#45]
**问题描述**
Local File Search Settings > Search directories

Although there is a "**Hint: relative path and title format fields are supported**", there is no way to add such directories that are defined by using the Title Formatting Syntax. It will complain that "Path does not exist" if using the AddDirectory option to add the search directories. The AddDirectory option only allows to select a real directory and cannot accept the Title Formatting Syntax, e.g. 
%fb2k_profile_path%lyrics

**期望表现**
Except the AddDirectory option, add another option to take up the Title Formatting Syntax.

**Comment by ESLyric** [comment]
plz add a exist directory and then edit in place.

**Comment by medp7060** [comment]
Thanks a lot. Haha. Did not know it can be done that way. Perhaps add an "Edit ..." option to the right-click popup menu.

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1019
