### ISSUE TITLE
桌面歌词在自定义字体下可能无法显示

### ISSUE THREAD

**Issue by alphayangyang** [ESLyric/feedback#46]
**问题描述**
某些非系统字体无法在桌面歌词中预览及显示

**重现步骤**
重现该问题的步骤:
1. 在 Desktop Lyrics 中将字体设置为 霞鹜文楷（例）
2. 点击应用

**期望表现**
能够正常显示

**截图**
![屏幕截图 2022-11-18 112541](https://user-images.githubusercontent.com/54565994/202609952-520d246f-0396-4db4-865a-6e2b568bd0a0.png)

**软件环境:**
 - Windows 22H2 (22621.819)
 - foobar2000 v2.0 beta 12 (x86)

**Comment by ESLyric** [comment]
不支持opentype类型字体，短期内也没计划支持。

**Comment by a1waysbeta** [comment]
霞鹜文楷 字体可以显示，本人在用这款。安装了字体需要重启fb，你可能是在开着fb的情况下安装的字体
