### ISSUE TITLE
Copy Lyric ... options - Only include line time stamps

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#47]
**Is your feature request related to a problem? Please describe.**
Add one more option in the **Copy Lyric** menu, so that enhanced lyrics can be saved as the traditional .lrc format, which only includes the line timestamps at the beginning of each line.

**Describe the solution you'd like**
![tempsnip](https://user-images.githubusercontent.com/76891201/202669153-7c3ddab9-f2fb-4a39-8aac-52bf13397c77.png)

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1019
