### ISSUE TITLE
问题反馈：在 "Search Settings" 保存非法设置会导致 Foobar2000 主程序崩溃。

### ISSUE THREAD

**Issue by tglsf** [ESLyric/feedback#48]
**问题描述**
在 "Search Settings" 保存非法设置会导致 Foobar2000 主程序崩溃。

**重现步骤**
重现该问题的步骤:
1. Preferences: ESLyric > Search Settings
2. 选择 Regex Remove String > 在左边的文本框中输入 "("，点击 Add 并保存设置。
3. Foobar2000 主程序崩溃。 `Message: regex_error(error_paren): The expression contained mismatched ( and ).`

**期望表现**
程序拒绝保留非法设置或使非法设置无效。/ 程序不崩溃。

**截图**

**软件环境:**
 - Windows版本 Windows 10.0.19045 x64
 - foobar2000版本 v1.6.14

**其他信息**
```
Illegal operation:
Code: E06D7363h, flags: 00000001h, address: 764CE062h
Additional parameters: 19930520h 008FF418h 6F2B4128h
Message: regex_error(error_paren): The expression contained mismatched ( and ).
Last win32 error: 38

Call path:
entry=>app_mainloop=>eslyric_core::request_lyrics
```

**Comment by ESLyric** [comment]
感谢反馈，下个版本修复。
