### ISSUE TITLE
希望新增「原始歌詞不進行簡繁轉換」功能

### ISSUE THREAD

**Issue by zhtw2013** [ESLyric/feedback#5]
**新功能或功能增强**

希望新增「原始歌詞不進行簡繁轉換」功能

**功能简介**

目前簡繁轉換功能是整個歌詞內容進行轉換
但日文中有些漢化跟簡體中文共通
就會跟簡體中文一起轉換了
希望新增 原始歌詞不做簡繁轉換的功能
(只轉換參照歌詞)

舉例
![image](https://user-images.githubusercontent.com/9501406/175227210-6591a9c6-5bab-49ce-9f2b-ef8daf5bb371.png)

這句歌詞中
「無計画に車を走らせた」

如果開了簡繁轉換
則會將日語的「無計画」轉換成「無計畫 」

![image](https://user-images.githubusercontent.com/9501406/175226966-de25d4cd-3800-428a-a197-364c499ecdf9.png)

這個問題應該只會在有漢字的日語發生
但希望能有選項能單獨設定是否轉換原始歌詞

並希望能預設開啟，原始歌詞當然越「原始」越好

**Comment by ESLyric** [comment]
现在歌词是整体转换然后再解析的，所以可能暂时没法实现。

**Comment by f416720001** [comment]
我的想法是可以來撰寫魔鏡歌詞網爬蟲

另外想問一下 @zhtw2013 是用 opencc 翻譯的嗎
今天才剛裝 ESLyric，看release是透過opencc去翻譯，但太晚沒去了解XD

**Comment by zhtw2013** [comment]
@f416720001 opencc 是進階使用方法
不用 opencc 也能做簡繁轉換，只是效果沒那麼好
opencc 強在能夠自訂詞彙、修正簡繁轉換名詞

過兩天會寫個 opencc 教學

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1005
