### ISSUE TITLE
问题反馈   歌词格式不通用

### ISSUE THREAD

**Issue by Masir01** [ESLyric/feedback#51]
**问题描述**
新歌词格式不被其他软件歌词插件支持

**重现步骤**
重现该问题的步骤:
1. 使用ESLyric保存歌词
2. 使用AIMP播放

**期望表现**
请问新格式有什么优势吗
能否增加关于保存格式的设置
歌词能正确显示

**截图**
![image](https://user-images.githubusercontent.com/32405103/204157858-c99e4259-1bea-4355-86c6-68e4e122cb8f.png)

**软件环境:**
 - AIMP
 - AutoLyric 6.2.1

**其他信息**
现: [00:01.06]<00:01.06>词：<00:01.20>姬<00:01.33>霄<00:01.46>
旧: [00:01.06]词：[00:01.20]姬[00:01.33]霄[00:01.46]
旧格式受支持, 新格式不支持

**Comment by ESLyric** [comment]
新的是更为通用的增强LRC格式。老的格式之前是随便设定的。
