### ISSUE TITLE
When lyrics are embedded point to the file on "Open containing folder"

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#52]
Hi ohyeah,

just noticed that when lyrics have embedded lyrics ( tags ) in the file and the user uses the option
`fb.RunMainMenuCommand('View/ESLyric/Panels/Open containing folder');`
nothing happens. Most users would think this is a bug.

Instead point to the music file, i.e opens containing folder of the music file that contains the embedded lyric:
`fb.RunContextCommand('Open Containing Folder');`

Thanks

-TT

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1019
