### ISSUE TITLE
Show popup error message when failing to save lyric to tags

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#53]
Hi ohyeah,

just encountered a bug when trying to save lyric to tags via 
`fb.RunMainMenuCommand('View/ESLyric/Panels/Save Lyric To/Tags');`
and the music file is readonly.

When something like this happens, we should inform the user via popup with an error message.
Thanks

-TT

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1019
