### ISSUE TITLE
网易云 js 无法正常工作

### ISSUE THREAD

**Issue by nothing-0** [ESLyric/feedback#55]
ESLyric版本是 0.5.3.1018,网易云js是默认的0.1的那个，无法搜索到歌词，脚本测试结果

[eslyric]exec script "C:\tools\play\foobar2000\profile\user-components\foo_uie_eslyric\scripts\searcher\netease.js" begin.
[eslyric]call getConfig
[eslyric]name: 网易云音乐
[eslyric]author: ohyeah
[eslyric]version: 0.1
[eslyric]call getLyrics
[eslyric]HttpQueryInfoA error - 系统找不到指定的文件。  [0x00000002]
[eslyric]undefined
[eslyric]get 0 lyrics
[eslyric]exec script end. elapsed time 0:00.316 

另外，ESLyric 0.3.6版本的 网易云 netease 0.0.2.js 是可以正常搜索到歌词文件的。

**Comment by nothing-0** [comment]
> 请使用1019测试，未发现你这个问题

还是同样的问题，经过进一步测试，2台x64的win7有问题，1台win10的正常，查看抓包结果，正常发送数据，返回数据也正常。

**Comment by ESLyric** [comment]
用什么关键词搜的，我可以试试，如果不行的话就不知道了。
