### ISSUE TITLE
背景

### ISSUE THREAD

**Issue by dghgw2022** [ESLyric/feedback#56]
请问作者,现在如果停止播放歌曲时,背景如何用图片显示,现在只能用纯色,不知该如何设定.

**Comment by a1waysbeta** [comment]
右键-面板设置-背景类型-选择 图片- 图片设置-默认有专辑封面供选择，或者右键添加图片来源

**Comment by dghgw2022** [comment]
播放歌曲时是有背景的,停止后就不显示背景图片了

**Comment by ESLyric** [comment]
添加本地图片文件或目录，勾选始终显示就可以了。
只有和音轨无关的图片才能始终显示。

**Comment by dghgw2022** [comment]
我就是这样的,播放歌曲时是有背景的,但停止后就只显示纯色的,不显示图片,图片是自选的

**Comment by dghgw2022** [comment]
我就是按你说这样的设定的,播放歌曲时是有背景的,但停止后就只显示纯色的,不显示图片,图片是自选的

**Comment by ESLyric** [comment]
截图下你的图片设置或者打包下fb2k看下吧

**Comment by dghgw2022** [comment]
不会上传图片

![image](https://user-images.githubusercontent.com/120238173/206861098-ac48a541-3578-49f8-8e6a-beccd7c6ed7c.png)

**Comment by ESLyric** [comment]
保存到其他不带()的目录吧 ，这里支持titleformat但是没播放的时候又不会去执行。

**Comment by dghgw2022** [comment]
好了,谢谢!

**Comment by dghgw2022** [comment]
原来是文件名的问题,是我自己的问题,谢谢
