### ISSUE TITLE
Is it possible to use the 32bit ESLyric on a WinPE x64 Windows 10 system?

### ISSUE THREAD

**Issue by medp7060** [ESLyric/feedback#58]
**Describe the bug**
This may not be a bug at all. It is just an observation.
On a WinPE x64 Windows 10 system, when use the 32 bit of Foobar2000 v2.0. An error will appear:

Failed to load DLL: foo_uie_eslyric.dll (_checked: it was the x32 version installed_) 
Reason: This component is missing a required dependency, or was made for different version of foobar2000.

However, it works well with the the 64 bit of Foobar2000 v2.0 

So the question is: **Whether it is possible to use the 32bit ESLyric on a WinPE x64 Windows 10 system.**

The reason for using the 32 bit Foobar2000 v2.0 was to use components that have no 64bit compilation.

**Comment by ESLyric** [comment]
install the latest vcruntime and see if it is works

**Comment by medp7060** [comment]
Thank you for your reply. 

I tried it after installing the latest Visual C++ Redistributable (both the x86 and x64 ) from here: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

On WinPE 10 x64, the "foo_uie_eslyric.dll v0.5.3.1019 x32" still cannot be loaded. However, foo_uie_eslyric.dll v0.3.6 worked with "Foo"bar2000 v2.0 beta 17 x32.

**Comment by ESLyric** [comment]
Hmm... i have no clue.

**Comment by medp7060** [comment]
Thanks. I got this:

**Comment by medp7060** [comment]
I guess those DLLs are VC++ x32 runtime DLLs. However, it was not help with the installation of the "Microsoft Visual C++ 2015-2019 Redistributable Package". I wonder why the old version 0.3.6 can run without any issues.
