### ISSUE TITLE
希望新增背景色自动切换功能

### ISSUE THREAD

**Issue by lychichem** [ESLyric/feedback#6]
**问题描述**
简要清晰地描述问题
鉴于column UI已经能支持切换亮色和暗色主题（https://github.com/reupen/columns_ui/releases/tag/v2.0.0-alpha.1 ），能否考虑使面板支持跟随column UI切换主题色
**重现步骤**
重现该问题的步骤:
1. 安装column ui 2.0.0和eslyric 0.5.2 beta
2. 切换主题色

**期望表现**
简要清晰的表述你期望的表现
当column UI为亮色主题时使用白底黑字，为暗色主题时使用黑底白字
**截图**
如可能，请添加截图帮助阐述问题

**软件环境:**
 - Windows版本 (如Windows 10 19043.1586)
 - foobar2000版本 (如1.6.8)
foobar 1.6.11& column UI 2.0.0-alpha1
**其他信息**
其他与问题相关的信息
如歌词显示问题请附上歌词文件及对应音频文件
如崩溃请打包crashreport(crash reports目录下)

**Comment by ESLyric** [comment]
这个需要升级cui的sdk https://columns-ui-sdk.readthedocs.io/en/latest/upgrading.html
如果vs2022是硬性要求的话，还需要升级ESL的项目。
看看使用这功能的人多不多吧，如果不多的话可能优先级会很低。

**Comment by lychichem** [comment]
> 这个需要升级cui的sdk https://columns-ui-sdk.readthedocs.io/en/latest/upgrading.html 如果vs2022是硬性要求的话，还需要升级ESL的项目。 看看使用这功能的人多不多吧，如果不多的话可能优先级会很低。

好的，感谢前辈

**Comment by ESLyric** [comment]
可以试试这个
https://github.com/ESLyric/release/releases/tag/0.5.3.1001
