### ISSUE TITLE
Bouncing ball karaoke

### ISSUE THREAD

**Issue by matthias-vogt** [ESLyric/feedback#60]
I think it would be cool to have a classic bouncing ball karaoke effect for the lyrics (e.g. https://youtu.be/GmmatcEhBsg?t=221) as an option

**Comment by ESLyric** [comment]
perhaps no effects would add to lyric show.

**Comment by matthias-vogt** [comment]
Sorry, I don't understand your comment. I think the bouncing ball would be cool because it helps the singer with the rhythm but I understand if you think it is unnecessary.
