### ISSUE TITLE
Lyric editor deletes enhanced/karaoke timestamps

### ISSUE THREAD

**Issue by Kezwo** [ESLyric/feedback#62]
**Describe the bug**
When creating .lrc files in the enhanced format (karaoke mode) using the Lyric Editor, the lyrics will first get saved correctly, but if you open the lyrics in the editor again, all enhanced timestamps (the ones in <>) get removed. This happens regardless if "karaoke edit mode" is enabled, but even if it wasn't enabled, the editor should obviously never remove any timestamps when opening a file.

**Desktop (please complete the following information):**
Windows 10
Foobar2000 1.6.14
ESLyrics 0.5.3.1019

**Comment by ESLyric** [comment]
cannot reproduce. are you open the same lyric?
