### ISSUE TITLE
桌面歌词在DPI与主显示器不同的屏幕上时会变得模糊

### ISSUE THREAD

**Issue by xmcp** [ESLyric/feedback#65]
**问题描述**
当电脑连接多个显示器、且DPI不相同时，桌面歌词控件始终以主显示器的DPI渲染，因此在其他显示器上会糊。

**重现步骤**
重现该问题的步骤:
1. 让电脑连接两个显示器，主显示器A缩放设置为125%，显示器B缩放设置为250%
2. 打开foobar2000，启动桌面歌词
3. 把桌面歌词控件拖到显示器B的区域
4. 发现歌词显示不清晰，文字有很多锯齿

**期望表现**
歌词应当清晰显示

**截图**

<details>
<summary>在主显示器A（125%）上的效果，桌面歌词与其他程序一样清晰：</summary>
<img src="https://user-images.githubusercontent.com/6646473/210097439-5a2f48de-782d-402c-9bae-8ed106b0117e.png">
</details>

<details>
<summary>在显示器B（250%）上的效果，桌面歌词不如其他程序清晰，而且紫色工具栏相对于桌面歌词控件的位置也乱了：</summary>
<img src="https://user-images.githubusercontent.com/6646473/210097578-2877ba7f-28c3-455b-b1bf-ece47f8e61ae.png">
<i>（如果看不出区别可以点击查看原图）</i>
</details>

**软件环境:**
 - Windows 10 22H2 (19045.2364)
 - foobar2000 1.6.14
 - ESLyric v0.5.3.1019

**其他信息**
我日常使用是主显示器150%、副显示器175%，所以效果没有这么夸张，但仍然有点糊。
移动到其他显示器后重新开关桌面歌词或者重启foobar2000均无法解决模糊问题。

**Comment by ESLyric** [comment]
在显示器B上FB主窗口字体显示正常吗？另外可以尝试在兼容性里设置下foobar2000程序的DPI设置。

**Comment by xmcp** [comment]
把foobar2000.exe的缩放设置调成“应用程序”之后ESLyric就不糊了，但是依旧是以显示器A的DPI渲染（因此歌词和右键菜单等等都比显示器B上的正常字体小一点）。

感觉这个不是ESLyric能解决的问题，得foobar2000适配不同DPI。先close了。
