### ISSUE TITLE
桌面歌词显示参考行之后显示不完整

### ISSUE THREAD

**Issue by xmcp** [ESLyric/feedback#66]
**问题描述**
桌面歌词如果设置成 “显示单行” 且 “显示参考行歌词”，则实际会显示两行，但调整大小后会按单行计算字号，因此文字显示不完整。

**重现步骤**
重现该问题的步骤:
1. 在 设置 → ESLyric → 桌面歌词 中选择 “显示模式”：“显示单行”
2. 播放一首歌词带翻译的歌曲
3. 在桌面歌词控件右键，勾选 “显示参考行歌词”
4. 调整桌面歌词控件大小，发现字号过大，导致两行字都显示不完整

**期望表现**
如果在设置中选择 “显示模式” 是 “显示双行”，则字号正常

**截图**
![image](https://user-images.githubusercontent.com/6646473/210128940-4e5462f6-6a74-41f4-ab70-d0f0ae39bec4.png)

重现 GIF ↓
![cast](https://user-images.githubusercontent.com/6646473/210128869-49079bfe-0e27-4605-b6b9-b6e6f34897f8.gif)

**软件环境:**
 - Windows 10 22H2 (19045.2364)
 - foobar2000 1.6.14
- ESLyric v0.5.3.1019

**其他信息**
可以在桌面歌词设置里手动调整字号，但是此后只要不慎触发调整大小，又会被自动改成过大的字号。
或许应该在计算字号的时候考虑参考行设置，或者在高级选项里加一个 “改变大小时不自动调整字号” 的flag。

**Comment by ESLyric** [comment]
已确认，感谢反馈。

**Comment by a1waysbeta** [comment]
试试。https://github.com/ESLyric/release/releases/tag/0.5.3.1020

**Comment by xmcp** [comment]
经测试问题已解决。谢谢！
