### ISSUE TITLE
后背文本未显示阴影

### ISSUE THREAD

**Issue by xmcp** [ESLyric/feedback#67]
**问题描述**
当没有歌词时，歌词面板会显示设定的后背文本。但是后背文本不遵循阴影颜色设定，始终不显示阴影。

**重现步骤**
重现该问题的步骤:
1. 右键 ESLyric 面板，“面板参数选项”，按下图设置勾选阴影相关参数，把背景设置成专辑封面
2. 播放一首没有歌词的音乐
3. 观察到后背文本没有显示阴影

![image](https://user-images.githubusercontent.com/6646473/210165631-f8755342-6a91-4142-9319-b6922bcf5e79.png)

**期望表现**
在v0.3.6版本中，后背文本会显示阴影

**截图**
最新版（v0.5.3.1019）：
![image](https://user-images.githubusercontent.com/6646473/210165742-93864ecb-8353-4e63-9dc0-0e36c4344185.png)

v0.3.6：
![image](https://user-images.githubusercontent.com/6646473/210165671-3e2ccb2b-992b-4194-89e0-0bd5e824349f.png)

**软件环境:**
 - Windows 10 22H2 (19045.2364)
- foobar2000 1.6.14
- ESLyric v0.5.3.1019

**其他信息**
当使用专辑封面作为背景时，文字没有阴影可能造成文字的易读性问题。
顺便建议像桌面歌词一样增加一个文本轮廓设定。

**Comment by ESLyric** [comment]
感谢反馈，未显示阴影的问题下个版本修复。

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.3.1020

**Comment by xmcp** [comment]
经测试问题已解决。谢谢！
