### ISSUE TITLE
[功能特性] 过滤纯音乐歌词下载，title中没有「instrumental」等字样的

### ISSUE THREAD

**Issue by uoyh** [ESLyric/feedback#69]
**新功能或功能增强**
过滤歌词下载

**功能简介**
过滤对象是title或path中没有「instrumental」等字样的纯音乐

**是否有参考软件实现**
不知道

**其他信息**
功能实现：先让Eslyric搜索下载，下载的歌词文件中出现“纯音乐，请欣赏”，就删除文件或另存到其他目录

**Comment by ESLyric** [comment]
建议你整理标签或文件。
