### ISSUE TITLE
桌面歌词 Outline 的 Width 参数不生效

### ISSUE THREAD

**Issue by JPLiu** [ESLyric/feedback#7]
**问题描述**
ESlyric（版本：0.5.2.1108）中，桌面歌词 Outline 的 Width 参数不生效

**重现步骤**
重现该问题的步骤:
1. 在 ESlyric 的桌面歌词中，设置桌面歌词的 Outline （设置为不是 None）和 Outline 对应的 Width 参数。
2. 无论 Width 设置为多少，桌面歌词的显示效果都是不变的，与 ESlyric 设置内的示意图效果并不一致。

**期望表现**
桌面歌词显示效果与 ESlyric 设置内的示意图一致。

**截图**
![图片](https://user-images.githubusercontent.com/13379952/177001788-dfd34ed6-0106-4527-9178-be33dcf86e8f.png)

**软件环境:**
 - 如Windows 10 19044.1766
 - foobar2000  V1.6.11 原版

**其他信息**
无。

**Comment by ESLyric** [comment]
是bug，一直没注意这个设置。下个版本会修复，感谢反馈。

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1111

**Comment by JPLiu** [comment]
[0.5.2.1111](https://github.com/ESLyric/release/releases/tag/0.5.2.1111)

测试问题已修复，此 issue 关闭。
