### ISSUE TITLE
本地lrc文件显示问题

### ISSUE THREAD

**Issue by pergau** [ESLyric/feedback#71]
**问题描述**
我本地的lrc文件只能显示第一行，需要手动去修改才能全部显示，能不能适配一下这种格式呢

**重现步骤**
重现该问题的步骤:
1. [00:01.00]啊有故的马来西亚
[00:03.00] 
[00:03.00]阿巴阿巴?
[00:06.60] 
[00:06.60]巴拉巴拉
2. 这样隔一行的时间是上一行结束的时间，但是用eslyric只能显示第一行后面就没有了

**期望表现**
minilyric是能够正常显示的，这好像是什么arctime生成的字幕，我电脑上存的都是这种，希望能适配一下

**Comment by pergau** [comment]
试了试qq音乐也可以正常显示，手机上的网易云音乐也可以，可能适配一下不会太难，欧内该

**Comment by ESLyric** [comment]
现在这种形式的歌词在ESL里是作为有参照歌词解析的。

**Comment by pergau** [comment]
> 现在这种形式的歌词在ESL里是作为有参照歌词解析的。

请问可以改设置解决吗还是只能自己手动改lrc了

**Comment by ESLyric** [comment]
没有设置。

**Comment by pergau** [comment]
那请问有希望在未来适配吗

**Comment by ESLyric** [comment]
不会适配。
