### ISSUE TITLE
[歌词保存] 不能正确处理网络路径

### ISSUE THREAD

**Issue by lijunyu-cn** [ESLyric/feedback#72]
**问题描述**
如果将歌词保存位置设为：The same folder as the track，此时Location的值为：$directory_path(%path%)，那么对于形如  \\\\server\share\folder1\folder2的路径，会生成如下重复1次的路径：\\\\server\share\folder1\folder2\server\share\folder1\folder2

**临时解决办法**
将Location的值 $directory_path(%path%) 替换为 . 
在以下插件版本有效，其它版本未测试

**软件环境:**
ESLyric v0.5.3.1020 (Beta)

**Comment by ESLyric** [comment]
感谢反馈，下个版本修复

**Comment by lijunyu-cn** [comment]
0.5.3.1023已修复此问题。
