### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by BeyondandSharp** [ESLyric/feedback#73]
桌面歌词不显示参照行

不同电脑运行相同的版本(fb2k v1.6.16汉化版, ESLyric v0.53.1020)，一个有参照行一个没有，而且我也没找到参照行的开关。
无参照行的电脑其实从这个新版歌词更新以来就没有出现过了。

![image](https://user-images.githubusercontent.com/31413614/218242195-e463b6e9-868c-45d1-9c2e-4c1a60e18819.png)
![image](https://user-images.githubusercontent.com/31413614/218242218-83957eae-c00e-475c-9614-0aceb69e2d75.png)

无参照行: win10 19045.2486
有参照行: win10 19044.1889

**Comment by a1waysbeta** [comment]
参照行开关，在歌词面板右键开启，内嵌歌词和桌面歌词参照行开关是独立的

**Comment by BeyondandSharp** [comment]
> 

那桌面歌词的参照行开关在哪里呢

**Comment by a1waysbeta** [comment]
在桌面歌词右键

**Comment by BeyondandSharp** [comment]
> 在桌面歌词右键

居然是能右键的，谢谢。
