### ISSUE TITLE
更改歌词字体大小后，切换歌曲会导致字体大小改变。

### ISSUE THREAD

**Issue by VoidRambler** [ESLyric/feedback#74]
在桌面歌词设置里面把字体改小并点击应用之后，字体可以正常变小，但是切换歌曲后会重新变大。尝试过导出字体设置后，切换歌曲字体变大时再次导入设置，但后续切歌还是一样的情况。想请问一下是不是我哪个地方设置错了，还是说这里面有些bug。

默认情况下：
![image](https://user-images.githubusercontent.com/38771874/219837920-ff19ba06-82e7-4901-9d90-df4a32c8baea.png)

更改字体以后：
![image](https://user-images.githubusercontent.com/38771874/219838345-c125a93d-900c-45de-8dfb-8b634283ea41.png)

切换歌曲以后：
![image](https://user-images.githubusercontent.com/38771874/219838506-0c75a27f-38b4-448a-9f7c-09c1ceed438d.png)
这里字体有时是53，有时是66。

软件环境:
 - Windows 10 19045.2604
 - foobar2000版本：v2.0 beta 24 [x64]

有空的话请帮忙看一下，谢谢！

**Comment by ESLyric** [comment]
最新版本没有重现。另外可以直接缩放歌词面板来达到更改字体大小的目的

**Comment by VoidRambler** [comment]
好的，我自己再看看是哪里出了问题，谢谢！

**Comment by The-Fool-Nirvana** [comment]
> 

老兄你好，你的问题解决了嘛？你看看我新发的问题描述，是不是你想说的情况。
