### ISSUE TITLE
保存歌詞可選簡體或繁體

### ISSUE THREAD

**Issue by aprils148** [ESLyric/feedback#75]
現在保存歌詞(標籤以及.lrc)似乎只能保存簡體，
希望可以設定保存為簡體或繁體。

**Comment by a1waysbeta** [comment]
参数选项-工具-ESLyric-右侧-歌词处理-右键-预设-转化为繁体

**Comment by aprils148** [comment]
我知道這個,這個只是顯示為繁體,保存還是簡體

**Comment by a1waysbeta** [comment]
ok，确认存在此问题

**Comment by aprils148** [comment]
ESLyric v0.5.3.1023 已可以保存繁體中文
