### ISSUE TITLE
內置簡中翻繁中部分失效

### ISSUE THREAD

**Issue by ccrrow** [ESLyric/feedback#77]
![image](https://user-images.githubusercontent.com/100426674/221893163-86040f57-9b14-48d5-84cd-7a9b216f73ce.png)
如題，插件使用的是0.5.3.1023版
選擇內置的網易雲歌詞（其它的好像也會）
然後用歌詞處理器選歌詞轉繁中
但好像只有日文的部分字符被換成繁中格式了，其它都還是簡體
但還是要感謝大佬的付出，如果有其它可以幫你debug的可以聯絡我，如果找不到我可以mail： tsp34392@outlook.com
我會盡量提供你相關訊息，謝謝

**Comment by a1waysbeta** [comment]
参照行默认不转化，设置里有提示

**Comment by ccrrow** [comment]
![image](https://user-images.githubusercontent.com/100426674/221900156-26fc1f78-f947-45d9-a83f-51db5620d446.png)
我有把這個選項取消勾選了，但好像還是一樣

**Comment by ccrrow** [comment]
阿應該好了，沒事了，只是有一些翻的不太完整而已，謝謝

**Comment by a1waysbeta** [comment]
好的，如果问题解决记得关闭问题哈，感谢你的反馈
