### ISSUE TITLE
艺术家或标题中含有限制字符如"/"等时，保存的文件名会将限制字符转成"_"，但再播放时并不能匹配该保存的歌词文件

### ISSUE THREAD

**Issue by LetCodeGo** [ESLyric/feedback#8]
**问题描述**
如题
还有一个问题就是，Search Filter和Search preprocessor中对字符串的处理应该没必要区分大小写。

**Comment by ESLyric** [comment]
> 艺术家或标题中含有限制字符如"/"等时，保存的文件名会将限制字符转成"_"，但再播放时并不能匹配该保存的歌词文件

这个麻烦提供一下示例

> 还有一个问题就是，Search Filter和Search preprocessor中对字符串的处理应该没必要区分大小写。

同样请提供下示例

> 本地歌词匹配还是有问题

这里的处理器不仅用于搜索关键字，也用于搜索到的文件名。之前版本默认的一个正则移除feat的有点问题，最新的改成了正则替换（需要重置配置）。你这种情况也可以修改下，比如使用正则替换\s?feat.*-)为 -

**Comment by LetCodeGo** [comment]
> > 艺术家或标题中含有限制字符如"/"等时，保存的文件名会将限制字符转成"_"，但再播放时并不能匹配该保存的歌词文件
> 
> 这个麻烦提供一下示例
> 
> > 还有一个问题就是，Search Filter和Search preprocessor中对字符串的处理应该没必要区分大小写。
> 
> 同样请提供下示例
> 
> > 本地歌词匹配还是有问题
> 
> 这里的处理器不仅用于搜索关键字，也用于搜索到的文件名。之前版本默认的一个正则移除feat的有点问题，最新的改成了正则替换（需要重置配置）。你这种情况也可以修改下，比如使用正则替换\s?feat.*-)为 -

还有一个就是处理大小写的问题，标题和艺术家中有时是feat有时是Feat，还有live和Live等等，而正则表达式处理是区分大小的。实际上区分大小写没什么意义，处理后进行网络搜索大小写也没什么意义。

**Comment by ESLyric** [comment]
> 说说我的想法，搜索本地歌词文件不应该进行处理（只把限制字符替换成'_'），处理只针对网络搜索。
> 保存歌词时是以[%artist% - ]%title%文件名保存，搜索本地就以[%artist% - ]%title%文件名查找，没找到就分别对标题和艺术
> 家进行处理后进行网络搜索。

好的，以上问题已收到。其中正则区分大小写这个问题，代码和实际测试都是正常即不区分大小写的，可否再提供下你的测试例子？搜索关键字处理这个我先考虑下做法。

**Comment by LetCodeGo** [comment]
> 

比如 Search Filter里设置 %genre% regex match 这里是区分大小写的，而 %genre% is 就没。

**Comment by LetCodeGo** [comment]
> > 说说我的想法，搜索本地歌词文件不应该进行处理（只把限制字符替换成'_'），处理只针对网络搜索。
> > 保存歌词时是以[%artist% - ]%title%文件名保存，搜索本地就以[%artist% - ]%title%文件名查找，没找到就分别对标题和艺术
> > 家进行处理后进行网络搜索。
> 
> 好的，以上问题已收到。其中正则区分大小写这个问题，代码和实际测试都是正常即不区分大小写的，可否再提供下你的测试例子？搜索关键字处理这个我再考虑下做法。

比如 Search Filter里设置 %genre% regex match 这里是区分大小写的，而 %genre% is 就没。

**Comment by ESLyric** [comment]
> 比如 Search Filter里设置 %genre% regex match 这里是区分大小写的，而 %genre% is 就没。

现在‘是’ '包含'等都是不区分大小写的，'是'要两个字段相等，可以确认看看实际上是不是，可以的话上传下音频文件及截图下测试的过滤条件。

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1117
