### ISSUE TITLE
升级时会把定制脚本删掉

### ISSUE THREAD

**Issue by szc126** [ESLyric/feedback#80]
**问题描述**
如题（升级eslyric时会把定制脚本删掉）

**重现步骤**
重现该问题的步骤:
1. 把新的脚本放在parser、searcher里
2. 升级eslyric
3. 检查「歌词来源」列表或上述的文件夹

**期望表现**
脚本存续

**截图**
无

**软件环境:**
 - Windows 10、Wine 8.2
 - foobar2000 v2.0 beta 24 [x86]

**其他信息**
（Wine下）脚本如果是symbolic link则会导致
- 把首一个symbolic link的目标文件删掉
- 「foobar2000 component maintenance failure／Could not update component: Directory not empty／Abort、Retry、Ignore」
（Windows 10无法读取Linux所作的symbolic link）

**Comment by ESLyric** [comment]
试试 https://github.com/ESLyric/release/releases/tag/0.5.3.1025

**Comment by szc126** [comment]
没问题了，谢谢！
