### ISSUE TITLE
在编辑歌词界面可否做个隐藏<>标签的选项，可以称为练唱模式

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [ESLyric/feedback#83]
**新功能或功能增强**
可以加个练唱模式吗，就是和编辑歌词那个界面类似，我这几天就在用编辑歌词界面反复听某一句，但是只有那种只标记了方括号的使用起来体验比较好，有<>标签的就不是很方便，可以做一个隐藏<>标签的选项吗，而且歌词渲染的时候还是可以根据<>标签渲染

想要的界面如下
![image](https://user-images.githubusercontent.com/56683174/227568998-161aae1e-6c3a-4876-9a78-e02ff3153f0b.png)

现在的界面
![image](https://user-images.githubusercontent.com/56683174/227569387-4372657b-351b-49f0-94a6-fb67587fbef0.png)

**Comment by ESLyric** [comment]
小众需求不考虑。可以直接看面板歌词或者删除全部标签或者手动复制为标准歌词。

**Comment by a1waysbeta** [comment]
或者可以双击歌词面板进入全屏，或者歌词面板右键，歌词信息，界面也是纯文本

**Comment by Unknown-Chinese-User** [comment]
行吧
