### ISSUE TITLE
网易云歌词搜索问题

### ISSUE THREAD

**Issue by mouyuu** [ESLyric/feedback#84]
**问题描述**
搜索歌词时若包含艺术家搜索不到。如图(https://i.328888.xyz/2023/04/01/i2WUgJ.png)
若删去艺术家则可以。如图(https://i.328888.xyz/2023/04/01/i2Wblz.png)

**软件环境:**
 - Windows 10 19045.2604
 - foobar2000 1.6.16

**其他信息**
eslyric已更至最新，网易云音乐来源版本为0.2

**Comment by a1waysbeta** [comment]
网易云网站这首歌的标题中间有一个:，你把你的歌曲名改为网易云的试试呢。
