### ISSUE TITLE
桌面歌词字体大小切歌后会自适应面板高度改变

### ISSUE THREAD

**Issue by The-Fool-Nirvana** [ESLyric/feedback#85]
**问题描述**
看到之前有人提这个问题，但是他表述的不明确。
自己桌面歌词显示面板高度设置的较大，多次尝试后，按顺序会出现下面的情况：
1.前一首歌有参照行歌词，字体大小设置的较小，切换到下一曲，下一曲也有参照行歌词，字体没有改变；
2.前一首歌有参照行歌词，切换到下一曲，下一曲没有参照行歌词，字体大小会自适应显示面板的高度（这里因为显示面板高度设置较大，字体变大）；
3.紧接着2，下一首切换到有参照行歌词的曲子，字体大小又会自适应显示面板的高度（较2的大小是变小）；
4.后面多次切换有（无）参照行的歌曲，字体大小像2、3中那样自适应面板高度了，但是回不到一开始设置的固定值；
5.回退到1019版本，字体大小为固定值，无论切换到有无参照行都是固定值。

总结：
1.若歌曲均有（无）参照行歌词，无事发生；
2.若下一曲歌词参照行的有无出现变化，字体大小立刻自适应面板高度，且后续不会再回到原来设定的固定值。

**期望表现**
不清楚是bug还是之后版本做成这样的，个人还是比较喜欢歌词字体大小为固定值，不会因为有无参照行歌词切换后改变大小。
显示面板的高度设置较大原本是想借此调整参照行和原词之间的间隔的。

**软件环境**
foobar2000 1.6.16
0.5.3.1019之前没有这个问题
0.5.3.1020之后开始出现这个问题

大佬有空帮忙看一下，先谢谢大佬了！

**Comment by ESLyric** [comment]
设计如此，换成双行显示就不会调整。

**Comment by The-Fool-Nirvana** [comment]
> 

原来是这样，谢谢大佬解答。
