### ISSUE TITLE
超过一个小时的歌词部分不能显示，也不能编辑

### ISSUE THREAD

**Issue by WhoisMorgan** [ESLyric/feedback#86]
**问题描述**
作者你好，我使用的是Foobar2000 v1.6.16 汉化（2023.03.26）
这个版本的软件。我想反映一个bug，不知道是软件本身还是eslyric这个插件的问题。
事情是这样的，我正在制作一首时长超过一个小时的音乐的歌词，可是我在使用编辑歌词的功能时发现Foobar不支持编辑超过一个小时的部分的歌词（可以编辑但是点击“跳转到当前行”时没有反应），也不会时长超过一个小时的那部分歌词。请问有解决办法吗？

> 

> 

> 

1. > **重现步骤**

- [ ]  #@[重现该问题的步骤:]( #url)

1. 制作一首时长超过一个小时的音乐的歌词
2. 在超过一个小时的部分进行编辑

**期望表现**
我希望可以制作超过一个小时的歌词

**截图**
/

**软件环境:**
/
 - Windows版本 (如Windows 10 )
 - foobar2000版本 (Foobar2000 v1.6.16 汉化（2023.03.26）)

**其他信息**

**Comment by WhoisMorgan** [comment]
我知道了！！！
“由此可见LRC格式的局限性，超过60分钟的视频，以及超过99分钟的视频无法按此规则显示
因为LRC本身为显示歌词设计，一首歌曲/MTV的时间一般不超过60分钟”

**Comment by ESLyric** [comment]
麻烦提供下歌词和音频示例
