### ISSUE TITLE
酷狗双语歌词保存

### ISSUE THREAD

**Issue by axojhf** [ESLyric/feedback#87]
**新功能或功能增强**
酷狗双语歌词保存

**功能简介**
目前酷狗解析到的双语歌词点击保存后只会保留原歌词，旧版ESLyric可以保存酷狗的双语歌词，希望新版也能保存

**是否有参考软件实现**
旧版ESLyric

**其他信息**
感谢大佬的持续更新

**Comment by ESLyric** [comment]
提供歌词文件或搜索关键词

**Comment by axojhf** [comment]
> 没有搜到酷狗有双语歌词。

啊，不会吧，为什么我能搜得到😂
![image](https://user-images.githubusercontent.com/20625305/232536176-78200280-4d5a-41b9-818d-930b311ba947.png)

**Comment by axojhf** [comment]
因为最开始使用的是别人打包好的汉化版，最近更新到的最新版的ESLyric(v0.5.3.1028 (Beta))，抱歉不知道初始原版本能否解析酷狗的双语字幕

**Comment by axojhf** [comment]
> 试试，https://github.com/ESLyric/release/releases/tag/0.5.3.1031

可以了，感想开发者

**Comment by dghgw2022** [comment]
Could not update tags (File is already in use) on:
"D:\伴奏\容祖儿\容祖儿-这么近那么远.mkv"
MKV这种格式的写标签还是不行，出错
