### ISSUE TITLE
Is the lyrics editor removed?

### ISSUE THREAD

**Issue by girtabb** [ESLyric/feedback#88]
I've recently updated to a newer version, and the button isn't there anymore. Any help?
![screenshot](https://user-images.githubusercontent.com/131411046/233501484-6f76f66c-d7c8-4f64-bdaf-78af0c8df941.png)

**Comment by a1waysbeta** [comment]
You can hold down the shift key before clicking on the main menu. Of course, a more intuitive operation is to right-click on the lyrics panel.

**Comment by girtabb** [comment]
It doesn't seem to work for me. I'm holding shift while clicking every button but nothing works. Also right clicking.

**Comment by girtabb** [comment]
Oh wait i figured it out. Thanks
