### ISSUE TITLE
安裝最新版後eole主題歌詞頁面報錯

### ISSUE THREAD

**Issue by aunight** [ESLyric/feedback#89]
錯誤如圖希望可以修正
![image](https://user-images.githubusercontent.com/52199445/235178772-79ad4f70-fdf6-4de0-a77b-7005010a81ad.png)
原本使用舊版本的ESLyric，但因為大部分的歌曲中文歌詞失效
所以重裝新版的但安裝可能因主題衝突而無法使用
希望可以修復 謝謝~
使用主題連結 [Eole](https://github.com/Ottodix/Eole-foobar-theme)

**Comment by a1waysbeta** [comment]
请更新你的eole ，看eole 官方更新说明

**Comment by aunight** [comment]
好的 感謝

**Comment by aunight** [comment]
![image](https://user-images.githubusercontent.com/52199445/235343000-c46202c9-b22d-44b5-a0e3-486ffbda92c0.png)
更到最新版的了 但仍然無法正常顯示

**Comment by a1waysbeta** [comment]
应该是个人操作问题，eole 有针对性更新

**Comment by aunight** [comment]
有我重新安裝了 目前可以正常運作 但想詢問一下之前記得歌詞有簡體轉繁體的功能 想詢問一下目前最新版本還有此功能嗎?
有設定的位置嗎? 感謝

**Comment by a1waysbeta** [comment]
https://github.com/ESLyric/feedback/issues/77

https://github.com/ESLyric/release/discussions/18

**Comment by a1waysbeta** [comment]
解决了问题记得及时关闭
