### ISSUE TITLE
QQ歌词能搜索出来，但是不能下载

### ISSUE THREAD

**Issue by simear2004** [ESLyric/feedback#9]
**问题描述**
QQ歌词能搜索出来，但是不能下载，手动双击也不能下载歌词

**软件环境:**
 - Windows版本 (如Windows 11)
 - foobar2000版本 (如1.6.11)

**其他信息**
歌词版本：0.5.2.1111

**Comment by ESLyric** [comment]
麻烦提供下一个异常的搜索示例

**Comment by ESLyric** [comment]
https://github.com/ESLyric/release/releases/tag/0.5.2.1117
