### ISSUE TITLE
Typo in Preferences

### ISSUE THREAD

**Issue by grimes2** [ESLyric/feedback#90]
Typo in Panel Preferences | Advanced | Fallbac Text (Fallback Text).

**Comment by a1waysbeta** [comment]
You can submit a PR here to prevent the author from forgetting the next update, haha. https://github.com/ESLyric/release/blob/main/locale/en_US.lng

**Comment by ESLyric** [comment]
fixed in https://github.com/ESLyric/release/releases/tag/0.5.4.1001
