### ISSUE TITLE
关闭桌面歌词中文翻译选项

### ISSUE THREAD

**Issue by a442509097** [ESLyric/feedback#91]
希望能增加关闭的开关. 另外就是使用桌面歌词, 关闭k歌模式, 字体设置为72, 都居中对齐, 听英文歌, 当歌词太长时, 滚动的速度慢了一点, 往往一句唱完, 还没移动到最后. 还有就是偏移时间感觉还是以前的500毫秒起步比较好.

**Comment by a1waysbeta** [comment]
桌面歌词右键，关闭参照行。
滚动慢是否跟歌词时间戳不准有关

**Comment by a442509097** [comment]
@a1waysbeta 
不行, 只能对软件框内歌词生效, 桌面歌词不起作用.
![Snipaste_2023-05-26_09-14-29](https://github.com/ESLyric/feedback/assets/17733616/959de82e-3edf-4adc-9d74-2b1b411b66bb)
另外发现无法保存歌词, 如选下面这个歌词, 停止, 再次播放后歌词就变回别的(已经点了保存歌词).
![Snipaste_2023-05-26_09-05-19](https://github.com/ESLyric/feedback/assets/17733616/7abdb0b4-e1a3-4418-a2b4-66f0d08889d9)
还有就是歌词搜索还未都完成时, 立即任意点一个, 也是会被恢复的. 

![Snipaste_2023-05-26_08-54-02](https://github.com/ESLyric/feedback/assets/17733616/63318205-572b-42a5-9fbb-94654ce27b18)

**Comment by a1waysbeta** [comment]
让你在桌面歌词上点右键关闭，你要去软件框内点。


无法保存的问题描述不清晰，你的歌词源，保存位置，歌词匹配等

**Comment by a442509097** [comment]
@a1waysbeta 不好意思, 大意了,当时没找到, 关闭中文翻译搞好了.
无法保存歌词问题, 我只要选择"保存歌词至 音轨所在目录"就行了.
![Snipaste_2023-06-03_15-25-50](https://github.com/ESLyric/feedback/assets/17733616/2df37695-ad90-44e6-9d3c-097f59a1715a)
如何直接选择 "保存歌词" 就不行了, 连偏移信息都无法保存, 应该是之前版本留下的歌词, 被选择在了这个旧歌词, 我重新在选项里勾选新的那个歌词就行了.

**Comment by a1waysbeta** [comment]
嗯嗯，解决问题之后关闭问题
