### ISSUE TITLE
双语歌词保存

### ISSUE THREAD

**Issue by MoeYks** [ESLyric/feedback#93]
新功能或功能增强
网易云、QQ音乐双语歌词保存后，原文歌词和翻译歌词公用相同的时间轴，导致使用用walkman播放歌曲时，只能显示原文歌词不能显示翻译歌词。
例如：
[00:13.03]本当は　わかってたんだ
[00:13.03]其实我一直都知道

[00:19.23]自分にウソをついていること
[00:19.23]我一直在欺骗我自己

[00:25.74]本当は　知ってたんだ
[00:25.74]其实我一直都知道
> 
希望可以出个将原文歌词和翻译分离，套用不同的时间轴的插件版本。

功能简介
原文歌词和翻译分离，套用不同的时间轴，以适配walkman实现双语歌词的显示。

是否有参考软件实现
1.以前用旧版的ESLyric中有搜索歌词保存时有选择并排歌词的选项。
2.https://github.com/Ludoux/LRCHelper/

感谢大佬的持续更新

**Comment by ESLyric** [comment]
可以自己修改歌词脚本。插件本身不打算兼容这种没规范的了。

**Comment by MoeYks** [comment]
好的，感谢大佬
