### ISSUE TITLE
左行文字标点位置错误

### ISSUE THREAD

**Issue by Bobo-alcazar** [ESLyric/feedback#95]
**问题描述**
左行文字（如方体亚兰字母），本应出现在句末，即左方的标点出现在了右方。

**重现步骤**
重现该问题的步骤:
1. 找一个左行文字的歌词（比如<http://music.163.com/api/song/media?id=444425454>）
2. 导入foobar，并用 ESLyric 显示歌词

**期望表现**
整个text都应该是左行的，但实际上只有方体亚兰字母部分左行了，结果是句末的标点符号视觉上出现在了句首

**截图**
应该不需要了吧，挺明白的

**软件环境:**
 - Windows 10 19045.2965
 - foobar2000 2.0

**其他信息**
没有排查其他，但我怀疑可能未对非横排右性文字作过专门适配，建议是可以对各向文字都作以下适配，然后允许在首选项里单独调。（毕竟软件不可能自动判断歌词所使用的文字）

**Comment by Bobo-alcazar** [comment]
> 听不懂看不懂

![圖片](https://github.com/ESLyric/feedback/assets/62412037/662abc5f-127a-4e3d-b5e5-7ef9fa5987ec)


右边是HyPlayer调用DirectWrite的实现，句末标点是在左的。左边是ESLyric，标点出现在了句首。

**Comment by Bobo-alcazar** [comment]
这可能不太好解决吧。。。太底层了。只是提一下，要是有办法优化的话就最好了。

**Comment by ESLyric** [comment]
esl也有dwrite的 可以先试试有没有区别。有时间我看下。

**Comment by ESLyric** [comment]
调整之后显示顺序看起来正常，但是有其他问题，没有太多时间去处理这些细节了。因此这个暂时不会修改。
