### ISSUE TITLE
网易云歌词搜索出现完全无关内容

### ISSUE THREAD

**Issue by MalitsPlus** [ESLyric/feedback#96]
**问题描述**
ESLyric 歌词搜索时出现完全无关内容

**重现步骤**
重现该问题的步骤:
1. 进入 ESLyric 歌词搜索界面，搜索网易云音乐歌词。
2. 查看检索结果。

**期望表现**
出现与检索曲目正确对应的搜索结果。

**截图**
- UI 截图
![image](https://github.com/ESLyric/feedback/assets/50281195/335dd27b-229d-4497-b228-17a161f8a243)

- 调试截图
![image](https://github.com/ESLyric/feedback/assets/50281195/990ea1b0-13ce-4b4b-81b8-276a2f8bfb61)

**软件环境:**
 - Windows 11 Pro 22621.1702
 - foobar2000版本 v2.0 x64

**其他信息**
尝试搜索其他曲名依然出现完全不对的检索结果，并且所有检索结果的曲名都是数字（就像上图的 「16」一样，在我尝试过程中还出现了「2」「13」等 ），并且尝试从网易云音乐 APP 端检索这些歌曲的歌词是存在的。

**Comment by a1waysbeta** [comment]
提供几个歌曲名，艺术家，日语不好打字

**Comment by MalitsPlus** [comment]
不仅仅是日文歌，任何歌曲都是同样的结果。

例
- パレイド - 夏川椎菜
- 第二人生 - 五月天
- Hotel California - Eagles

**Comment by a1waysbeta** [comment]
![image](https://github.com/ESLyric/feedback/assets/11453148/0791e4ef-8d20-4903-915b-0b9b007afc48)
![image](https://github.com/ESLyric/feedback/assets/11453148/be7b25ed-f0c1-4ec4-af6a-46e713f9e215)
网易云脚本版本号0.2，没遇到你的问题。你可以更新一下脚本。

**Comment by MalitsPlus** [comment]
![image](https://github.com/ESLyric/feedback/assets/50281195/e514aa58-3dfe-4045-9f5f-3ac30b1e414f)

看了下版本号就是 0.2，不知道是不是跟你一样。

**Comment by MalitsPlus** [comment]
diff 了一下我本地的 netease.js 和 [这个](https://github.com/ESLyric/scripts/blob/970349e449f6b08c0b314db2803ac46c80d16b24/searcher/netease.js) 脚本，两者没有任何区别。

**Comment by a1waysbeta** [comment]
你安装网易云试试，

**Comment by MalitsPlus** [comment]
折腾了半天仿照 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 向 Cookie 中添加 `anonymousToken` 之后搜索结果正常了。

![image](https://github.com/ESLyric/feedback/assets/50281195/0ac9f913-b9f2-4f80-b063-1b840617a44c)

不知道是不是对一部分 IP 有强行限制。

https://github.com/MalitsPlus/scripts/commit/d185160276c75a4a29dc12e97ab86db8e00b3b27
我 Fork 了一份，如果有需要我可以提交 PR。

**Comment by ESLyric** [comment]
> 折腾了半天仿照 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 向 Cookie 中添加 `anonymousToken` 之后搜索结果正常了。
> 
> ![image](https://user-images.githubusercontent.com/50281195/244873005-0ac9f913-b9f2-4f80-b063-1b840617a44c.png)
> 
> 不知道是不是对一部分 IP 有强行限制。
> 
> [MalitsPlus/scripts@d185160](https://github.com/MalitsPlus/scripts/commit/d185160276c75a4a29dc12e97ab86db8e00b3b27) 我 Fork 了一份，如果有需要我可以提交 PR。

可以的 欢迎PR。需要同时修改脚本版本号及version.json里的版本号
https://github.com/ESLyric/scripts/blob/970349e449f6b08c0b314db2803ac46c80d16b24/archive/version.json#LL28C26-L28C26
另外提交中的headers设置建议放到一起，中间不要间隔其他代码。
