### ISSUE TITLE
保存非同步歌词时会回顶、停顿

### ISSUE THREAD

**Issue by szc126** [ESLyric/feedback#97]
**问题描述**
保存非同步歌词时会回顶、停顿

**重现步骤**
重现该问题的步骤:
1. 从网络读取非同步歌词
2. 等到自动保存（1:00）或从菜单手动保存

**期望表现**
简要清晰的表述你期望的表现
- 继续滚动

**截图**
如可能，请添加截图帮助阐述问题
- 无

**软件环境:**
 - Windows 10、Wine
 - foobar2000版 v2.0 [x86]

**其他信息**
其他与问题相关的信息
- 调整窗口的大小以诱导换行后也会恢复

**Comment by ESLyric** [comment]
ESLyric是最新版吗？印象中有处理过这个问题。

**Comment by szc126** [comment]
0.5.3.1031，仍然有問題。

**Comment by ESLyric** [comment]
试下新版本
https://github.com/ESLyric/release/releases/tag/0.5.4.1001

**Comment by szc126** [comment]
没问题了，谢谢！
